### ISSUE TITLE
Installing Emulator for Android Studio Problem 

### ISSUE THREAD

**Issue by ShivaShirsath** [termux/proot-distro#100]
How to enter in startup BIOS for enabling Virtualization Technology.

**Comment by ZhymabekRoman** [comment]
> How to enter in startup BIOS for enabling Virtualization Technology.

proot is easily understood as a more modern term virtual environment. The process gets a new, virtual, root directory to establish path visibility. This is mainly a convenient and simple way to control what files and libraries can be referenced by the process. It is very helpful for isolating from things that might have different versions available on the actual file system. The proot/chroot uses the kernel of the main (host) system, which in our case is the kernel of the Android system - Linux. There is no separate kernel/virtualization/BIOS in the proot system.

Use for this case QEMU (NOT user static!) or maybe Bochs for Android

**Comment by ShivaShirsath** [comment]
I want to run emulator in android studio. without emulator or Virtualization Technology, no one app getting build Or showing preview.

If there is any way to build app, please suggest me !

Thank you for your attention ! 😇
