### ISSUE TITLE
An option to skip integrity check for "proot-distro install"

### ISSUE THREAD

**Issue by alvitoraidhy** [termux/proot-distro#107]
To mitigate possible unintentional mistakes, there should be an option to skip integrity check.

**Comment by xeffyr** [comment]
Which mistakes? If you have found that integrity check failed for some of **supported** distributions, you should will a bug report in this repo. If that's about custom distributions, then I don't see any issue with running `sha256sum ./tarball.tgz`. If you really need to disable it, just don't specify sha256 in plug-in. However there no practical reasons to disable integrity checking.

Integrity check is the only way to ensure that archive was download comletely.

**Comment by alvitoraidhy** [comment]
Thank you for the quick reply. I have submitted a new issue https://github.com/termux/proot-distro/issues/108

**Comment by MRDEVILAS24102009** [comment]
Please share the solution

**Comment by Ubsmart89** [comment]
proot-distro install arrot integrity check fails, what's the solution sir
