### ISSUE TITLE
Add Linux Mint

### ISSUE THREAD

**Issue by theblobscp** [termux/proot-distro#110]
Mint is fun, please add it if you feel like it

**Comment by xeffyr** [comment]
Do you know where to get its rootfs archive?

Also what you are expecting from it? It would not be significantly different from Debian/Ubuntu as all of `proot-distro` distributions come as bare minimum command line environments. Also it doesn't have ARM (32/64) support.

**Comment by theblobscp** [comment]
For me personally, it's mostly just the fact that python3 uses 3.9. If i try to install it differently, i usually can't use the alias.

**Comment by ZhymabekRoman** [comment]
> python3 uses 3.9

You can install last Python 3.9 on Ubuntu  using DeadSnakes PPA: 
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update
sudo apt-get install python3.9
```

**Comment by theblobscp** [comment]
Uh... I don't know what deadsnakes is
