### ISSUE TITLE
Error When Download Ubuntu 21.04

### ISSUE THREAD

**Issue by dinaradenis** [termux/proot-distro#111]
Usually I Download 300MB File Just In A Minute, But When I Download Ubuntu 21.04 It Very Slow. I Restart My Phone, Reinstall Termux, But Result Are Same. Estimated Download Time Like 20 Hours. How I Can Download Ubuntu 21.04?

**Comment by xeffyr** [comment]
And what I should do? I do not own GitHub and can't make it faster. Also I won't spin up a VPS specifically for hosting rootfs, neither will waste disk space on my cloud storage.

Use it as is or fix your networking: change ISP, try VPN or if already have - try to disable.
