### ISSUE TITLE
Set up xrdp in Ubuntu

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/proot-distro#112]
Hi, how to set up xrdp in root account? I use Ubuntu 21.04

**Comment by ZhymabekRoman** [comment]
> Hi, how to set up xrdp in root account? I use Ubuntu 21.04

```
root@dlp:~# apt -y install xrdp tigervnc-standalone-server
root@dlp:~# systemctl enable xrdp 
```

**Comment by NoNameMan1231** [comment]
> > Hi, how to set up xrdp in root account? I use Ubuntu 21.04
> 
> ```
> root@dlp:~# apt -y install xrdp tigervnc-standalone-server
> root@dlp:~# systemctl enable xrdp 
> ```

HOW ABOUT XVNC PASSWORD FOR ROOT USER?

**Comment by ZhymabekRoman** [comment]
> HOW ABOUT XVNC PASSWORD FOR ROOT USER?

JUST USE `tightvncserver` !

**Comment by NoNameMan1231** [comment]
> > HOW ABOUT XVNC PASSWORD FOR ROOT USER?
> 
> JUST USE `tightvncserver` !

so install tightvncserver,
then start rdp server

at rdp, switch to xvnc section and type the tightvnc password ,right?
