### ISSUE TITLE
Problem setting up sudo account

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/proot-distro#113]
I have problem setting up account in ubuntu 21.04. Even I edit the /etc/sudoers file. It just giving me these errors:
sudo: /etc/sudo.conf is owned by uid 1000, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

 
![Screenshot_2021_0811_092050](https://user-images.githubusercontent.com/87801676/128955396-80a247e7-d03e-4f6c-9176-59a4dd842a30.jpg)

PLEASE HELP ME!

**Comment by NoNameMan1231** [comment]
Well, this occur in version v1.10.1

**Comment by Yonle** [comment]
> PLEASE HELP ME
# Be Patient
Ok?

**Comment by NoNameMan1231** [comment]
> > PLEASE HELP ME
> 
> # Be Patient
> Ok?

OK👌

**Comment by ZhymabekRoman** [comment]
Try this from root user: ` chown root:root /etc/sudoers /etc/sudoers.d -R`

**Comment by ZhymabekRoman** [comment]
Try this from root user:
```
chown root:root /etc/sudo.conf 
chown root:root /usr/bin/sudo
chmod u+s /usr/bin/sudo
```

**Comment by NoNameMan1231** [comment]
> Try this from root user:
> 
> ```
> chown root:root /etc/sudo.conf 
> chown root:root /usr/bin/sudo
> chmod u+s /usr/bin/sudo
> ```

don't work :(

**Comment by xeffyr** [comment]
General proot issue completely undrelated to `proot-distro`.

**Comment by DocMAX** [comment]
> > Try this from root user:
> > ```
> > chown root:root /etc/sudo.conf 
> > chown root:root /usr/bin/sudo
> > chmod u+s /usr/bin/sudo
> > ```
> 
> don't work :(

works
