### ISSUE TITLE
Login as user non root, vnc the connection closed unexpectedly, and termux crashed. (ubuntu 20.04) 

### ISSUE THREAD

**Issue by vmobilez** [termux/proot-distro#117]
i'am installing DE xfce4 and tigervnc-standalone-server , login as root is normaly, when login as user non root.. termux and vnc crashed.

if i'm install xfce4 with command --no-install-recommends, is normaly.. login as root or non root normaly, but.. i found any bugs.
i can't found trash on thunar manager and desktop.
home and filesystem on desktop can't open.

**Comment by ZhymabekRoman** [comment]
> tigervnc-standalone-server

 Try to use `tightvncserver`

**Comment by vmobilez** [comment]
Problem Solved

After create new user, i copy directory .config from root to new user, Now.. i can login vnc as new user whithout problem.
