### ISSUE TITLE
Can't install Kali

### ISSUE THREAD

**Issue by theblobscp** [termux/proot-distro#118]
I tried to install kali, but received a "network error". However, my signal is perfectly fine, so there's no reason for the download to break. Just in case it is me, ill download debian

**Comment by theblobscp** [comment]
Yep, debian works. Its just kali linux

**Comment by theblobscp** [comment]
Oh you removed it. Well can you remove it from the list

**Comment by layaachmad** [comment]
**Kali and Parrot OS are removed from proot-distro**

12c0c02465682e6906e6c33ac5397c12acc902e7
