### ISSUE TITLE
[Ubuntu-21.04] OpenGL driver problem

### ISSUE THREAD

**Issue by masrur10rahman** [termux/proot-distro#119]
OpenGL driver of Ubuntu 21.04 might have some issues.

I tried to run Godot but it shows some errors like below.
- Desktop :
```
Your video card driver does not support any of the supported OpenGL versions.
Please update your drivers or if you have a very old or integrated GPU upgrade it.
```
- Terminal :
```
Godot Engine v3.2.3.stable.custom_build - https://godotengine.org
ERROR: initialize: Condition "!fbc" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:158.
ERROR: initialize: Condition "!fbc" is true. Returned: ERR_UNCONFIGURED
   At: platform/x11/context_gl_x11.cpp:158.
ERROR: is_viable: Error initializing GLAD
   At: drivers/gles2/rasterizer_gles2.cpp:166.
```
**Worked perfectly on older versions of proot-distro (Ubuntu-20.04)**

I also had OpenGL issues with SFML, GLFW and Raylib.

***Reproducing the issue :***
Ran `godot3` from terminal.

**Comment by ZhymabekRoman** [comment]
Compile from source llvmpipe mesa drivers

**Comment by masrur10rahman** [comment]
> Compile from source llvmpipe mesa drivers

Repository's one won't work?
I used both repository's package and compiled from source in previous proot-distros.
Could compiling from source solve driver issues?

**Comment by ZhymabekRoman** [comment]
> Could compiling from source solve driver issues?

Yes

**Comment by xeffyr** [comment]
Closing since this is not issue of `proot-distro` (reminding that it is only a shell script wrapper for `proot`).
