### ISSUE TITLE
Chromium Browser for Ubuntu 20.04

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#12]
Hey. so I recently installed Chromium Browser via apt. and after Installation I do some tweaking by adding no sandbox through the desktop entry `/usr/share/applications` afterwards it won't start. I tried to run it in terminal but it asks me to install chromium as a snap package

however. snapd obviously won't gonna work because it uses FUSE (i think) and Requires real root access.

Tried to Google. "[chromium ppa for Ubuntu 20.04](http://ubuntuhandbook.org/index.php/2020/06/install-chromium-via-deb-ubuntu-20-04/)". but adding it still uses the focal repositories instead of the PPA. even pinning it. i could use Midori or Firefox but I want to run Chromium.

is there a way to install chromium without snaps in Ubuntu 20.04

**Comment by xeffyr** [comment]
Trying the AMD64 build on ARM(64)? That won't work...
http://ppa.launchpad.net/xalt7x/chromium-deb-vaapi/ubuntu/pool/main/c/chromium-browser/ - amd64 only as well as most of existing PPAs.

**Comment by WMCB-Tech** [comment]
Oh. ok. thanks for the response
