### ISSUE TITLE
[Bug]: Debian update failed

### ISSUE THREAD

**Issue by GitHubNeko** [termux/proot-distro#122]
### Problem description

**When I log in to Debian and update the source, it gives the following error：**

The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 151.101.78.132 443]
Err:5 https://deb.debian.org/debian-security stable/updates Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 151.101.78.132 443]
Err:6 https://deb.debian.org/debian stable-updates Release
  Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 151.101.78.132 443]
Reading package lists... Done
W: https://deb.debian.org/debian/dists/stable/InRelease: No system certificates available. Try installing ca-certificates.
W: https://deb.debian.org/debian-security/dists/stable/updates/InRelease: No system certificates available. Try installing ca-certificates.
W: https://deb.debian.org/debian/dists/stable-updates/InRelease: No system certificates available. Try installing ca-certificates.
W: https://deb.debian.org/debian/dists/stable/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://deb.debian.org/debian stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://deb.debian.org/debian-security/dists/stable/updates/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://deb.debian.org/debian-security stable/updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://deb.debian.org/debian/dists/stable-updates/Release: No system certificates available. Try installing ca-certificates.
E: The repository 'https://deb.debian.org/debian stable-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### What steps will reproduce the bug?

Log in to Debian：proot-distro login debian
update source：apt update

**Comment by xeffyr** [comment]
Seems like this is due to https urls added without ca-certificates installed. I'll switch to http which is default, data is verified with gpg anyway.

**Comment by xeffyr** [comment]
Version 2.0.1 should resolve the issue, thanks.
