### ISSUE TITLE
[Bug]: missing plugin for distribution 'ubuntu-20.04'.

### ISSUE THREAD

**Issue by ShivaShirsath** [termux/proot-distro#124]
### Problem description

Error: missing plugin for distribution 'ubuntu-20.04'.

### What steps will reproduce the bug?

updating the proot-distro

```
pkg update -y && pkg upgrade -y
```

### What is the expected behavior?

How to get log in in ubuntu-20.04

**Comment by xeffyr** [comment]
Intended behavior. **Versioning is no longer supported since 2.0.**
