### ISSUE TITLE
[Bug]: Errors encountered in file manager in Ubuntu-21.04

### ISSUE THREAD

**Issue by duskygloom** [termux/proot-distro#129]
### Problem description

In Ubuntu-21.04, I have encountered two issues when using file manager (both Thunar and Nautilus). I am on android 9.

1. File manager failed to open external sdcard.
![noaccesssdcard](https://user-images.githubusercontent.com/65943118/129734410-97fc0c4e-e680-4fb7-937d-1d58546afa61.png)

2. Some folders cannot be copied.
![Screenshot_2021-08-16_16-52-33](https://user-images.githubusercontent.com/65943118/129734483-58e02c6b-eb71-4a04-ab62-1d5e5e5f9f60.png)
![Notification](https://user-images.githubusercontent.com/65943118/129734519-f1c2c03d-4edc-4b48-a9d9-d272bffbdf9f.png)

3. Also, I use QtDesigner which is now unable to save any file.
![notsaving](https://user-images.githubusercontent.com/65943118/129734744-92658666-e2ea-4408-8a35-fcd05e33ca3a.png)

** Please note that the file manager related issues are not occurring when dealing with the files in terminal with cd and cp.

### What steps will reproduce the bug?

Bugs are reproduced when:

1. Accessing external sdcard in file manager.
2. Trying to copy certain folders.
3. Trying to save in QtDesigner.

**Comment by NoNameMan1231** [comment]
i think use termux-setup-storage?

**Comment by duskygloom** [comment]
> i think use termux-setup-storage?

I did it before installing proot-distro. But one thing was a bit weird that no popup appered after that. But I have checked manually that storage permission exists. And also I can access my storage from terminal but not from file manager.

**Comment by xeffyr** [comment]
1. This isn't issue of `proot-distro`.
2. Ubuntu 21.04 is not supported.

**Comment by xeffyr** [comment]
Some information on topic: https://wiki.termux.com/wiki/Internal_and_external_storage. You can't write files to external sd card or usb drive in Termux.

**Comment by duskygloom** [comment]
> Some information on topic: https://wiki.termux.com/wiki/Internal_and_external_storage. You can't write files to external sd card or usb drive in Termux.

I was not trying to write in external sdcard 😢😢

**Comment by WMCB-Tech** [comment]
> > Some information on topic: https://wiki.termux.com/wiki/Internal_and_external_storage. You can't write files to external sd card or usb drive in Termux.
> 
> I was not trying to write in external sdcard 😢😢
@duskygloom 

The first photo shown that the program is trying to `stat` on external storage which in that case puts certain restrictions

second and third photos are probably some bug which in this case you may report it through https://github.com/termux/proot

**Comment by duskygloom** [comment]
@WMCB-Tech whatever... I'll just have to install ubuntu20 again 😓😓
