### ISSUE TITLE
[Bug]: xfwm4 not working

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/proot-distro#130]
### Problem description

hi folks, im using ubuntu .

i installed xfce4 and start the vnc session . later , i'm found that the xfwm4 was not working!

### What steps will reproduce the bug?

when i start an vnc session.

**Comment by xeffyr** [comment]
Does it worked until certain point and then suddenly was terminated?

Seems to be more like your device issue, some manufacturers configure system to kill background process. Related issues:
* https://github.com/termux/termux-app/issues/2015
* https://github.com/termux/termux-app/issues/2197

In any case, circumvention of background process killing isn't possible without root or at least ADB and is not a subject for `proot-distro` anyway.

If you suspect any crash or other instability related to proot, better to report issue to https://github.com/termux/proot. This repository is only about `proot-distro` (which is only a shell script wrapper for proot) and bundled rootfs.

**Comment by NoNameMan1231** [comment]
> Does it worked until certain point and then suddenly was terminated?

no

**Comment by dionisio32** [comment]
eu estou a ver fumo
