### ISSUE TITLE
[Bug]: Cannot create files due to "disk full"

### ISSUE THREAD

**Issue by Yisus7u7** [termux/proot-distro#131]
### Problem description

![Screenshot_20210817-151118](https://user-images.githubusercontent.com/64093255/129831547-1bd4a9f3-af4f-4a47-8e1e-2e4535c207f5.png)

I installed kde plasma in termux

### What steps will reproduce the bug?

But the kde apps cannot create some files, a message appears saying that the disk is full

### What is the expected behavior?

And that's false, if I have space.

The problem happens in any facility and any phone

**Comment by xeffyr** [comment]
> But the kde apps cannot create some files, a message appears saying that the disk is full

And what I can do? I'm not author or maintainer of KDE or other packages. 

Guys, let's understand that `proot-distro` is just a shell script wrapper that automates downloading rootfs, extracting it and launching the proot. No more. Any error in package comes from proot itself and not the `proot-distro`.

So what issue/bug reports I'm accepting:
* Logical and syntax errors inside `proot-distro` script.
* Broken rootfs.
* Package installation errors, e.g. postinst failure in Ubuntu/Debian. 

Everything else is beyond the control of PRoot Distro.
