### ISSUE TITLE
[Bug]: Arch upgrade issues

### ISSUE THREAD

**Issue by GitHubNeko** [termux/proot-distro#135]
### Problem description

Use Arch to update the software package operation, the following error message appears

_Failed to check for chroot() environment: No such file or directory
  Skipped: Current root is not booted.
(3/4) Reloading device manager configuration...
Failed to check for chroot() environment: No such file or directory
  Skipped: Device manager is not running.
(4/4) Arming ConditionNeedsUpdate..._

### What steps will reproduce the bug?

pacman -Syu --noconfirm

### What is the expected behavior?

Do i ignore it ？

**Comment by WMCB-Tech** [comment]
Ignore that, it isn't critical anyway and `pacman` should continue to successfully install packages

**Comment by xeffyr** [comment]
Disable hook scripts of you won't want to see this. See pacman manual on how to do it.

**Comment by SDRausty** [comment]
Changing --chroot to -c in file /usr/share/libalpm/scripts/systemd-hook suppresses the message.
