### ISSUE TITLE
 Arch linux bug

### ISSUE THREAD

**Issue by testdevloper13225** [termux/proot-distro#14]
1.recently i installed arch linux using proot-distro 
then xfce4 and when i started xsdl 
i got a error 'desktop Folder' not found 
and xfce4 not working properly 
2. when i tried lxde i got new error 
'no session 
for pid 14798'
please fix it

**Comment by xeffyr** [comment]
Sorry, but distribution issues can't be fixed here. You probably messed up with something or package installation was not finished successfully.

**Comment by michalbednarski** [comment]
The issue has been fixed on proot side, Thunar should now be usable after upgrading proot package

**Comment by WMCB-Tech** [comment]
@michalbednarski should this fix this [issue?](https://github.com/SDRausty/TermuxArch/issues/257)

**Comment by michalbednarski** [comment]
Looks like that is same issue, though to be certain one had to test if this is now fixed

**Comment by WMCB-Tech** [comment]
@michalbednarski it's fixed when updating proot:
![Screenshot_2020-10-18-16-26-52-20_30a42d6a209f6598350fa5f61642e1a9.png](https://user-images.githubusercontent.com/65075766/96362281-ca167700-115e-11eb-9318-4857439eba37.png)
