### ISSUE TITLE
[Bug]: pulseaudio

### ISSUE THREAD

**Issue by beki13** [termux/proot-distro#140]
### Problem description

it is not working .
i have tried with ubuntu and debian

### What steps will reproduce the bug?

i have done all steps correctly

**Comment by ZhymabekRoman** [comment]
See this: pulseaudio

**Comment by xeffyr** [comment]
This isn't bug really. You need to use Pulseaudio from Termux as in https://github.com/termux/proot-distro/issues/85#issuecomment-854358933, as only this variant has drivers for sound output compatible with Android.
