### ISSUE TITLE
[Bug]: cannot to APT update

### ISSUE THREAD

**Issue by TUNBudi06** [termux/proot-distro#144]
### Problem description

When update the command say "
~ $ proot-distro login ubuntu
root@localhost:~# apt update
Get:1 http://security.ubuntu.com/ubuntu hirsute-security InRelease [110 kB]
Get:2 http://security.ubuntu.com/ubuntu hirsute-security/main amd64 Packages [215 kB]
Get:3 http://security.ubuntu.com/ubuntu hirsute-security/main Translation-en [56.7 kB]
Get:4 http://security.ubuntu.com/ubuntu hirsute-security/universe amd64 Packages [211 kB]
Get:5 http://security.ubuntu.com/ubuntu hirsute-security/universe Translation-en [41.4 kB]
Get:6 http://security.ubuntu.com/ubuntu hirsute-security/multiverse amd64 Packages [3364 B]
Get:7 http://security.ubuntu.com/ubuntu hirsute-security/multiverse Translation-en [828 B]
Err:8 http://archive.ubuntu.com/ubuntu hirsute InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
Err:9 http://archive.ubuntu.com/ubuntu hirsute-updates InRelease
  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
Fetched 639 kB in 32s (19.8 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/hirsute/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Could not connect to archive.ubuntu.com:80 (91.189.88.152), connection timed out Could not connect to archive.ubuntu.com:80 (91.189.88.142), connection timed out
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/hirsute-updates/InRelease  Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::23). - connect (101: Network is unreachable) Cannot initiate the connection to archive.ubuntu.com:80 (2001:67c:1360:8001::24). - connect (101: Network is unreachable)
W: Some index files failed to download. They have been ignored, or old ones used instead.
root@localhost:~#

"

I don't know what happen.but my signal fine.

### What steps will reproduce the bug?

APT update

### What is the expected behavior?

Ubuntu hirsute

**Comment by xeffyr** [comment]
As PRoot Distro is only a shell script that manages proot, this issue is completely unrelated to it and will be closed.

Try changing name servers in /etc/resolv.conf.
