### ISSUE TITLE
[Bug]: i can't to make new user

### ISSUE THREAD

**Issue by TUNBudi06** [termux/proot-distro#145]
### Problem description

So i have to change user but i can't.because i need to run vscode.deb.and this log of my terminal code

proot-distro login ubuntu
root@localhost:~# useradd -U -m fs
root@localhost:~# passwd fs
New password:
Retype new password:
passwd: password updated successfully
root@localhost:~# exit
logout
~ $ proot-distro login --user fs ubuntu
$ cd /sdcard/download
$ sudo dpkg -i code_1.60.0-1630493336_arm64.deb
[sudo] password for fs:
fs is not in the sudoers file.  This incident will be reported.
$

### What steps will reproduce the bug?

To create specific user

### What is the expected behavior?

Ubuntu

**Comment by Grimler91** [comment]
Looks like your user was added just fine, I don't see an error from user creation here.

> fs is not in the sudoers file. This incident will be reported.

Means exactly what it says, you have not specified that the user should be allowed to use sudo. See the world wide web for how to set that up, for example https://askubuntu.com/questions/7477/how-can-i-add-a-user-as-a-new-sudoer-using-the-command-line

**Comment by TUNBudi06** [comment]
But still cannot to use.when i look into a /etc/group it has sudo:x:27:fs
When i try again its fails.

**Comment by Yonle** [comment]
Modify `/etc/sudoers` file and add this line after `sudo ALL=(ALL) ALL` like:
![Screenshot_2021_0905_220446](https://user-images.githubusercontent.com/63401712/132131627-d871507d-53cb-4573-bb82-339193d8d622.png)

```
[username] ALL=(ALL) ALL
```

**Comment by TUNBudi06** [comment]
Thank so much,is works.
