### ISSUE TITLE
Bind $PREFIX/tmp to Guest /tmp directory

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#15]
Hi. so i was just wondering if you can add a feature that the Termux's tmp directory is mounted to Guest /tmp directory. this is useful if termux runs at cold start. the guest tmp directory is also cleared as well to clean up cache and unwanted sockets. and. i can run Guest's GUI apps inside Termux X11 with Xhost.

***Running Firefox inside Termux X11 using Debian Chroot***
![Screenshot_2020-09-29-10-08-16-70_86e29ab1b9fd3f2a477a649413bc8db4.png](https://user-images.githubusercontent.com/65075766/94505041-ce750180-023c-11eb-89a7-46316ac23818.png)

**Comment by ZhymabekRoman** [comment]
#18

**Comment by ZhymabekRoman** [comment]
Hello. I implemented your wish in the code and made pull request. You can follow the pull request status here : #18

**Comment by ZhymabekRoman** [comment]
To enable the function of mounting the /tmp folder from the host folder to in the proot container, you need to specify the --shared-tmp flag during the launch of proot-distro. For example : proot-distro login ubuntu --shared-tmp

Sorry for my English : )

**Comment by xeffyr** [comment]
Closing as I have merged https://github.com/termux/proot-distro/pull/18.

**Comment by WMCB-Tech** [comment]
Thanks for adding this feature
