### ISSUE TITLE
[Bug]: enhance plug-in script: TARBALL_STRIP_OPT="path"  to suport : tar -C ${TARBALL_STRIP_OPT}

### ISSUE THREAD

**Issue by zxq432** [termux/proot-distro#150]
### Feature description

 enhance plug-in script with :
1. ENV_CMD="/some_path/env"  
2. LOGIN_CMD="/some_path/commad some_args"
3. TARBALL_STRIP_OPT="path"  to suport : tar -C ${TARBALL_STRIP_OPT}, with the following logic:

```
[[ ${TARBALL_STRIP_OPT} == /* ]] && {
    [[ -d ${TARBALL_STRIP_OPT} ]] || mkdir -p ${TARBALL_STRIP_OPT}
    tar_cmd +="-C ${TARBALL_STRIP_OPT}"
}
```
the current proot-distro gentoo using the normal distributions of starge3 gentoo(systemd) does not work for the bug [https://github.com/termux/proot/issues/182](https://github.com/termux/proot/issues/182)

the latest gentoo prefix released comes with a woking sys-devel/patch, to correctly install gentoo prefix is for aarch64 .  the plug-in script will be like:
```
DISTRO_ARCH=aarch64
DISTRO_NAME="Gentoo-prefix /data/gentoo64"
ENV_CMD="/data/gentoo64/usr/bin/env"
LOGIN_CMD="/data/gentoo64/bin/bash -l"
TARBALL_STRIP_OPT="/data"
TARBALL_URL['aarch64']="https://mirror.tuna.tsinghua.edu.cn/gentoo/experimental/prefix/arm/prefix-stage3-arm64-latest.tar.xz"
TARBALL_SHA256['aarch64']="b93cd8da4fab5fa97dc23aeb19b583317f6c5cc55d5f3cb2ffaba4d52987176e"
```

**Comment by xeffyr** [comment]
Are you sure you properly understand the `TARBALL_STRIP_OPT` meaning? Seems not...

**Comment by xeffyr** [comment]
> ENV_CMD="/some_path/env"
LOGIN_CMD="/some_path/commad some_args"

Everything possible on command line. Also plugins are intended to supply options only during installation and moreover they are not configuration files anymore.
