### ISSUE TITLE
Missing plugin for distribution

### ISSUE THREAD

**Issue by manhtetthar** [termux/proot-distro#151]
### Problem description

i have already installed hippo and ubuntu 20.04 using proot. when today i login to my hippo 
it show "Error : missing plugin for distribution 'hippo' and then i checked with 'proot-distro list'
ans my installed os are disappeared. 

### What steps will reproduce the bug?

.

### What is the expected behavior?

missing plugin for distrbution 'hippo'
and disappeared installed distrbution on proot

**Comment by xeffyr** [comment]
Look in directory `$PREFIX/etc/proot-distro`. If it was a custom plugin and has been disabled, you will find it there and will have to rewrite it into PRoot Distro 2.x format ([sample](https://github.com/termux/proot-distro/blob/4cd12325ee23713dc5210bd909a6e729c6fc7399/distro-plugins/distro.sh.sample)).

**Comment by manhtetthar** [comment]
Thank i have solved it 💓💓💓
