### ISSUE TITLE
[Bug]: Arch cannot use pocl

### ISSUE THREAD

**Issue by GitHubNeko** [termux/proot-distro#152]
### Problem description

I want to use Arch to call pocl, but it cannot detect the existence of pocl
![Screenshot_20210919_092638](https://user-images.githubusercontent.com/83487691/133912596-1639f0b3-1b3f-4a94-a739-b0fe282a932e.jpg)

### What steps will reproduce the bug?

pacman -S pocl clinfo
clinfo

### What is the expected behavior?

On the contrary, Debian can use pocl
![Screenshot_20210919_092611](https://user-images.githubusercontent.com/83487691/133912656-472bfde1-efbf-42ff-bee7-16301db14bcd.jpg)

**Comment by xeffyr** [comment]
Just different versions of POCL. Nothing to do with PRoot Distro.

**Comment by cu233** [comment]
I can run `clinfo`.
You can install it with `yay -S clinfo-git`
![Screenshot_20210920-140743_1](https://user-images.githubusercontent.com/54758066/133962702-070c4226-cc95-4276-8cd6-2da32f1a5772.png)

**Comment by GitHubNeko** [comment]
> 我可以跑`clinfo`。
> 你可以安装它`yay -S clinfo-git`
> ![截图_20210920-140743_1](https://user-images.githubusercontent.com/54758066/133962702-070c4226-cc95-4276-8cd6-2da32f1a5772.png)

Doesn't work, yay compiles pocl error 
![Screenshot_20210921_160042_com termux](https://user-images.githubusercontent.com/83487691/134136717-6ffd0b57-6ef3-427c-92b5-91efbb4e5456.jpg)

**Comment by xeffyr** [comment]
@GitHubNeko Make sure that compiler and other necessary things are installed (`pacman -S base-devel`) and try again. If still picks `bcc` from /system/bin, then pass option `--isolated` to `proot-distro login` - this will disable mounting of Android directories.
