### ISSUE TITLE
[Bug]: how to resolve proot vpid 1 terminated

### ISSUE THREAD

**Issue by TUNBudi06** [termux/proot-distro#154]
### Problem description

I don't know why when i installing Ubuntu in x86 proot emulation.is sho error like this

> `~ $ proot-distro install ubuntu
[*] Installing Ubuntu x86 hirsute...
[*] Creating directory '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu'...
[*] Downloading rootfs tarball...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   638  100   638    0     0    595      0  0:00:01  0:00:01 --:--:--   595
100 34.2M  100 34.2M    0     0   190k      0  0:03:04  0:03:04 --:--:--  193k

[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/profile.d/termux-proot.sh'...
[*] Writing resolv.conf file (NS 1.1.1.1/1.0.0.1)...
[*] Writing hosts file...'
[*] Registering Android-specific UIDs and GIDs...
id: cannot find name for group ID 99909997
[*] Running distro-specific configuration steps...
proot info: vpid 1: terminated with signal 4
~ $`

### What steps will reproduce the bug?

Trying to install Ubuntu x86_64 version

### What is the expected behavior?

Ubuntu

**Comment by xeffyr** [comment]
About `proot` issues, please ask in https://github.com/termux/proot, since I'm really IDK why it could crash.

Proot issues are not Proot Distro script issues.
