### ISSUE TITLE
[Bug]:  the PREFIX is unnecessarily set for gentoo distro in /etc/profile.d/termux-proot.sh makes it emerge openrc files incorrectly into  $PREFIX

### ISSUE THREAD

**Issue by zxq432** [termux/proot-distro#155]
### Problem description

with PREFIX set, emerge of openrc install some files into the $PREFIX incorrectly.
workaround: unset PREFIX before running emerge. it seems PREFIX is unnecessarily set.

### What steps will reproduce the bug?

$ proot-distro login gentoo
# emerge -v1 openrc

### What is the expected behavior?

do not install files into $PREFIX, /data/data/com.termux/files/usr

**Comment by xeffyr** [comment]
This is a part of PRoot Distro <--> Termux env compatibility: https://github.com/termux/proot-distro/blob/4cd12325ee23713dc5210bd909a6e729c6fc7399/proot-distro.sh#L370-L388

Feel free to modify `/etc/profile.d/termux-proot.sh` or `/etc/profile` (fallback if no profile.d) as you wish.

That's distribution behavior is completely unexpected.
