### ISSUE TITLE
[Feature]: add TAR_OPTS tar options for distro tarball, and DISTRO_PREFIX for prefixed distro

### ISSUE THREAD

**Issue by zxq432** [termux/proot-distro#157]
### Feature description

add TAR_OPTS to set some tar options for distro tarball, such as:
```
TAR_OPTS=(-v "--xattrs-include='*.*'" --numeric-owner "2>&1" ">" "${INSTALLED_ROOTFS_DIR}/${distro_name}/tar.log")
```
add DISTRO_PREFIX for prefixed distro, such as gentoo prefix. to install sysroot to /data/gentoo64:
```
DISTRO_PREFIX="/data/gentoo64"
```
the attached patch for proot-distro, and g2.sh  for gentoo latest stage 3 openrc, gp.sh for gentoo prefix, all tested to work

[proot-distro_2.6_.patch.txt](https://github.com/termux/proot-distro/files/7214185/proot-distro_2.6_.patch.txt)
[g2.sh.txt](https://github.com/termux/proot-distro/files/7214186/g2.sh.txt)
[gp.sh.txt](https://github.com/termux/proot-distro/files/7214187/gp.sh.txt)

there's no su in gentoo prefix stage 3, so does test for su, if no su, then use bash -l.

**Comment by xeffyr** [comment]
Feature requests must follow the current PRoot Distro design. I don't support anything beyond the **traditional** distributions.
