### ISSUE TITLE
[Bug]: What the hell happened?

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/proot-distro#158]
### Problem description

When I run update command , it gave me this error
``
Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
``
Note: my line works VERY WELL. 

### What steps will reproduce the bug?

EVERY TIME I RUN`sudo apt update`

**Comment by NoNameMan1231** [comment]
Note: this problems also occured at other distro

**Comment by Yonle** [comment]
Maybe check your network connection. I face no problem at both Debian bullseye and sid. Also this is NOT `proot-distro` problem.

**Comment by NoNameMan1231** [comment]
No. MY NETWORK CONNECTION IS GOOD!

**Comment by Yonle** [comment]
Then that's your ISP DNS problem.
Change your DNS or use VPN.

**Comment by NoNameMan1231** [comment]
> Then that's your ISP(Your operator) DNS problem. Change your DNS or use VPN.

Thanks! Now I'm using 1.1.1.1
