### ISSUE TITLE
Can't Login Ubuntu18.04

### ISSUE THREAD

**Issue by Flytreels** [termux/proot-distro#16]
$ proot-distro login ubuntu-18.04
su: System error

 OS: Android 9 aarch64
 Host: HONOR KIW-AL10
 Kernel: 3.10.108-lineageos-g6e87014
 Uptime: 15 hours, 24 min
 Packages: 66 (dpkg), 1 (pkg)
Shell: bash 5.0.17
Terminal: com.termux
 CPU: (8)
Memory: 1649MiB / 2850MiB

**Comment by xeffyr** [comment]
Try a different distribution, maybe it will work. That's however proot imcompatibility with your device.

**Comment by Flytreels** [comment]
But other distributions are normal

**Comment by xeffyr** [comment]
Then use other distributions as `proot-distro` can't fix binaries.
