### ISSUE TITLE
[Bug]: adduser command not working in Ubuntu (hirsute)

### ISSUE THREAD

**Issue by shrihanDev** [termux/proot-distro#160]
### Problem description

Adding users in `ubuntu` using `adduser` doesn't work. See below for details.

Some env details:
- Operating System: Android 11 (custom ROM, rooted)
- Device: j7elte
- `uname -a`: `Linux localhost 3.10.108-g356f7b75c68 #1 SMP PREEMPT Mon May 24 04:03:20 CEST 2021 armv8l Android`
- Termux version: v0.117
- proot version:
```bash
[Proot in figlet style here]... 5.1.0

built-in accelerators: process_vm = yes, seccomp_filter = yes

Visit http://proot.me for help, bug reports, suggestions, patchs, ...
Copyright (C) 2015 STMicroelectronics, licensed under GPL v2 or later.
```

### What steps will reproduce the bug?

So today, I installed `proot-distro` and using it, installed `ubuntu`. Fine.

I logged into Ubuntu and `apt update && apt full-upgrade`-d it. Fine.

I tried to add a non-root user to keep things safe using `adduser`. There's the problem.

When I run `adduser test`, here's what I get:

```bash
root@localhost:~# adduser test
Adding user `test' ...
Adding new group `test' (1000) ...
groupadd: /etc/group.20856: lock file already used
groupadd: cannot lock /etc/group; try again later.
adduser: `/sbin/groupadd -g 1000 test' returned error code 10. Exiting.
```
[The 20856 part differs after every iteration of the same command.]

I checked `ps aux`, but there's no process running with that PID.

I also tried the `useradd` command, which gave me a sorta similar error:
```bash
useradd: /etc/passwd.20995: lock file already used
useradd: cannot lock /etc/passwd; try again later.
```

I thought that maybe setting `PROOT_NO_SECCOMP=1` may make any sort of difference, and it did, but with another error:
```bash
~ $ PROOT_NO_SECCOMP=1 proot-distro login ubuntu
root@localhost:~# adduser test
Adding user `test' ...
Adding new group `test' (1000) ...
groupadd: cannot get lock /etc/group.lock: Operation not permitted
groupadd: cannot lock /etc/group; try again later. 
adduser: `/sbin/groupadd -g 1000 test' returned error code 10. Exiting.

root@localhost:~# useradd test
useradd: cannot get lock /etc/passwd.lock: Operation not permitted
useradd: cannot lock /etc/passwd; try again later.
```

**Comment by shrihanDev** [comment]
Interestingly, if I try to use `useradd` in `archlinux`, it works perfectly.

**Comment by xeffyr** [comment]
Not a PRoot Distro issue.

Already reported in https://github.com/termux/proot/issues/191.
