### ISSUE TITLE
[Bug]: Nodejs output "Illegal Instruction" in Alpine, but not in Debian

### ISSUE THREAD

**Issue by delay-lag** [termux/proot-distro#161]
### Problem description

Nodejs, commands like `node`, `npm`, `npx` output `I
llegal Instruction` in all distros except Debian-based distros.

![Screenshot 1](https://user-images.githubusercontent.com/65605681/134787345-9e0a3abe-157b-4457-a94e-01c45ab1db2e.png)

![Screenshot 2](https://user-images.githubusercontent.com/65605681/134787365-591622cb-1028-42e9-b8e3-11c3509fd837.png)

### What steps will reproduce the bug?

Run `node, npx or npm` in distros that are not Debian-based.

### What is the expected behavior?

Run `node` and show the following 
```
Welcome to Node.js (nodejs version).
Type ".help" for more information.
>
```

**Comment by xeffyr** [comment]
Possibly related to https://github.com/termux/proot-distro/issues/91. If so, I will remove support of 32bit variants of Alpine Linux. Nothing can be done on PRoot Distro side (its finally only a rootfs manager script).
