### ISSUE TITLE
[Bug]: proot info: vpid 1: terminated with signal 4 (x86_64)

### ISSUE THREAD

**Issue by morealternative** [termux/proot-distro#162]
### Problem description

Unable to login to the distro 

### What steps will reproduce the bug?

.

### What is the expected behavior?

Just login into it

**Comment by SDRausty** [comment]
duplicates: https://github.com/termux/proot/issues?q=vpid+1
 
At https://github.com/termux/proot/issues you can gleam more diagnostic ingormation.

**Comment by xeffyr** [comment]
Bug report from already mentions that **I'm not accepting runtime bugs happening in proot utility**. PRoot Distro is only rootfs manager script and nothing more. All the task of executing programs within the given environment (Ubuntu, Debian, etc), is done by `proot`.

Correct repository is there: https://github.com/termux/proot
