### ISSUE TITLE
Add Nethunter: 

### ISSUE THREAD

**Issue by xx-Anonymous** [termux/proot-distro#163]
### Feature description

Hi.

I know `Kali Nethunter Rootless (Minimal Install)` was available in previous versions of `proot-distro`, but is there any plans of adding `nethunter` back into the latest versions of `proot-distro`.It was very convenient for me to install all my hacking tools in a seperate file system.Or is the removal of `nethunter` part of the "No hacking tolerance" in Termux?

Also how can I get older versions of `proot-distro`.

Thank You. 
In advance.

**Comment by xeffyr** [comment]
Nethunter has been removed intentionally. Decision is final and is not subject for revising. Details: https://wiki.termux.com/wiki/Hacking

Adding custom distribution plug-in shouldn't be issue for you. But if shell scripting is a big trouble, my suggestion - begin from *basics* and not from hacking.

> Also how can I get older versions of proot-distro.

You can get it through git checkout, isn't it? However note that I have removed rootfs of nethunter/parrot-os.
