### ISSUE TITLE
[Bug]: proot-distro install alpine not success

### ISSUE THREAD

**Issue by mazhe1988** [termux/proot-distro#164]
### Problem description

~ $ proot-distro install alpine
[*] Installing Alpine Linux (edge)...
[*] Using cached rootfs tarball...
[*] Checking integrity, please wait...
[*] Extracting rootfs, please wait...
proot error: ptrace(TRACEME): Operation not permitted
proot error: execve("/data/data/com.termux/files/usr/bin/tar"): Operation not permitted
proot info: It seems your kernel contains this bug: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1202161
To workaround it, set the env. variable PROOT_NO_SECCOMP to 1.
fatal error: see `proot --help`.
[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile'...
find: ‘usr/lib/’: No such file or directory

### What steps will reproduce the bug?

~ $ proot-distro install alpine

**Comment by xeffyr** [comment]
This is not issue of PRoot Distro.
