### ISSUE TITLE
[Bug]: LANG over-rides locale. Easy fix.

### ISSUE THREAD

**Issue by ghost** [termux/proot-distro#167]
### Problem description

File /etc/profile.d/termux-proot.sh has this line of code:

    export LANG=C.UTF-8

But texmux-proot.sh is sourced after locale.sh. As a result, the LANG setting provided by locale.sh is re-set to C.UTF-8.

Simple solution: In file termux-proot-sh, make this change:

    [ -z "$LANG" ] && export LANG=C.UTF-8

### What steps will reproduce the bug?

Any login using proot-distro login archlinux. Then

    echo $LANG

produces LANG=C.UTF-8, which is incorrect if LANG was set using /etc/locale.gen and locale-gen.

### What is the expected behavior?

Should produce correct user locale, such as en_GB.UTF-8.

**Comment by xeffyr** [comment]
Thanks, this will be fixed in 2.6.5.
