### ISSUE TITLE
A solution for Xvnc segmentation fault

### ISSUE THREAD

**Issue by xeffyr** [termux/proot-distro#17]
For now we can use
```
vncserver -localhost -SecurityTypes None
```
to avoid crash of TigerVNC server.

However https://github.com/TigerVNC/tigervnc/issues/800 proposes a solution which seems better: to preload a `libgcc_s.so.1` library. Script `proot-distro` can be modified to export a `LD_PRELOAD` variable with appropriate architecture-specific value like `/lib/aarch64-linux-gnu/libgcc_s.so.1`.

- [x] TODO: verify that solution actually works.

**Comment by WMCB-Tech** [comment]
Actually. the LD_PRELOAD Method is better because it doesn't crash when closing VNC viewer.

**Comment by xeffyr** [comment]
Implemented in https://github.com/termux/proot-distro/commit/ba1419f2d3f773904ba6feabf994be53e864dd26 but will take effect only for new distribution installations.

If you want to use this without reinstalling, run this (assuming you did `proot-distro login ...`):
```
echo "export LD_PRELOAD=$(find /usr/lib/ -name libgcc_s.so.1)" >> /etc/profile
```
and restart your shell session.

**Comment by WMCB-Tech** [comment]
Thanks. you're a real lifesaver regarding with these bugs
