### ISSUE TITLE
[Distribution]: Ubuntu 21.10

### ISSUE THREAD

**Issue by NoNameMan1231** [termux/proot-distro#171]
### Description

Ubuntu 21.10 released!

### Home page URL

https://ubuntu.com/

### Root file system archive URL

https://cloud-images.ubuntu.com/impish/current/

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [x] Yes, distribution supports AArch64 and ARM.

**Comment by NoNameMan1231** [comment]
> and someday ubuntu will be snap-only distribution 

:(

**Comment by NoNameMan1231** [comment]
>ubuntu is becomming worser

yeah...i agreed

**Comment by xeffyr** [comment]
Going to be done in v2.9.0.
