### ISSUE TITLE
[Bug]: Cannot update in OpenSUSE

### ISSUE THREAD

**Issue by Adriankhl** [termux/proot-distro#173]
### Problem description

I use OpenSUSE in my daily laptop, so I think it would be good to also have it in termux. However, the basic - updating packages, doesn't work.

### What steps will reproduce the bug?

Open termux, login OpenSUSE
```
proot-distro login opensuse
```

Call `dup` to update will delete all the packages:
```
zypper dup
```

Can't install anything, for example this doesn't work
```
zypper in git
```

**Comment by xeffyr** [comment]
Going to be fixed in 2.9.0.
