### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot-distro#180]
### Feature description

Please consider to add links to source code of Debian packages to The /etc/apt/sources.list

Unfortunately, current tarbal with Debian minimal do not contain those repositoryes links. As a result, I can not use apt build-dep packagename

I need to modify some C apps so I would like to have also The opportunity to build The packages from sources. May be, that you could add updated /etc/apt/sources.list here so I can paste The textual content to this file if it would be too complex to add those repository links directly in to Debian Chroot.
Thank you for yours help.

**Comment by xeffyr** [comment]
All customization such as adding or enabling `deb-src` links should be done *manually*.

**Comment by JanuszChmiel** [comment]
OK, I will try to find those links by reading article on The Internet.
