### ISSUE TITLE
[Bug]: Apache2 Web Server

### ISSUE THREAD

**Issue by Anonymouse2077** [termux/proot-distro#185]
### Problem description

When I try to run apache2 in proot-distro it says

root@localhost:~# service apache2 start
 * Starting Apache httpd web server apache2                           /usr/sbin/apache2ctl: 99: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.
(13)Permission denied: AH00072: make_sock: could not bind to address [::]:80
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
Action 'start' failed.
The Apache error log may have more information.
 *

Im using Ubuntu in PRoot-Distro

### What steps will reproduce the bug?

I dont know but, the whole error message is in the description

### What is the expected behavior?

The expected behavior after running

service apache2 start 

Is I can access my own localhost server for web developmemt

**Comment by ZhymabekRoman** [comment]
In Android, some well-known ports are blocked for use for security purposes. To get around this, you can redirect to another port. To do this, run proot-distro with the parameter ```-f-ix-low-ports```

**Comment by ShivaShirsath** [comment]
Try
```bash
sudo apt install lamp-server^
```

**Comment by ShivaShirsath** [comment]
for web development
Install VS code
```bash 
sudo apt install code 

code --no-sandbox # for opening
```
& install live server extension in vs code
