### ISSUE TITLE
[Bug]: Automatically Termux crashes when we use tigervnc server

### ISSUE THREAD

**Issue by ShivaShirsath** [termux/proot-distro#187]
### Problem description

**the connection closed unexpectedly** 
this error thrown by vnc viewer

automatically get crashes app when we use tigervnc server

### What steps will reproduce the bug?

`tigervncserver` this cammand

### What is the expected behavior?

vnc server start

**Comment by ZhymabekRoman** [comment]
Try use tightvncserver

**Comment by xeffyr** [comment]
Try another VNC server implementation, e.g. already suggested `tightvncserver`.

Application crashes are not related to PRoot Distro in any way.

**Comment by ShivaShirsath** [comment]
> Try another VNC server implementation, e.g. already suggested `tightvncserver`.
> 
> Application crashes are not related to PRoot Distro in any way.



> Try use tightvncserver

Not working this also

**Comment by ShivaShirsath** [comment]
On previous update it worked very well
But in new update it can't working

Your **release v2.2.0** is working,
But **release v2.3.1** is not working

**Comment by ShivaShirsath** [comment]
Problem solved when vnc server launched then instantly go to `settings` in `right click` & select `application` option
