### ISSUE TITLE
[ASK]:how to use see storage file?

### ISSUE THREAD

**Issue by mastersenpai05** [termux/proot-distro#188]
### Feature description

I don't know how to see storage file, is there an option to see storage?

**Comment by ZhymabekRoman** [comment]
storage is a folder, not a file, and you can view the folder in the usual way:
```bash
.../git/translate $ proot-distro login ubuntu
root@localhost:~# cd /storage/
root@localhost:/storage# ls
89E9-1315  emulated  enc_emulated  self
root@localhost:/storage#
```

**Comment by mastersenpai05** [comment]
> storage is a folder, not a file, and you can view the folder in the usual way:
> 
> ```shell
> .../git/translate $ proot-distro login ubuntu
> root@localhost:~# cd /storage/
> root@localhost:/storage# ls
> 89E9-1315  emulated  enc_emulated  self
> root@localhost:/storage#
> ```

**Comment by mastersenpai05** [comment]
Thanks sir ❤️

**Comment by ShivaShirsath** [comment]
```bash
cd ~/storage/shared/
```
Or 
```bash
proot-distro login ubuntu
cd /storage/emulated/0/
```
