### ISSUE TITLE
[Bug]: can't update

### ISSUE THREAD

**Issue by spz2020** [termux/proot-distro#189]
### Problem description

root@localhost:~# apt update
Ign:1 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease
Ign:2 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease
Ign:3 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease
Err:4 http://ports.ubuntu.com/ubuntu-ports hirsute Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute_Release - open (13: Permission denied) [IP: 240.0.0.245 80]
Err:5 http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute-updates_Release - open (13: Permission denied) [IP: 240.0.0.245 80]
Err:6 http://ports.ubuntu.com/ubuntu-ports hirsute-security Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute-security_Release - open (13: Permission denied) [IP: 240.0.0.245 80]
Reading package lists... Error!
W: Download is performed unsandboxed as root as file '/var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Could not create temporary file for /var/cache/apt/srcpkgcache.bin - mkstemp (13: Permission denied)
E: The package lists or status file could not be parsed or opened.
root@localhost:~#
![Screenshot_20211121-141828](https://user-images.githubusercontent.com/74664513/142751968-fcfebb0f-1713-412d-9060-657248b64c1b.png)

### What steps will reproduce the bug?

proot-distro install ubuntu
proot-distro login ubuntu
apt update

### What is the expected behavior?

can update

**Comment by spz2020** [comment]
termux-info
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# game-repo (sources.list.d/game.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://mirrors.ustc.edu.cn/termux/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.11-5 arm [upgradable from: 2.3.6]
ca-certificates/stable 1:2021-10-26-0 all [upgradable from: 20210525]
command-not-found/stable 1.67 arm [upgradable from: 1.62]
coreutils/stable 9.0 arm [upgradable from: 8.32-7]
curl/stable 7.80.0 arm [upgradable from: 7.77.0-3]
dash/stable 0.5.11.5 arm [upgradable from: 0.5.11.3]
debianutils/stable 5.5 arm [upgradable from: 4.11.2]
dialog/stable 1.3-20210621-0 arm [upgradable from: 1.3-20210530-0]
diffutils/stable 3.8 arm [upgradable from: 3.7-3]
ed/stable 1.17-4 arm [upgradable from: 1.17]
gawk/stable 5.1.1 arm [upgradable from: 5.1.0-1]
gpgv/stable 2.3.3 arm [upgradable from: 2.3.1-1]
grep/stable 3.7-1 arm [upgradable from: 3.6]
gzip/stable 1.11-3 arm [upgradable from: 1.10-4]
inetutils/stable 1.9.4-12 arm [upgradable from: 1.9.4-11]
less/stable 590 arm [upgradable from: 563]
libandroid-support/stable 28-2 arm [upgradable from: 28]
libc++/stable 23b-3 arm [upgradable from: 21d-1]
libcurl/stable 7.80.0 arm [upgradable from: 7.77.0-3]
libgnutls/stable 3.6.16 arm [upgradable from: 3.6.15-3]
libgpg-error/stable 1.43 arm [upgradable from: 1.42]
libidn2/stable 2.3.2 arm [upgradable from: 2.3.0-2]
libnettle/stable 3.7.3 arm [upgradable from: 3.7.2]
libnghttp2/stable 1.46.0 arm [upgradable from: 1.43.0]
libssh2/stable 1.10.0 arm [upgradable from: 1.9.0-2]
libtirpc/stable 1.3.2 arm [upgradable from: 1.3.1]
lsof/stable 4.94.0-1 arm [upgradable from: 4.94.0]
nano/stable 5.9 arm [upgradable from: 5.7]
openssl/stable 1.1.1l arm [upgradable from: 1.1.1k-2]
pcre/stable 8.45 arm [upgradable from: 8.44-1]
termux-keyring/stable 2.3 all [upgradable from: 1.9]
termux-tools/stable 0.149 all [upgradable from: 0.130]
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-g07dc527 #2 SMP PREEMPT Wed Oct 24 10:21:06 CST 2018 armv7l Android
Device manufacturer:
HUAWEI
Device model:
DLI-AL10

**Comment by spz2020** [comment]
@xeffyr

**Comment by ZhymabekRoman** [comment]
@spz2020, judging by the screenshot you are using a VPN connection, try to turn it off.

**Comment by spz2020** [comment]
not 
root@localhost:~# apt update                      Ign:1 http://ports.ubuntu.com/ubuntu-ports hirsute InRelease                                        Ign:2 http://ports.ubuntu.com/ubuntu-ports hirsute-updates InRelease
Ign:3 http://ports.ubuntu.com/ubuntu-ports hirsute-security InRelease
Err:4 http://ports.ubuntu.com/ubuntu-ports hirsute Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute_Release - open (13: Permission denied) [IP: 91.189.88.152 80]                                              Err:5 http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute-updates_Release - open (13: Permission denied) [IP: 91.189.88.142 80]
Err:6 http://ports.ubuntu.com/ubuntu-ports hirsute-security Release
  Could not open file /var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute-security_Release - open (13: Permission denied) [IP: 91.189.88.142 80]
Reading package lists... Error!
W: Download is performed unsandboxed as root as file '/var/lib/apt/lists/partial/ports.ubuntu.com_ubuntu-ports_dists_hirsute_InRelease' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ports.ubuntu.com/ubuntu-ports hirsute-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Could not create temporary file for /var/cache/apt/srcpkgcache.bin - mkstemp (13: Permission denied)
E: The package lists or status file could not be parsed or opened.
root@localhost:~#
![Screenshot_20211121-170602](https://user-images.githubusercontent.com/74664513/142756153-4dead262-c076-4287-a24e-be2a2b8958ef.png)

**Comment by ZhymabekRoman** [comment]
Try the steps described here: https://askubuntu.com/a/1146593/1305307

If not, try the steps described here: https://askubuntu.com/a/454899/1305307

**Comment by xeffyr** [comment]
You have error `open (13: Permission denied)`. This is clearly not issue of PRoot Distro but rather of `proot` and should be reported to https://github.com/termux/proot/issues.

**Comment by ShivaShirsath** [comment]
```bash
mkdir /tmp
```
Use this command.
