### ISSUE TITLE
Adding System V IPC support via LD_PRELOAD

### ISSUE THREAD

**Issue by ZhymabekRoman** [termux/proot-distro#19]
Hello. I'm thinking about implementing System V IPC in proot. There are of course two options, one aesthetic and the other, as the Russians say, is just a "crutch" (костыль). 
1) implement at the proot level
2) via LD_PRELOAD using the Peyla Library

What do you think about this ?

**Comment by xeffyr** [comment]
> via LD_PRELOAD using the Peyla Library

Post a link to that IPC implementation library by Pelya. If you are about https://github.com/pelya/android-shmem - then know that it is not System V IPC lib.

**Comment by michalbednarski** [comment]
[System V IPC](https://man7.org/linux/man-pages/man7/sysvipc.7.html) has three mechanisms (`msg*`, `sem*` and `shm*`) and I think this is about `shm` (I've never heard requests for other two).

Main reason that System V IPC wasn't added to proot is that `libandroid-shmem` worked well enough

Also I haven't thought of clean'ish way of handling it in proot

(proot has already bunch of compatibility workarounds, just unlike `LD_PRELOAD` they are hidden)

**Comment by WMCB-Tech** [comment]
However will Fakeroot without TCP IPC work in debian-based distributions? when compiling stuff requires fakeroot with ipc? it seems there's an Package fakeroot-tcp in arch linux but in Ubuntu. only fakeroot package is available

**Comment by xeffyr** [comment]
> I think this is about shm (I've never heard requests for other two).

Fakeroot is a typical example of program using the *other two*.
``` .c
  do {
    if(!msg_key) {
      msgflag |= IPC_EXCL;
      srandom(time(NULL)+getpid()*33151);
      while(!msg_key && (msg_key!=-1))  /* values 0 and -1 are treated
                                           specially by libfake */
        msg_key=random();
    }

    if(debug)
      fprintf(stderr,"using %li as msg key\n",(long)msg_key);

    msg_get=msgget(msg_key,msgflag);
    if (msg_get != -1)
      msg_snd=msgget(msg_key+1,msgflag);
    if (msg_snd != -1)
      sem_id=semget(msg_key+2,1,msgflag);

    if((msg_get==-1)||(msg_snd==-1)||(sem_id==-1)){
      if (errno == EEXIST) {
        if(debug)
          fprintf(stderr,"using %li as msg key caused a collision, cleaning up and retrying\n",(long)msg_key);
        cleanup(-1);
        msg_key = 0;
        msg_get = msg_snd = sem_id = -1;
        continue;
      }
      perror("fakeroot, while creating message channels");
      fprintf(stderr, "This may be due to a lack of SYSV IPC support.\n");
      cleanup(-1);
      exit(1);
    }
  } while(msg_key == 0);
```

**Comment by michalbednarski** [comment]
Okay, I've experimentally implemented `msg*` and `sem*` into proot, currently on [sysvipc branch](https://github.com/termux/proot/tree/sysvipc), in version from that branch there are no additional flags needed, however once it reaches release I think there will be switch.

IPCs are managed within proot, launching two proot instances will lead to separate IPC namespaces.

`shm` is not yet implemented, so android-shmem at this point is still needed for shared memory

Anyway, in not so exhaustive tests it seems that `fakeroot`/`makepkg` work

**Comment by WMCB-Tech** [comment]
@michalbednarski so this means fakeroot that Requires SYSV IPC will emulate it? even without using fakeroot-tcp?

**Comment by michalbednarski** [comment]
Yes, for now you can use fakeroot (without fakeroot-tcp) by building proot from source from sysvipc branch

Also, if someone has some examples of real programs that either would need shm (I guess there are many but I'll need to pick something for testing) or have problems with current msg/sem then please let me know.

**Comment by ZhymabekRoman** [comment]
For example VNC Viewer () supports the MIT-SHM extension, which works via shm. Wine and glxgears can use MIT-SHM. I can't tell you any other examples. 
![Uploading Screenshot_20201031-161033_VNC Viewer.jpg…]()

**Comment by WMCB-Tech** [comment]
@michalbednarski it seems there's a make error:
![Screenshot_2020-10-31-21-12-42-54.png](https://user-images.githubusercontent.com/65075766/97780158-e209e400-1bbd-11eb-9bfa-54e680512321.png)

**Comment by michalbednarski** [comment]
Sorry, forgot a file, please `git pull` and try again

**Comment by WMCB-Tech** [comment]
@michalbednarski according to my tests. both fakeroot and fakeroot-tcp works:

Using User-compiled proot with virtual ipc:
![Screenshot_2020-11-01-13-12-26-95.jpg](https://user-images.githubusercontent.com/65075766/97795693-1cb65f80-1c44-11eb-83a6-249288823b74.jpg)

Using Termux-provided/pre-compiled proot:
![Screenshot_2020-11-01-13-14-55-55.jpg](https://user-images.githubusercontent.com/65075766/97795704-41aad280-1c44-11eb-968d-a61d40eb63a1.jpg)

**Comment by michalbednarski** [comment]
Minimal shm support is now also implemented on `sysvipc` branch, although not really tested so far

**Comment by michalbednarski** [comment]
Anyway implementation is now available in proot (package now available in Termux apt) behind `--sysvipc` flag.

I've done minimal tests with fakeroot and postgresql, although I'm not sure how much works.

**Comment by WMCB-Tech** [comment]
I assume proot-distro should be updated as well to handle packages inside the proot'ed Linux Distros like Fakeroot in Arch

**Comment by WMCB-Tech** [comment]
@michalbednarski it seems sysvipc emulation won't work 
Tested on Android x86 running fakeroot on debian chroot but it doesn't work

Saying function not implemented

**Comment by xeffyr** [comment]
`--sysvipc` is enabled by default in the latest git version. Use `--no-sysvipc` to disable it cause issues.
