### ISSUE TITLE
[Feature]: Enable built in Desktop Environment

### ISSUE THREAD

**Issue by ShivaShirsath** [termux/proot-distro#190]
### Feature description

`xfce4` is very lite weight Desktop Environment only **200 mb size**

with `xfce4-goodies` having all necessary plugins only having **10 mb size**

with `firefox` browser having **70 mb size**

for automatic or dialog based VNC server **command** [click here](https://github.com/ShivaShirsath/Ubuntu-On-Android/blob/main/README.md#vnc)

200 + 10 + 70 = 280 ≈ 300 mb maximum size required.

**Comment by ZhymabekRoman** [comment]
From README.md file:
```
All systems come in a bare-minumum variant, typically consisting of package manager, shell, coreutils, util-linux and few more. Extended functionality like shell completion or package install suggestions should be configured manually.
```

IMHO do not need to burden proot-distro's with third-party packages, I personally from third-party packages directly install Openbox and xterm, xfce4 not correctly works with VNC/Xorg clients, now I do not remember, If I'm not mistake the problem was the lack of support for some kind of extension by Xorg and VNC client

**Comment by GitHubNeko** [comment]
> 

I think the built-in desktop environment is not necessary for most people, you just need to install it yourself😄

**Comment by xeffyr** [comment]
Won'tfix. PRoot Distro will not provide pre-configured desktop installations. It is intended to provide only base and rest should be done by user as stated in README.

> All systems come in a bare-minumum variant, typically consisting of package manager, shell, coreutils, util-linux and few more. Extended functionality like shell completion or package install suggestions should be configured manually.
