### ISSUE TITLE
[Bug]: Cannot authenticate to github using gh

### ISSUE THREAD

**Issue by noobiescoder** [termux/proot-distro#194]
### Problem description

Error: error validating token: Get "https://api.github.com/": read tcp 10.128.111.14:55006->20.205.243.168:443: read: connection reset by peer

### What steps will reproduce the bug?

gh auth login -> GitHub.com -> ssh -> ssh-key -> Paste an authentication token

### What is the expected behavior?

It should be logged in

**Comment by ShivaShirsath** [comment]
Create a full permission authentication token 

don't use ssh

if you want to push something
    git push
    User name : YourUserNameOfGithub
    Password : YourAuthenticationToken

**Comment by SDRausty** [comment]
>User name : YourUserNameOfGithub
‎ Password : YourAuthenticationToken

*User name : YourAuthenticationToken
‎ Password : YourAuthenticationToken

**Comment by ZhymabekRoman** [comment]
> User name : YourAuthenticationToken

@SDRausty, Are you sure that need to enter a token in the username field?

**Comment by wmcbtech30** [comment]
Closing since it's a problem with user action and not a `proot-distro` issue
