### ISSUE TITLE
[Bug]: cp: cannot open '****' for reading: Too many levels of symbolic links

### ISSUE THREAD

**Issue by JavisWiki** [termux/proot-distro#195]
### Problem description

In termux,installed ubuntu(impish) with proot-distro,when I compile lede_openwrt firmware,logs oouput this error:

cp: cannot open '/home/javis/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/initial/./bin/.l2s.mipsel-openwrt-linux-musl-objcopy0001' for reading: Too many levels of symbolic links
cp: cannot open '/home/javis/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/initial/./bin/.l2s.mipsel-openwrt-linux-musl-ar0001' for reading: Too many levels of symbolic links
cp: cannot open '/home/javis/lede/staging_dir/toolchain-mipsel_24kc_gcc-8.4.0_musl/initial/./bin/.l2s.mipsel-openwrt-linux-musl-nm0001' for reading: Too many levels of symbolic links

### What steps will reproduce the bug?

Compile lede firmware.

### What is the expected behavior?

Too many levels of symbolic links,need to fix this.

Maybe we can install system in an img file,like this:  emulate one virtual disk image file,make ext4 file system in image, emulate a folder related to this virtual disk image, then we can make links.
I've tried use guestfs-tools to mount image file,but it doesn't work,lack of /dev/fuse permission.
Expect fix it,thanks.

**Comment by wmcbtech30** [comment]
Likely proot bug and must be reported in [termux/proot](https://github.com/termux/proot)

**Comment by JavisWiki** [comment]
OK, tanks.
