### ISSUE TITLE
Can I avoid this in any way

### ISSUE THREAD

**Issue by Aridlvory** [termux/proot-distro#197]
### Problem description

I installed VLC on Ubuntu and I can't run it... How can I execute command without giving root priviledges
![Screenshot_2022-02-13_21-09-00](https://user-images.githubusercontent.com/78092537/153760880-d91bfd55-784a-4b21-8326-184e46035fbc.png)

### What steps will reproduce the bug?

proot-distro login ubuntu
apt install vlc
vlc

I am using this in my termux
https://github.com/Yisus7u7/termux-desktop-xfce

### What is the expected behavior?

Run vlc smoothly

**Comment by Grimler91** [comment]
Create another, non-root, user. See for example https://askubuntu.com/questions/592507/how-do-i-create-a-new-user-account
