### ISSUE TITLE
Sudo su failed

### ISSUE THREAD

**Issue by BJS611** [termux/proot-distro#2]
![Screenshot_2020-07-30-11-06-31-83_84d3000e3f4017145260f7618db1d683.png](https://user-images.githubusercontent.com/65802479/88879576-cf95ac80-d254-11ea-9d7a-e9e7da1de0cb.png)

**Comment by BJS611** [comment]
Please, I usually use Andronix to enter sudo su but why not this time ???

**Comment by xeffyr** [comment]
proot-distro adds Termux bin directory to PATH by default and it seems you don't have installed `sudo` in Ubuntu but have such in Termux.
```
apt update
apt install sudo
hash -r
```

And suggestion: do not use `sudo su` - that's a wrong way of gaining root or another user's shell. Use `sudo -s` instead.
