### ISSUE TITLE
Arch Linux base package depends upon systemd

### ISSUE THREAD

**Issue by Lokawn** [termux/proot-distro#20]
Archlinux installation using proot-distro stops abruptly.
Getting this error: 
```
warning: pacman is designated as a HoldPkg.
:: HoldPkg was found in target list. Do you want to continue? [y/N]
```
Please remove 'systemd' and 'dbus' from unnecessary packages in 'archlinux.sh', 'base' package depends upon 'systemd' and which inturn depends upon 'dbus', so they can't be removed.
[base package](https://archlinuxarm.org/packages/any/base)
[systemd package](https://archlinuxarm.org/packages/aarch64/systemd)
Or for removing bloat, you can try something like [this](https://wiki.archlinux.org/index.php/Pacman/Tips_and_tricks#Removing_everything_but_essential_packages).

**Comment by xeffyr** [comment]
At the time when `archlinux.sh` was created, systemd and dbus were not essential packages.

Ok, will review packages removal list.

**Comment by xeffyr** [comment]
Fixed in https://github.com/termux/proot-distro/commit/ea32968ca250791505812ff6873942e2c1162145.
