### ISSUE TITLE
[Bug]: linker Warning spams console when programm is running inside proot

### ISSUE THREAD

**Issue by anamyk** [termux/proot-distro#201]
### Problem description

The issue of the following warning under Android 12 has been already acknowledged in proots README.
However, there it is talk about this warning only appearing during proot install.

```
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
```

I use [git-annex](https://git-annex.branchable.com/), which runs inside proot.
When I execute a git-annex command in Termux, I get up to 80+ of these warnings, and it just spams my console. See Screenshot.
![Screenshot_20220303-175553_Termux](https://user-images.githubusercontent.com/49527234/156613173-860ae968-4494-4daa-8f81-91f8a06f78a7.jpg)

I there any possibility of hiding this Warning or to resolute the bug/issue, that is causing it?

There is already a [raised issue over on the git-annex forum](https://git-annex.branchable.com/forum/Warning__58___linker_on_each_command_Android_8.20210429/).

### What steps will reproduce the bug?
Install termux on Android 12.
Install git-annex.
Setup a repo with gitannex.
Run a git-annex command, e.g. git annex sync origin.

### What is the expected behavior?

The Warning
```
WARNING: linker: Warning: failed to find generated linker configuration from "/linkerconfig/ld.config.txt"
```
is not shown or only shown once, not spamming the console.

Edit: edited to add screenshot

**Comment by wmcbtech30** [comment]
You could try running `proot-distro` in isolated mode (`--isolated`)

**Comment by anamyk** [comment]
Thank you for the tip. I dont see how I could do that while using git annex, because I never actually use the command `proot-distro` while using the program.

There has also been some invesigation over on the git-annex forum.

In the meantime (and since termux-proot-distro-devs say the warning is harmless), I managed to filter out only the aforementioned "WARNING: linker:"... from the cli output:
`$ git annex <command> 2> >(grep -v "WARNING: linker:" >&2)`
or as an alias in shellrc
`alias ga = 'git annex $1 2> >(grep -n "WARNING: linker:" >&2)'`
