### ISSUE TITLE
[Distribution]: Ubuntu 20.04

### ISSUE THREAD

**Issue by singam-sanjay** [termux/proot-distro#202]
### Description

How can I install older versions of ubuntu, like Ubuntu 20.04? This is due to missing packages in 21.10 and LTS.

### Home page URL

https://releases.ubuntu.com/20.04/

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [X] Yes, distribution supports AArch64 and ARM.

**Comment by wmcbtech30** [comment]
Create one with
https://github.com/termux/proot-distro#adding-distribution

```sh
# Do not modify this file as your changes will be overwritten on next update.
# If you want customize installation, please make a copy.
DISTRO_NAME="Ubuntu (20.04)"

TARBALL_URL['aarch64']="https://github.com/termux/proot-distro/releases/download/v2.2.0/ubuntu-aarch64-pd-v2.2.0.tar.xz"
TARBALL_SHA256['aarch64']="486de37668963c1b6a0d131e33b91486be8eb1919b0813ad03726885753feba6"
TARBALL_URL['arm']="https://github.com/termux/proot-distro/releases/download/v2.2.0/ubuntu-arm-pd-v2.2.0.tar.xz"
TARBALL_SHA256['arm']="b29f6d89c5d19056b297125a1a8222f641579bd2c70d2174ac91080100ec634a"
TARBALL_URL['x86_64']="https://github.com/termux/proot-distro/releases/download/v2.2.0/ubuntu-x86_64-pd-v2.2.0.tar.xz"
TARBALL_SHA256['x86_64']="799b2b1eaf8c2a97a57663a7a0acc568ab2714dedbd5c35b6f465f0aa9a5c407"

distro_setup() {
	# Don't update gvfs-daemons and udisks2
	run_proot_cmd apt-mark hold gvfs-daemons udisks2
}
```

We only provide one distribution either LTS, latest stable or rolling release type. also can you explain what package are missing in the distribution?

**Comment by singam-sanjay** [comment]
Thank you @wmcbtech30!

I use a lot of Python packages, which depend on python versions 3.7 or 3.8. The lowest available version in Ubuntu impish is python3.9, but python 3.8 is available in focal.

Maybe, you could rename (or symlink) the image TARBALLs to include the version of ubuntu to quickly identify them.

**Comment by wmcbtech30** [comment]
Closing since proot-distro is relying on latest versions of distribution
