### ISSUE TITLE
[Bug]: can't see a enter word

### ISSUE THREAD

**Issue by harrybates3253** [termux/proot-distro#203]
### Problem description

Hi,
       I use ubuntu downlod from proot-distro at android 9 ,vivo y3.
       Firstly,When I entry the passwd,suddently "login timed out after 60 seconds",then auto quit entry passwd ,
        Suddentely,after that every word i entry can'see, exit ubuntu  to Termux ,still .
        Later,I have to restart Termux,so that normal.Thanks for read

### What steps will reproduce the bug?

![IMG_20220317_134652](https://user-images.githubusercontent.com/101085793/158745077-dc36ca32-6b8e-47d5-8916-789722b81032.jpg)
when entry passwd,login timed out after 60 seconds,

### What is the expected behavior?

normal enter word

**Comment by wmcbtech30** [comment]
When filling a password on the Terminal. this is a normal behavior to avoid eavesdropping character count and the password you type. it would appear that no input was given but you are actually giving a password as you type
https://askubuntu.com/questions/112069/nothing-shows-up-in-the-terminal-when-i-type-my-password#124428

And you also need to make sure if your credentials you type are correct
