### ISSUE TITLE
[Feature]: package search in currently installed distros

### ISSUE THREAD

**Issue by sudomain** [termux/proot-distro#204]
### Feature description

Since I bought a phone with large internal storage, I keep most of the proot-distro's installed, though only 2 are really used regularly. When I learn of a new piece of software, the first thing I usually do is manually check which proot-distro has it and which has the newest version. I'd like to have a proot-distro subcommand, `package-search` (borrowing the hyphenated 2 word precedent set by the `clear-cache` command) which sequentially logs into each of the currently installed proot-distros and:
1. Updates the package list/cache in that distro using the appropriate package manager e.g. apt update, dnf check-update, etc.
2. Searches for the package using the appropriate package manager e.g. apt search, dnf search, pacman -Ss

It wont always work as the different distros sometimes name packages slightly differently, but that's on the user. If this is out of scope for this project please let me know: I'll attempt a wrapper function around proot-distro in my dotfiles.

**Comment by MrAdityaAlok** [comment]
> If this is out of scope for this project please let me know: I'll attempt a wrapper function around proot-distro in my dotfiles.

Yah..it is should be out of scope ;). This is just your use case, so you should implement yourself (it should be easy to).
 I do not think many people will really want that.

Closing it now. You may ask for any help if you need.
