### ISSUE TITLE
[Bug]:  Vsftp service not working in any linux distro in termux

### ISSUE THREAD

**Issue by anshiq** [termux/proot-distro#205]
### Problem description

Vsftp service not working in any linux distro in termux. 
![Screenshot_20220406-151603_Termux](https://user-images.githubusercontent.com/66484628/161947324-9bb389b3-5fbd-434e-ad6f-6b002903424e.jpg)

### Steps to reproduce the behavior.

Install any debian distro using proot-distro 
Update the repo of distro
Install vsftpd: apt install vsftpd 
Config vsftpd: nano /etc/vsftpd.conf   
Remove #   from  #write_enable=YES
Save the file.
Start vsftpd: service vsftpd start 
It throughs error 
Starting FTP server: vsftpdvsftpd failed - probably invalid config. ... (warning).

### What is the expected behavior?

It should run properly 

### System information

* Termux application version:
* Android OS version:
* Device model:

**Comment by Grimler91** [comment]
Well what port are you trying to run it on? Remember that proot doesn't provide root access, so ports lower than 1024 cannot be used

**Comment by Anshik-Singh** [comment]
I am using port 8888.

**Comment by Anshik-Singh** [comment]
If you found the solution please reply me.

**Comment by michalbednarski** [comment]
(Tested on `proot-distro archlinux`)

1. You'll need to configure different port (as I understand you've done this, so `vsftpd` should start (not exit immediately, although not yet allowing logging in), if not use `proot-distro login --fix-low-ports`)
2. Run following command inside proot: `chmod a-w /var/empty`
3. Change following options in `/etc/vsftpd.conf`: `connect_from_port_20=NO` and `chown_uploads=NO` (these features won't be available in proot)
4. (depending on distro this might be default, this step isn't Termux specific) it may be necessary to turn on `anonymous_enable` or `local_enable`

**Comment by michalbednarski** [comment]
On Debian there's `secure_chroot_dir=/var/run/vsftpd/empty` in default config, so in step 2 command will be
`mkdir /var/run/vsftpd/empty ; chmod a-w /var/run/vsftpd/empty`

I've had "probably invalid config" message when attempting to bind to low port, use `proot-distro login --fix-low-ports` and if still doesn't work try running `vsftpd` directly (without `service ... start`) to see error message

**Comment by Anshik-Singh** [comment]
Does it worked on your termux proot-distro linux distribution???

**Comment by michalbednarski** [comment]
Yes, I was able to start `vsftpd` on `proot-distro archlinux` and `proot-distro debian` on 64-bit ARM and connect from another device to ftp (haven't checked ftps)
