### ISSUE TITLE
[Bug]: bash: 'aarch64': syntax error: operand expected (error token is "'aarch64'")

### ISSUE THREAD

**Issue by Android-PowerUser** [termux/proot-distro#207]
### Problem description

In the readme.md it says that to add a distribution e.g.

`DISTRO_NAME="Debian"
TARBALL_URL['aarch64']="https://github.com/termux/proot-distro/releases/download/v1.10.1/debian-aarch64-pd-v1.10.1.tar.xz"
TARBALL_SHA256['aarch64']="f34802fbb300b4d088a638c638683fd2bfc1c03f4b40fa4cb7d2113231401a21"`

should enter. However this is output:
`bash: 'aarch64': syntax error: operand expected (error token is "'aarch64'")` 

Presumably adding distros this way wouldn't work if the example doesn't work with all CPU architectures.

### What steps will reproduce the bug?

Readme.md on the proot-distro page
Section:
Add distro
Code example see above.

### What is the expected behavior?

Debian should be added.

**Comment by MrAdityaAlok** [comment]
It works, but explain what exactly you did? How did you run or which command you used?

**Comment by Android-PowerUser** [comment]
Exactly what I wrote after running 
`pkg install root-distro`. 
Not more...

**Comment by MrAdityaAlok** [comment]
> Exactly what I wrote. I had before `pkg install root-distro` executed Not more...

There is no *roo-distro* package.

If you want to name your distro as `root-distro` then create a file named `root-distro.sh` at `$PREFIX/etc/proot-distro` and write your instructions there.  You may use `proot-distro list` to view that your distro has been recognised.  Then install using `proot-distro install root-distro`

**Comment by Android-PowerUser** [comment]
What I really mean is `pkg install proot-distro` Was a typo.

**Comment by MrAdityaAlok** [comment]
@Android-PowerUser It can be edited via external apps too. Look here https://wiki.termux.com/wiki/Internal_and_external_storage

Or you may use editors like nano or neovim inside Termux itself to edit files.

Closing since this isn't a bug. You may ask if you have any further queries.
