### ISSUE TITLE
After adding the path to the libgcc_s.so.1 file to LD_PRELOAD, the Termux UTILITIES stopped working

### ISSUE THREAD

**Issue by ZhymabekRoman** [termux/proot-distro#21]
A few days ago I had an SD card, where Termux was installed, went into "read-only" mode. Just yesterday I bought a new card and immediately delivered Termux and proot-distro. It seems that everything worked, but today I wanted to run utilities that are part of Termux (netstat, nano (in proot-distro rootfs nano was not installed), termux-api), but they sent me far further. The error was like this:

`CANNOT LINK EXECUTABLE "nano": library "/usr/lib/arm-linux-gnueabihf/libgcc_s.so.1" needed or dlopened by "/data/data/com.termux/files/usr/bin/nano" is not accessible for he namespace "(default)"`

Immediately libgcc_s.so.1 rushed into the eyes. I remembered that there were changes from the @xeffyr for fixing crash of TigerVNC server. As soon as I comment the line LD_PRELOAD in termux-proot.sh in the folder /usr/var/lib/proot-distro/installed-rootfs/ubuntu/etc/profile.d, all Termux utilities started working.

**Comment by WMCB-Tech** [comment]
All Termux binaries are compiled with Bionic libc with Android NDK. so the LD_PRELOAD library is loaded from the traditional linux distributions:
https://wiki.termux.com/wiki/Differences_from_Linux

And yeah i encountered the same

**Comment by ZhymabekRoman** [comment]
> All Termux binaries are compiled with Bionic libc with Android NDK and Linker. so the LD_PRELOAD library is loaded from the traditional linux distributions which it may not be compatible with Android:

I know about it. But now the question arises : how to implement that TigerVNC would work and Termux utilities would also work

**Comment by WMCB-Tech** [comment]
How about adding an option `--enable-ld-hack` for TigerVNC? in proot distro?

**Comment by ZhymabekRoman** [comment]
> How about adding an option `--enable-ld-hack` for TigerVNC? in proot distro? but it needs some adaptation

It's not serious. Although... we can make own special rootfs for proot-distro with recompiled TigerVNC. Sooner or later, we will have to create your own rootfs for Debian systems. Unfortunately, there are no ready-made Debian rootfs on the official website.

**Comment by WMCB-Tech** [comment]
I could host debian rootfs but unfortunately GitHub doesn't allow me to have bigger tarballs: debian images can be found here:
https://uk.images.linuxcontainers.org/images/debian/

**Comment by ZhymabekRoman** [comment]
> debian images can be found here:
> https://uk.images.linuxcontainers.org/images/debian/ or by forking Andronix/Anlinux Repo

I've seen it before. But just do want to depend on someone, it can bring consequences. I'm already writing a script to easily create rootfs Debian systems. This is one of the most reliable options.

**Comment by WMCB-Tech** [comment]
Well Debootstrap is an option but it's buggy and when creating a user accounts. it gives me permission denied. so it's hard to find such debian rootfs

**Comment by WMCB-Tech** [comment]
@ZhymabekRoman A walkaround to fix this is to locally unset the environment variable without unsetting it globally 

e.g:
`LD_PRELOAD="" termux-open`

**Comment by xeffyr** [comment]
LD_PRELOAD can be limited only for TigerVNC by providing `/usr/local/bin/vncserver` which will set environment variable and then launch actual `vncserver` script.

**Comment by xeffyr** [comment]
Will be fixed by specifying preload libs through `/etc/ld.so.preload` which is specific to GNU libc linker and will not impact binaries from Android OS.

However will be available only in newly created environments.

Part of v1.0 release.
