### ISSUE TITLE
Linux shell 

### ISSUE THREAD

**Issue by Szymon64** [termux/proot-distro#211]
### Problem description

Somehow apache2 doesn't work when we log into Ubuntu or another shell using the proot-distro command

### Steps to reproduce the behavior.

proot-distro login ubuntu 
apt install apache2 -y
apache2 

### What is the expected behavior?

[Mon Apr 18 09:17:32.036910 2022] [core:warn] [pid 19290] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot

### System information

* Termux application version:
* 0.118.0
* Android OS version:
* 11
* Device model:
* oppo a53

**Comment by sylirre** [comment]
You need to run Apache on high port or enable Proot transparent port rewrite.

Example for the latter:
```
~ $ proot-distro login --fix-low-ports ubuntu
root@localhost:~# apachectl start
/usr/sbin/apachectl: 99: ulimit: error setting limit (Operation not permitted)
Setting ulimit failed. See README.Debian for more information.

ATTENTION: A bind system call was requested on port: 80
The port has been changed. If connecting from outside Termux, use: 2080

root@localhost:~# curl -s localhost |& head -n 5
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <!--
    Modified from the Debian original for Ubuntu
    Last updated: 2022-03-22
```

**Comment by andresilva96** [comment]
Did you can to configure some virtual host inside the proot?

**Comment by sylirre** [comment]
Yes, web server virtual hosts should work in proot.

**Comment by andresilva96** [comment]
It's weird because I am creating inside sites-available and after a2dissite 000-default.conf and a2ensite my example.conf haven't effect after /etc/init.d/apache2 reload on proot-distro.

Sorry to be layman, I just prefer Nginx and with that I can't run because doesn't have php-fpm. ):

**Comment by andresilva96** [comment]
Well... just updating here I couldn't put Virtual Hosts with Proot, so I just downloaded the ubuntu from Andronix and worked!
