### ISSUE TITLE
[Distribution]: Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by Alextrapixel** [termux/proot-distro#212]
### Description

Next Ubuntu 22.04 LTS version released. Can it be Ubuntu LTS version separated from current ubuntu dist? 
also maybe `do-release-upgrade` support?
Thanks before. 

### Home page URL

https://ubuntu.com

### Root file system archive URL

https://cdimage.ubuntu.com/ubuntu-base/daily/pending/

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [x] Yes, distribution supports AArch64 and ARM.

**Comment by wmcbtech30** [comment]
proot-distro currently provides one distribution per version at a time and Ubuntu 21.10 is ending support in just months away. so I'll stick with 22.04 to be updated for the long-term

**Comment by wmcbtech30** [comment]
I have now updated `proot-distro` to 3.0.1 supporting Ubuntu 22.04. requires reinstallation for changes to take effect!

It should be available in the repositories soon, if you want to try it now. you can use the git version as a "preview". if you have problems, please open it on another issue ticket!
