### ISSUE TITLE
NixOS

### ISSUE THREAD

**Issue by leap0x7b** [termux/proot-distro#215]
### Home page URL

https://nixos.org/

### Root file system archive URL

https://hydra.nixos.org/job/nixos/trunk-combined/nixos.closures.smallContainer.aarch64-linux

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [X] Yes, distribution supports AArch64 and ARM.

**Comment by wmcbtech30** [comment]
The URL doesn't seem to provide rootfs archives or a direct link downloads for deployment.

**Comment by leapofazzam123** [comment]
Oh wait I meant https://hydra.nixos.org/job/nixos/trunk-combined/nixos.containerTarball.aarch64-linux

**Comment by leapofazzam123** [comment]
> Oh wait I meant https://hydra.nixos.org/job/nixos/trunk-combined/nixos.containerTarball.aarch64-linux

Can you test this rootfs?

**Comment by wmcbtech30** [comment]
The rootfs doesn't seem to be standard. most file systems are missing nor created (`/etc`, `/usr`)

**Comment by leapofazzam123** [comment]
Ok looks like from what I read, you need to run /nix/var/nix/profiles/system/activate, which generate a working NixOS system, after you run the script, you can finally run /run/current-system/sw/bin/bash to enter the NixOS system

**Comment by leapofazzam123** [comment]
Also the script needs to be modified like removing the mounting and hostname setup part

**Comment by wmcbtech30** [comment]
I found an `init` script which initializes nixos environment. i'll look into this trying soon.

**Comment by t184256** [comment]
(shameless plug, https://github.com/t184256/nix-on-droid provides a Nix-powered environment that's not NixOS though. also uses proot under the hood)

**Comment by myguidingstar** [comment]
I tried it myself and it only partly works. I built a `lxc` tarball with [nixos-generator](https://github.com/nix-community/nixos-generators) and feed it to `proot-distro`, then call `proot` to execute its `/sbin/init`. The script printed some error because systemd couldn't start: `Explicit --user argument required to run as user manager`
After that I could run commands from packages defined in the tarball (yay!), but `nix` command won't be able to install anything because `nix` service has not started because systemd couldn't start itself.

There seems to be some effort out there trying to run systemd with termux, but I haven't tried it yet.

**Comment by qwqawawow** [comment]
Any updates?

**Comment by lovince-create** [comment]
Hello

I was trying to run NixOS on proot and I got to this discussion. Very interesting

**Comment by lovince-create** [comment]
> > Oh wait I meant https://hydra.nixos.org/job/nixos/trunk-combined/nixos.containerTarball.aarch64-linux
> 
> Can you test this rootfs?

Tested these rootfs but the nix-dameon just hangs

**Comment by expenses** [comment]
@myguidingstar Do you happen to have your install script around anywhere?

**Comment by lovince-create** [comment]
@expenses I copied the binaries, the libraries and /etc files from an ubuntu tarball

**Comment by lovince-create** [comment]
I tried to do same for nix files, currently

nix files to ubuntu -> nix works
ubuntu files to nixos -> nix doesn't work

The socket returns permission denied, and when I run nix-daemon it hangs with
What to do when nix daemon hangs

```# nix daemon --debug --verbose
accepted connection from pid 17734, user 10343
received daemon op 19
accepted connection from pid 17741, user root (trusted)
accepted connection from pid 17744, user root (trusted)
accepted connection from pid 17746, user root (trusted)```

**Comment by expenses** [comment]
> @expenses I copied the binaries, the libraries and /etc files from an ubuntu tarball

Okay nice, if you have a script to do this I'll try it out but using s6-rc as @myguidingstar suggests.

**Comment by lovince-create** [comment]
Can edolstra help with that?

**Comment by qwqawawow** [comment]
> Can edolstra help with that?

Maybe nix-static could help.But we should use nix-on-droid anyway
