### ISSUE TITLE
[Distribution]: GNU Guix

### ISSUE THREAD

**Issue by neonolli** [termux/proot-distro#216]
### Home page URL

https://guix.gnu.org

### Root file system archive URL

https://ftp.gnu.org/gnu/guix/guix-binary-1.3.0.aarch64-linux.tar.xz

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [X] Yes, distribution supports AArch64 and ARM.

**Comment by frafra** [comment]
Has it been really completed? It is not listed under "Supported distributions". Someone asked for that under "Discussions": https://github.com/termux/proot-distro/discussions/305

**Comment by TomJo2000** [comment]
> Has it been really completed? It is not listed under "Supported distributions".

Should have probably been closed as not planned.
