### ISSUE TITLE
Add proot's built-in port forwarding feature

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#22]
So i was about to setup QEMU using proot-distro with SMB File sharing but the issue is SMB didn't start when QEMU is running. QEMU runs but SMB sharing didn't work only the 9p method (but the 9p protocol is not available for windows so smb is being used). so i was playing around with `proot -p` with debian chroot (which i asked in subreddit) then i could see some differences. when enabling the `proot -p` i tried to setup SMB with QEMU and it works. since SMB Server requires root access 

This is useful for some applications like QEMU + smb and for lazy people needs to configure ports every time they reset the distro which is very tiring especially when you need to test packages

So it would be nice to add it

However it does not automatically bind to higher port (2000) if the server runs at port higher than 1024

**Comment by xeffyr** [comment]
Flag `--fix-low-ports` is now in git version.
