### ISSUE TITLE
Ubuntu 22.04  lack write support for external storage

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot-distro#220]
### Feature description

Proot-distro install ubuntu command install Ubuntu 22.04. It allow user to access The external storage if user has used Termux-setup-storage command from Termux.
Unfortunately, I can not write data to The sdcard sub folders. I Am using Android 8.0 Oreo, Huawei 10 Mate Lite. Feature should allow user to also write to The subfolders of sdcard. I want to move one native .so library from download folder to The internal folder of Ubuntu. Now, I can only read from The subfolders of /sdcard sub folder.
Ubuntu work excellently including Proc emulation, so Mate desktop and Marco window manager can work like A charm.

**Comment by wmcbtech30** [comment]
I'm not sure what you're trying to refer to but access to external (removable) storage are limited as suppose read-only access is given if not using native storage APIs which apps uses it. the shared storage on the other hand can be either read-writable or non-accessible.

Likely your device has special configuration that can only read files in shared storage `/sdcard` by default. is this what you want? if yes then try granting storage permission

**Comment by sylirre** [comment]
This seem to be either device-specific issue or `proot` bug.

As Proot-Distro is just a wrapper for `proot`, it can't limit access to /sdcard subdirectories on its own.
