### ISSUE TITLE
[Feature] Ability To Create Docker-esque Containers/Python-esque venvs

### ISSUE THREAD

**Issue by danieldjewell** [termux/proot-distro#23]
Love this so far - had an idea: Right now, the distro configs are 1:1 (e.g. there's a config file called alpine.sh, archlinux.sh etc. and when you install you get just one copy of a distro),

I think it would be awesome to modify the process slightly to use those configs as templates (sort of like Dockerfiles) and then when installing being able to create as many named "containers" as you'd like. Obviously, nothing nearly as complex as Docker - no need for layers, overlayfs, etc. Just the ability to create separate installs without copying the distro config file. The config files are already essentially this way... 

Then, when launching, being able to choose by name just as now.  

(Could be relatively simple - default behavior is as it is now, create the install with the alias name the same as the distro name... but also having the ability to specify a different name for a second or third copy.)

Just a thought :)

**Comment by xeffyr** [comment]
This is going to be available in proot-distro v1.0. You may use a git version of `proot-distro` as "preview".

This is implemented via `--override-alias` flag and usage is:
```
proot-distro install --override-alias alpine-testenv alpine
proot-distro login alpine-testenv
```
