### ISSUE TITLE
[Bug]: Podman not working in Proot-Distro

### ISSUE THREAD

**Issue by zak-admin** [termux/proot-distro#230]
### Podman not working in Proot-Distro

I am trying to learn podman from my android non-root phone on debian proot-distro using termux. As I know, podman does not require root.

I installed it using the command `sudo apt-get install podman` on debian. It gave a positive response.

But when I try to verify it using `podman version`. But I got an error as follows:

```bash
cannot clone: Invalid argument
Error: cannot re-exec process
```

However `podman -v` displays the correct output

After that I tried executing `podman run -dit ubuntu`. I got the same error again.

#### Neofetch in my Debian is as follows:

```bash
_,met$$$$$gg.          user@localhost
    ,g$$$$$$$$$$$$$$$P.       ---------------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) armv7l
 ,$$P'              `$$$.     Host: Xiaomi Redmi 8A
',$$P       ,ggs.     `$$b:   Kernel: 5.4.0-faked
`d$$'     ,$P"'   .    $$$    Uptime: 3 days, 7 hours, 4 mins
 $$P      d$'     ,    $$P    Packages: 1097 (dpkg), 1 (pkg)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Theme: Orchis-Green-Dark-Compact [GTK3]
 Y$$.    `.`"Y$$$$P"'         Icons: WhiteSur-green-dark [GTK3]
 `$$b      "-.__              Terminal: proot
  `Y$$                        CPU: Qualcomm SDM439 (8) @ 1.708GHz
   `Y$$.                      Memory: 1269MiB / 1856MiB
     `$$b.
       `Y$$b.
          `"Y$b._
              `"""
```

**My Question**

1. Is it possible to *run podman from my android non-root phone on debian proot-distro?*
2. If yes, What should I do to correct this error message?

> Thanks in Advance

### What steps will reproduce the bug?

I dont't know

### What is the expected behavior?

Podman Works

**Comment by WMCBTech** [comment]
podman requires custom kernel and root installed in your device that supports running containers. closing since it's a no-fix in proot's side, you can use qemu to run containers inside.
