### ISSUE TITLE
[Bug]: pulseaudio broken in proot-distro.

### ISSUE THREAD

**Issue by macerg** [termux/proot-distro#231]
### Problem description

Since today's termux pulseaudio update, it is broken for use by proot-distro.
When starting vlc in proot-distro errors are displayed
`the audio device could not be found
No such file or directory
Audio output failed`

### What steps will reproduce the bug?

Start proot-distro Debian with pulseaudio initialised via start-up script.
Start vlc within proot-distro Debian and open audio file or stream.

### What is the expected behavior?

Sounds should be output without errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15098
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://cdn.lumito.net/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://cdn.lumito.net/termux/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://cdn.lumito.net/termux/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
11
Kernel build information:
Linux localhost 4.9.227-perf+ termux/termux-packages#1 SMP PREEMPT Fri Sep 17 17:16:18 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003

```

**Comment by macerg** [comment]
Ok, I'll try to improve my description of setup and show my proot-distro startup script. I'll do later as tied up at the moment. Thanks for reopening.

**Comment by macerg** [comment]
Here's my proot-distro Debian startup script:-
`am start --user 0 -n com.realvnc.viewer.android/com.realvnc.viewer.android.app.ConnectionChooserActivity >/dev/null 2>&1
pulseaudio --start
proot-distro login debian --user richard`

Not complex is it? Haha.

**Comment by Grimler91** [comment]
> `pulseaudio --start`

So you are starting termux's pulseaudio and then trying to use it from proot-distro? 
Or are you starting a separate pulseaudio inside proot-distro as well?

**Comment by macerg** [comment]
Yes, and it always worked fine within proot Debian before the last pulseaudio update. I've backed out the update ( I always backup before update) and it's working fine again now. Interestingly, termux isn't showing a pending update to pulseaudio now.

`apt search pulseaudio
Sorting... Done
Full Text Search... Done
cava/stable 0.8.2 aarch64
  Console-based Audio Visualizer. Works with MPD and Pulseaudio

ncpamixer/stable 1.3.3.1 aarch64
  An ncurses mixer for PulseAudio

pavucontrol-qt/x11 1.1.0 aarch64
  Qt port of volume control of sound server PulseAudio

pulseaudio/stable,now 14.2-10 aarch64 [installed]
  A featureful, general-purpose sound server`

**Comment by macerg** [comment]
Checking availability of current mirror:
[*] https://mirrors.pku.edu.cn/termux/termux-main/: ok
Hit:1 https://mirrors.pku.edu.cn/termux/termux-main stable InRelease
Hit:2 https://mirrors.pku.edu.cn/termux/termux-root root InRelease
Hit:3 https://mirrors.pku.edu.cn/termux/termux-x11 x11 InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by tomty89** [comment]
Can you actually provide some useful output / logs? Such as `pacmd list-modules` on the outside, `pactl list short sinks` on the inside, and logs from vlc with high enough verbosity (please research yourself on how to do that).

As for the "update not available anymore" problem, I guess it's because some mirrors are still not up-to-date yet...

**Comment by macerg** [comment]
I would if I could, unfortunately I've reverted to a backup and can no longer reproduce the issue. As a result, I am closing the issue. Sorry to cause inconvenience but, I assure all concerned, it WAS an issue.

**Comment by macerg** [comment]
Ok, I'm going to reopen this if may.  After further investigation, I'm not convinced that the pulseaudio update is the culprit. I'll provide as much information as I can. Currently, I've rolled back to termux from a few weeks ago. All works well. I've updated, omitting the pulseaudio update. Result,  Audio in proot-distro Debian broken again. I'll work through this and provide information as requested. Please bare with me, will assist as much as able.

**Comment by macerg** [comment]
Problem disappeared!
