### ISSUE TITLE
[Bug]: why   proot error: unknown option '--sysvipc'. fatal error: see `proot --help`.

### ISSUE THREAD

**Issue by erbasisan** [termux/proot-distro#235]
### Problem description

why  err
proot error: unknown option '--sysvipc'.
fatal error: see `proot --help`.

### What steps will reproduce the bug?

why  err
proot error: unknown option '--sysvipc'.
fatal error: see `proot --help`.

### What is the expected behavior?

proot error: unknown option '--sysvipc'.
fatal error: see `proot --help`.

**Comment by Grimler91** [comment]
Apparently sysvipc is an unknown option in the proot you are using.

You haven't provided any info so nothing to do here..
