### ISSUE TITLE
[Bug]: No such file or directory

### ISSUE THREAD

**Issue by zxp1314gch** [termux/proot-distro#236]
### Problem description

I have tried all versions of linux and all reported similar errors

android 11 termux 0.118.0
### What steps will reproduce the bug?

~ $ **proot-distro install alpine**
Installing Alpine Linux (edge)...
Using cached rootfs tarball...
Checking integrity, please wait...
Extracting rootfs, please wait...
proot info: vpid 1: terminated with signal 11
**[*] Writing '/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile'...
/data/data/com.termux/files/usr/bin/proot-distro: line 371: /data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs/alpine/etc/profile: No such file or directory**

### What is the expected behavior?

install linux

**Comment by sylirre** [comment]
Proot Distro is only a wrapper script for `proot`. Report the issue to https://github.com/termux/proot instead.
