### ISSUE TITLE
[Bug]: Ubuntu 22.04 Xfce always failed to start

### ISSUE THREAD

**Issue by makerandreas** [termux/proot-distro#238]
### Problem description

I have installing Ubuntu 22.04 with proot-distro and also install Xfce as it's desktop environment. Initially it runs as expected without any issues, but after installing Mozilla Thunderbird in this distro, then logging out and then log back again with `vncserver  -xstartup startxfce4` and use VNC Viewer to connect to my Ubuntu, the connection suddenly closed after a few seconds.

The most astonishing thing was,  after several attempts using the command `vncserver -xstartup startxfce4`, the problem is not happen until next login, which is where the problem even reappears again.

Here's the crash log found on the `.vnc/localhost.localdomain:5901.log` (note: `makerandreas` is my Ubuntu username)

```
_XSERVTransmkdir: Owner of /tmp/.X11-unix should be set to root
                                                                                        Xvnc TigerVNC 1.12.0 - built 2022-03-25 17:06                                           Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
See https://www.tigervnc.org for information on TigerVNC.
Underlying X server release 12101003, X.Org                                                                                                                                     
Thu Sep  1 22:42:52 2022                                                                 vncext:      VNC extension running!
 vncext:      Listening for VNC connections on local interface(s), port 5901
 vncext:      created VNC server for screen 0                                           3NI3X0 New Xtigervnc server 'localhost.localdomain:1 (makerandreas)' on port 5901 for display :1.
3NI3X0 Use xtigervncviewer -SecurityTypes VncAuth -passwd /home/makerandreas/.vnc/passwd :1 to connect to the VNC server.                                                       /usr/bin/startxfce4: X server already running on display :1                             [mi] mieq: warning: overriding existing handler (nil) with 0xf0f01dd for event 2
[mi] mieq: warning: overriding existing handler (nil) with 0xf0f01dd for event 3
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root                           xfce4-session: No SSH authentication agent found

(xfwm4:23853): xfwm4-WARNING **: 22:42:58.380: Unsupported GL renderer (llvmpipe (LLVM 13.0.1, 128 bits)).

(xfsettingsd:24044): libupower-glib-WARNING **: 22:42:59.088: Couldn't connect to proxy: Could not connect: Tidak ada berkas atau direktori seperti itu

Thu Sep  1 22:42:59 2022
 ComparingUpdateTracker: 0 pixels in / 0 pixels out
 ComparingUpdateTracker: (1:nan ratio)

(xfsettingsd:24044): xfsettingsd-CRITICAL **: 22:42:59.186: Failed to apply display settings
 Connections: accepted: 127.0.0.1::57816
 SConnection: Client needs protocol version 3.8
 SConnection: Client requests security type VncAuth(2)
 VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
 VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian rgb888

** (xiccd:24433): CRITICAL **: 22:43:03.559: Failed to connect to colord: Could not connect: No such file or directory
Failure: Module initialization failed

(polkit-gnome-authentication-agent-1:24541): polkit-gnome-1-WARNING **: 22:43:05.541: Error getting authority: Error initializing authority: Could not connect: No such file or directory

** (xfce4-screensaver:24440): WARNING **: 22:43:06.044: screensaver already running in this session

(wrapper-2.0:24349): Gtk-WARNING **: 22:43:08.930: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkButton)
(EE)
(EE) Backtrace:
(EE)
(EE) Segmentation fault at address 0xc
(EE)
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE)
The Xtigervnc server died with signal 6!
```

Is that problem related to Xfce or Ubuntu itself or it's related to Thunderbird? Please help

### What steps will reproduce the bug?

1. Starting Xfce in Ubuntu 22.04:
`vncserver -xstartup startxfce4`

2. Open the Xfce Terminal app (inside Ubuntu) and install Mozilla Thunderbird app:
`sudo apt install thunderbird`

3. Close the terminal and log out from Ubuntu (by using Application menu > logout and then logout from Ubuntu using `logout` command)

4. Executing the `proot-distro login ubuntu` and use `login` command to log on to my Ubuntu user account

5. Lastly, start the VNC Server again using `vncserver -xstartup startxfce4` command, go back to connect with VNC Viewer app again, and the error "The connection closed unexpectedly" appears.

### What is the expected behavior?

After attempting to start with `vncserver -xstartup startxfce4` command and then connect to Ubuntu via VNC Viewer app, it just shows the blank screen (eventually the Xfce Panel also shown up with some of its plugin), and then the notification "The connection closed unexpectedly" suddenly appears.

I've even try to reconnect several times using same commands without success before it successfully connected. And the log file found on the `.vnc/localhost.localdomain:5901.log` doesn't show errors related to Thunderbird app I've installed before. After I tried uninstall Thunderbird from my Ubuntu, the problem disappear.

**Comment by sylirre** [comment]
Try using tightvncserver instead.

Note that Proot Distro is only a Bash script wrapper for `proot` utility. All `proot` runtime issues should be reported to https://github.com/termux/proot.
