### ISSUE TITLE
[Bug]: termux-home option 

### ISSUE THREAD

**Issue by baraa272** [termux/proot-distro#241]
### Problem description

When I cd into any folder under (storage) when using termux-home option it's gives me error no such a file or directory even though termux have access normally to those folders but I can't access them inside distro (Ubuntu) using proot distro option (termux-home) 
![Screenshot_20220919-130748_Termux](https://user-images.githubusercontent.com/32843097/190996073-12007cd5-2158-481e-8cfb-f7b248de68f4.png)

### What steps will reproduce the bug?

proot-distro login Ubuntu --termux-home 
Cd storage 
Cd shared 
No such a file or directory 

### What is the expected behavior?

Access those folders and read write normally

**Comment by Grimler91** [comment]
Use ´--bind` on those extra folders that you want to access, from the [README](https://github.com/termux/proot-distro):

> `--bind path:path`
> 
> Create a custom file system path binding. Option expects argument in the given format:
> 
> `<host path>:<chroot path>`
