### ISSUE TITLE
Can't access termux api

### ISSUE THREAD

**Issue by lonely-v3n1x** [termux/proot-distro#25]
$ proot-distro login ubuntu
root@localhost:~# ls
root@localhost:~# am
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/sh": library "libc.so.6" not found
Aborted
root@localhost:~# termux-info
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/bash": library "libc.so.6" not found
Aborted
root@localhost:~# nano
CANNOT LINK EXECUTABLE "nano": library "libc.so.6" not found
Aborted

This is what i when i run Termux-Api commands

**Comment by xeffyr** [comment]
> root@localhost:# am

```
LD_PRELOAD="" am
```
Will fix it soon.

> root@localhost:# nano

Avoid using commands from Termux prefix whenever possible.

**Comment by lonely-v3n1x** [comment]
> > root@localhost:# am
> 
> ```
> LD_PRELOAD="" am
> ```
> 
> Will fix it soon.
> 
> > root@localhost:# nano
> 
> Avoid using _normal_ (like nano) commands from Termux prefix whenever possible.

Still getting errors
