### ISSUE TITLE
[Bug]: `cd` failure with proot

### ISSUE THREAD

**Issue by sqrt2802** [termux/proot-distro#251]
### Problem description

I'm using `alpine-minirootfs-3.15.6-aarch64` with the command
`proot -r [redacted] -w /root/ --kill-on-exit -k 5.15.59-faked -0 -l --sysvipc -p -L` .
When I run `cd` inside the container, the error `-sh: cd: can't cd to /data/data/com.termux/files/home: No such file or directory` appear.
It seems that the option `-w /root/` failed to work, but switching to `proot-distro` solves the problem.
Why?

### What steps will reproduce the bug?

```
mkdir alpine15 && cd alpine15
wget https://dl-cdn.alpinelinux.org/alpine/v3.15/releases/aarch64/alpine-minirootfs-3.15.6-aarch64.tar.gz && tar -xzvf *  && rm -f alpine*
proot -r ./ -w /root/ --kill-on-exit -k 5.15.59-faked -0 -l --sysvipc -p -L
cd /
cd
```

### What is the expected behavior?

The working directory will be switched to `/root` after the `cd` command.

**Comment by michalbednarski** [comment]
Option `-w` sets initial working directory, you can see its effect by running `pwd` after starting (before using `cd`)

`cd` without argument defaults to `$HOME`, which isn't affected by proot start, set that environment variable
