### ISSUE TITLE
OpenSUSE issue

### ISSUE THREAD

**Issue by Natri123** [termux/proot-distro#271]
### Problem description

I installed OpenSUSE and when I login to it, it shows me this warning.
Warning: no /bin/su available in rootfs! You may need to install package 'util-linux' or 'shadow' (shadow-utils) or equivalent, depending on distribution.

### What steps will reproduce the bug?

I have the bug before I could even do the other things in my distro

### What is the expected behavior?

I can't use use apt and when I try to do it, it gives me this "Ability to run this command as root has been disabled permanently for safety purposes."

**Comment by powerjungle** [comment]
`zypper install util-linux` should do the trick.
