### ISSUE TITLE
Ubuntu X86_64 Apt

### ISSUE THREAD

**Issue by ghost** [termux/proot-distro#298]
### Problem description

I think RootFS apt keys needed update or something idk sorry (Used qemu-x86_64 I not have x86_64 device)

AArch64 and ArmV7 RootFS is fine too

Screenshoot:
![Screenshot_2023_0508_211847](https://user-images.githubusercontent.com/82843871/236901488-9a981335-dc37-4940-bf03-05c5b3641580.jpg)

### What steps will reproduce the bug?

apt update

### Bug report policy acknowledgement

- [X] I understand that PRoot Distro won't fix distribution issues.

**Comment by mcagabe19** [comment]
damn
