### ISSUE TITLE
[INFO | BUG]: QEMU no longer works with PRoot Distro

### ISSUE THREAD

**Issue by sylirre** [termux/proot-distro#299]
**This is a notice that some of PRoot Distro features may not work correctly due to bug in dependencies.**

### Problem description

Recently I've discovered that QEMU (user-mode) no longer works with PRoot Distro on all my devices. It is unknown when and what exactly triggered the problem, but it is definitely not related to the `proot-distro` script as I can reproduce the issue with standalone `proot` command and x86_64 Ubuntu rootfs directory.

Devices (both aarch64) show different error messages.

Samsung Galaxy S7:
![Screenshot_20230509-135510_Termux](https://github.com/termux/proot-distro/assets/107305601/7e0f9b03-74a8-4e4b-84f8-f49e973e3be6)

Google Pixel 5:
![Screenshot_20230509-140537](https://github.com/termux/proot-distro/assets/107305601/ed75ce18-aa8e-4d01-8935-453bed64ec28)

### What steps will reproduce the bug?

Requirement: AArch64 device. I'm not sure whether bug affects ARM (32bit) and i686.

1. `nano $PREFIX/etc/proot-distro/ubuntu.sh` and add line `DISTRO_ARCH=x86_64`. This will trigger QEMU (user-mode) usage by PRoot.
2. `proot-distro install ubuntu` (assuming the rootfs was not installed or has been deleted)
3. `proot-distro login ubuntu`

Behavior may vary between device models and Android versions. There are chances that above steps will work without problems.

### What is the expected behavior?

Bash prompt should appear.

**Comment by mcagabe19** [comment]
@sylirre in debian i386 is fine there is no ubuntu i386 rootfs (tested at same device)

**Comment by mcagabe19** [comment]
@sylirre i see now its how worked on me... i've already have installed 7.1.0
![Screenshot_2023_0509_182620](https://github.com/termux/proot-distro/assets/82843871/84bf4bd8-7769-48b9-9c05-d01fbe5d23eb)

**Comment by michalbednarski** [comment]
`git bisect` pointed to https://github.com/qemu/qemu/commit/55bbe4d5ee52e77951dda62b08e37cd0dd8ddb5b

I guess I'll have to implement `execveat` in `proot` (currently `execveat` is only on list of defined syscalls there, but has no handlers)

**Comment by michalbednarski** [comment]
Issue should be fixed with `proot 5.1.107-59` in Termux apt repo (might take some time to propagate into mirrors)

**Comment by mcagabe19** [comment]
> Issue should be fixed with `proot 5.1.107-59` in Termux apt repo (might take some time to propagate into mirrors)

cool

**Comment by mcagabe19** [comment]
@michalbednarski @sylirre its now fixed thanks for helping
