### ISSUE TITLE
$PREFIX/bin/getprop returns nothing

### ISSUE THREAD

**Issue by sudomain** [termux/proot-distro#3]
getprop doesn't seem to be functioning in the proot. Probably another bindpoint is needed. My end goal is to use the result of `getprop ro.product.model` as my prompt instead of localhost

`[root@localhost ~]# getprop
getprop: property_list
[root@localhost ~]# getprop ro.product.model

[root@localhost ~]# /system/bin/getprop ro.product.model

`

**Comment by xeffyr** [comment]
It works for me... Maybe there really are rom-specific bindings are needed.

Try to run `getprop` under strace: `strace -fv getprop |& grep open` - to see which files it tries to access.

**Comment by sudomain** [comment]
[root@localhost ~]# strace -fv getprop |& grep open
proot warning: ptrace request 'PTRACE_???' not supported yet
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC) = 3
openat(AT_FDCWD, "/property_contexts", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/data/data/com.termux/files/usr/lib/libc.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libc.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/property_contexts", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/vendor/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib/libc++.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib/libcutils.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib/libm.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib/liblog.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 7
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib/libnetd_client.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/data/data/com.termux/files/usr/bin/getprop", O_RDONLY|O_LARGEFILE) = 3
openat(AT_FDCWD, "/dev/urandom", O_RDONLY|O_LARGEFILE|O_NOFOLLOW|O_CLOEXEC) = 3
openat(AT_FDCWD, "/property_contexts", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libcutils.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib/libselinux.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 4
openat(AT_FDCWD, "/system/lib/libc.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 5
openat(AT_FDCWD, "/system/lib/libm.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 6
openat(AT_FDCWD, "/system/lib/liblog.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 7
openat(AT_FDCWD, "/system/lib/libc++.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 8
openat(AT_FDCWD, "/system/lib/libcrypto.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 9
openat(AT_FDCWD, "/system/lib/libpcre.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 10
openat(AT_FDCWD, "/system/lib/libpackagelistparser.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 11
openat(AT_FDCWD, "/system/lib/libstdc++.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 12
openat(AT_FDCWD, "/property_contexts", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/system/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/vendor/lib/libvendorconn.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/sys/devices/system/cpu/online", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
openat(AT_FDCWD, "/system/lib/libnetd_client.so", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 3
[root@localhost ~]#

**Comment by xeffyr** [comment]
Seems like `/property_contexts` is required.

**Comment by xeffyr** [comment]
Done in https://github.com/termux/proot-distro/commit/bf852cbb73c817cabda8a40fa1e4073bb634da85.

**Comment by sudomain** [comment]
Thanks!
