### ISSUE TITLE
Add support for Debian distribution

### ISSUE THREAD

**Issue by xeffyr** [termux/proot-distro#30]
Add support for these distributions:
* Debian Stable (debian-stable or debian-buster (?))
* ~~Debian Sid (debian-sid)~~ sid is low-prio

Will require building own rootfs tarballs and hosting somewhere (probably as attachments to proot-distro version tag).

**Comment by WMCB-Tech** [comment]
Found Debian Rootfs URL's:
https://github.com/debuerreotype/docker-debian-artifacts/

Rootfs can be downloaded via branch based on the architecture
arm64/arm for example:
https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-arm64v8
https://github.com/debuerreotype/docker-debian-artifacts/tree/dist-arm32v7

**Comment by xeffyr** [comment]
Rootfs must be either officially provided by distribution or by @termux. I'm on it, will be a part of 1.2 release.

**Comment by xeffyr** [comment]
Closing as support for `Debian 10 Stable/Buster` is not available in git.

Debian Sid will be added later, its not a priority now.

**Comment by xeffyr** [comment]
Also: rootfs tarballs are attached at https://github.com/termux/proot-distro/releases/tag/v1.1-debian-rootfs. They are very close to original Debian `debootstrap` installation, changes only done to `/etc/hosts`, `/etc/resolv.conf` and `/etc/apt/sources.lists`.

These tarballs can be used to create a normal chroot as permissions shouldn't be messed up just like in ones by Anlinux.
