### ISSUE TITLE
Add support for backing up installed distributions

### ISSUE THREAD

**Issue by xeffyr** [termux/proot-distro#31]
Allow user to backup specific distribution into tarball and possibly into stdout for piping over ssh, etc.

**Comment by WMCB-Tech** [comment]
So when will this feature to be implemented?

**Comment by xeffyr** [comment]
Part of v1.3

Usage:
```
proot-distro backup --output file.tar.gz <distribution-name>
proot-distro restore ./file.tar.gz
```
Piping to stdout and reading from stdin is supported.

Limits:
* Archive compression is GZip (\*.gz) only.
* Free-form rootfs archives aren't supported.  Proot-Distro can do restore only from archives created by itself. If you make a custom rootfs and supply it to $PREFIX, you will likely end with messed up $PREFIX.
Both cases aren't subject to change in future. If you want more powerful options for backup/restore, you will have to write own scripts for this.
