### ISSUE TITLE
on bluestacks cant use tar says access denied to /usr/lib

### ISSUE THREAD

**Issue by crocer211** [termux/proot-distro#32]
on bluestacks cant use tar says access denied to /usr/lib but was trying to test proot-distro on bluestacks to run linux on it but tar is unavailable any help

**Comment by xeffyr** [comment]
This is problem of Bluestacks.

Termux requires a Linux-compatible environemnt to run. Bluestacks is not such. If you want to run Termux and proot-distro on emulator, use virtual device from Android SDK or Android x86 with VirtualBox.

**Comment by crocer211** [comment]
well your wrong memu android emulator runs termux and proot stuff just fine
