### ISSUE TITLE
Distribution 'kali' known to be used by hax and therefore is not safe. Redirecting to 'ubuntu'...

### ISSUE THREAD

**Issue by mesflit** [termux/proot-distro#324]
### Problem description

Distribution 'kali' known to be used by hax and therefore is not safe. Redirecting to 'ubuntu'...

### What steps will reproduce the bug?

Distribution 'kali' known to be used by hax and therefore is not safe. Redirecting to 'ubuntu'...

### Bug report policy acknowledgement

- [X] I understand that PRoot Distro won't fix distribution issues.

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Hacking

**Comment by 2096779623** [comment]
https://wiki.termux.com/wiki/hacking

https://github.com/termux/proot-distro/blob/f6c912a90d56b3a7b205a401abb1f027411229f7/proot-distro.sh#L2184
