### ISSUE TITLE
[Bug]: Gnome-session not starting on Proot Ubuntu 

### ISSUE THREAD

**Issue by chocolatecakecake** [termux/proot-distro#336]
### Problem description

I am getting no such file or directory error.

### What steps will reproduce the bug?

In Ubuntu, when i start the gnome-session for x11, it crashes.

### Bug report policy acknowledgement

- [x] I understand that PRoot Distro won't fix distribution issues.

**Comment by twaik** [comment]
1. We can not debug such things without logs, screenshots, etc.
2. It will not work in ubuntu since it requires systemd. There were some people who had success in launching it with debian.

**Comment by chocolatecakecake** [comment]
Is there no way I can use gnome in Ubuntu?

**Comment by twaik** [comment]
No way.

**Comment by chocolatecakecake** [comment]
I tried to install the systemd but apt says already installed.

**Comment by chocolatecakecake** [comment]
Last question: Can I install xfce on Ubuntu and use it with x11?

**Comment by twaik** [comment]
As far as I know you can. But I did not use it.

**Comment by chocolatecakecake** [comment]
Ok thanks.
