### ISSUE TITLE
Internet Connection (WiFi/Mobile Data) Not Connected with Not Showing Instead of Proot Distro Desktop

### ISSUE THREAD

**Issue by BBCByComcast** [termux/proot-distro#344]
### Description

My Internet Connection (WiFi/Mobile Data) Not Connected with Not Showing, I Don't See Internet Connection Know to Proot Distro Desktop
Proot-distro desktop environment issue with Android 13 Issue has Vendor Side Issue
![image](https://github.com/termux/proot-distro/assets/137778363/201e883b-1080-4e8b-9bb5-76c8a5fc4424)
I Finally Fix/Solve a Our Vendor Issue with That Command:
'mkdir $PREFIX/tmp/.X11-unix'
'sudo apt install xorg'
'mkdir /tmp/.X11-unix'
I Upgrade Ubuntu 23.10 with That Command
'nano /etc/apt/sources.list'
'apt update && apt upgrade'
I Created a Kubuntu 23.10 Using That Command:
'mv ubuntu.sh kubuntu.sh'
'nano kubuntu.sh'
'nano $PREFIX/etc/kubuntu.sh'
'DISTRO_NAME="Kubuntu"'
'mv kubuntu.sh proot-distro'
'mv kubuntu.sh $PREFIX/etc/proot-distro'
'nano .config/neofetch/config.conf'
'distro="Kubuntu 23.10 Mantic Minotaur"'
'ascii_distro='Kubuntu''
I Installed KDE Plasma Using That Command:
'sudo apt install kubuntu-desktop'
I Fix/Solve Pulseaudio Using That Command:
'nano $PREFIX/etc/pulse/default.pa'
'load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1'
'nano $PREFIX/etc/pulse/daemon.conf'
'exit-idle-time = -1'
'pulseaudio --start'
'export PULSE_SERVER=127.0.0.1'
But Internet Connection (WiFi/Mobile Data) Not Connected with Not Showing Instead of Proot Distro Desktop
![Screenshot_2023-10-15-16-59-57-69_00df01c412509efb9bd6450c382822af](https://github.com/termux/proot-distro/assets/137778363/f4157f92-bacd-4fc4-8064-36aa4fcd6c27)
Any Problem?

### Home page URL

https://kubuntu.org/

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [X] Yes, distribution supports AArch64 and ARM.

**Comment by twaik** [comment]
Distros installed with proot-distro, proot or even termux itself do not have access to connection settings. It is restriction of the proot and android sandboxing mechanisms. It will not be fixed.

**Comment by BBCByComcast** [comment]
Oh, But KDE Software Center May Be Not Connected, Just Any Problem

**Comment by BBCByComcast** [comment]
Oops, My Bad, I'm Closing This

**Comment by BBCByComcast** [comment]
I Closed This, I am Sorry twaik, But KDE Software Center May Be Fine, I Have Delete My Arts in Deviantart

**Comment by BBCByComcast** [comment]
> Distros installed with proot-distro, proot or even termux itself do not have access to connection settings, this subsystem is simply not accessible by non-Java programs. It is restriction of the proot and android sandboxing mechanisms. It will not be fixed.
> 
> But in any way it will have Internet access. It is resolved using some other mechanism which is accessible.

Twaik, Can You Ask?
