### ISSUE TITLE
Auto Exit

### ISSUE THREAD

**Issue by lonely-v3n1x** [termux/proot-distro#35]
The proot auto exits when i am building dlib

**Comment by xeffyr** [comment]
Sorry, but https://github.com/termux/proot-distro/issues is only about `proot-distro` script issues. Not about `proot` utility or Termux in general.

You may try login with option `--no-sysvipc`, if `proot` crashes with error like in https://github.com/termux/proot/issues/133.

However this can also be out-of-memory condition, so process is terminated by Android OS to reclaim some RAM. In this case nothing can be done except getting a better device.
