### ISSUE TITLE
[Distribution]: Termux Distro Will Update Ubuntu to Brand New Ubuntu Version

### ISSUE THREAD

**Issue by BBCByComcast** [termux/proot-distro#355]
### Description

Ubuntu 24.04 is a Upcoming Ubuntu Version That on Deban 12 (Until 2025, Debian 13 Launched with a Codename "Trixie"), Termux Updating Ubuntu Version in November 1 2023, Termux Finally Updated Ubuntu Version in April 25 2024, Ubuntu Start Codename is "Noble Numbat" with LTS Version, There a Nobel Numbat Program has Ubuntu Program:
- Development = Not Release Yet
- Beta Program = Not Release Yet
- Stable Program = Not Release Yet
Termux Know That Ubuntu 24.04 Will Release in April 25 2024, And Ubuntu 24.04 Wallpaper That in Ubuntu:
![Picsart_23-10-29_15-56-05-072](https://github.com/termux/proot-distro/assets/137778363/f70829c2-2e10-4fff-9258-1ddf96a604cc)
At Least GNOME 46 Will Launch in March 20, GNOME 46 Features is:
Foreground Apps
Redesign GNOME Software
Ground Apps Selection
Blurred GNOME Shell with GNOME Panel And GNOME Menu
GNOME Connect
Improve GNOME from Smaller to Small
Here Release Date What Should it:
GNOME 46: March 20 2024
GNOME 46.1: April 20 2024
Ubuntu 24.04 LTS: April 25 2024
Here GNOME Update Date What Should it:
GNOME 46.2: May 20 2024
GNOME 46.3-46.5: June 20 2024
GNOME 46.6-46.7: July 20 2024
GNOME 46.8-46.9: August 20 2024
Here GNOME 47 Update Date What Should it:
GNOME 47: September 20 2024
GNOME 47.1: October 20 2024
GNOME 47.2-47.5: November 20 2024
GNOME 47.6-47.9: December 20 2024
Here GNOME 48 Update What Should it:
GNOME 48: March 20 2025
GNOME 48.1: April 20 2025
GNOME 48.2: May 20 2025
GNOME 48.3-48.5: June 20 2024
GNOME 48.6-48.9: August 20 2025
Here GNOME 49 Update What Should it:
GNOME 49: September 20 2025
GNOME 49.1: October 20 2025
GNOME 49.2-49.7: November 20 2025
GNOME 49.8-49.9: December 20 2025
Here Ubuntu Update What Should it:
Ubuntu 24.04.1 LTS
Ubuntu 24.04.2 LTS
Ubuntu 24.04.3 LTS
Thanks for Problem
https://github.com/termux/proot-distro/issues/352
### Home page URL

https://ubuntu.com/

### Is requested distribution has support for AArch64 (ARM64) and ARM CPUs?

- [X] Yes, distribution supports AArch64 and ARM.

**Comment by TomJo2000** [comment]
What do you expect us to do about software that doesn't even exist yet?
Ubuntu 24.04 will be offered in proot-distro once its available, it's a pretty simple addition but it can not be made until that version is publicly released.

**Comment by BBCByComcast** [comment]
> What do you expect us to do about software that doesn't even exist yet? Ubuntu 24.04 will be offered in proot-distro once its available, it's a pretty simple addition but it can not be made until that version is publicly released.

No, GNOME Software Still Exist Though GNOME Will Redesign GNOME Softw

**Comment by BBCByComcast** [comment]
> What do you expect us to do about software that doesn't even exist yet? Ubuntu 24.04 will be offered in proot-distro once its available, it's a pretty simple addition but it can not be made until that version is publicly released.

No, GNOME Software Still Exist Though GNOME Will Redesign GNOME Software in March 20 2024, Ubuntu 24.04 Will Be Recommend, Suggestion And Offered in Proot Distro, However It's Pretty Simple Additional with Additional Settings, And Why Are You Not Made?

**Comment by TomJo2000** [comment]
> No, GNOME Software Still Exist Though GNOME Will Redesign GNOME Software in March 20 2024, Ubuntu 24.04 Will Be Recommend, Suggestion And Offered in Proot Distro, However It's Pretty Simple Additional with Additional Settings, And Why Are You Not Made?

There seems to be a language barrier here.
We can not package a version of Ubuntu that has not been released yet.
We can revisit this in 5 months, when Ubuntu 24.04 Noble Numbat has actually been publicly released.
