### ISSUE TITLE
[Bug]: How to call functions for `proot-distro`  from outside of the `proot-distro`

### ISSUE THREAD

**Issue by HusniMuhammad** [termux/proot-distro#358]
### Problem description

How to call functions for proot-distro from outside of the proot-distro

![Screenshot_20231102-183317](https://github.com/termux/proot-distro/assets/104101867/7a3da422-3015-4ccd-83e2-a32ac1804c82)

### What steps will reproduce the bug?

```
my_echo() {
  echo "Hello"
}

proot-distro login debian -- /bin/bash -c 'export DISPLAY=:1; my_echo'

```

### What is the expected behavior?

Execution of the function

**Comment by TomJo2000** [comment]
The `my_echo` function is undefined in the Proot environments Shell.

You could define it by either:
- literally assigning it as part of the command passed to the Proot
- using `source` on file containing the function definition
- if you are going from Bash to another instance of Bash `export -f my_echo` *may* work, though I don't know if Proot passes along exported variables and functions.

**Comment by HusniMuhammad** [comment]
How to export function?

**Comment by TomJo2000** [comment]
> How to export function?

`export -f my_function_name`

Please note this functionality is unique to Bash and does not work for POSIX sh, Zsh, Fish, etc.

It appears to work with Bash's POSIX Mode, though I believe this to be a bug as the POSIX standard doesn't specify a `-f` flag for `export`.

**Comment by HusniMuhammad** [comment]
```
my_echo() {
  echo "Hello"
}

export -f my_echo

proot-distro login debian -- /bin/bash -c 'export DISPLAY=:1; my_echo'
```

Is this correct?

**Comment by TomJo2000** [comment]
As a wise man once said.
Fuck around and find out.

But yes unless Proot gets in the way of it that looks correct.

**Comment by HusniMuhammad** [comment]
> As a wise man once said. Fuck around and find out.
> 
> But yes unless Proot gets in the way of it that looks correct.

Here I found it

```sh

upt='if (apt update | grep upgraded); then apt -y upgrade; else echo -e "No updates in $(uname -sr)"; fi'

proot-distro login debian -- bash -c "$upt" & P1=$!

bash -c "$udt" & P2=$!

wait $P1 $P2
```
