### ISSUE TITLE
[Bug]: Cannot run pkg command as root

### ISSUE THREAD

**Issue by Drjacky** [termux/proot-distro#359]
### Problem description

<img width="400" alt="Screenshot 2023-11-05 at 10 56 40" src="https://github.com/termux/proot-distro/assets/2296754/8b90835f-0d8e-4c06-b52f-3bf2b49b0ddb">

### What steps will reproduce the bug?

Run `pkg update`

**Comment by Drjacky** [comment]
Replace pkg with apt

**Comment by TomJo2000** [comment]
This is actually intentional to save you from significant amounts of pain.

Yes you can run apt as root, but any package installed as root won't be accessible to a regular user and running apt as root may potentially overwrite files unintentionally.

**Comment by Kamalofficial24** [comment]
> Replace pkg with apt

E: Unable to locate package tsu
Now I got this 🙄
What can I do
