### ISSUE TITLE
Unable to write files inside proot'ed Ubuntu 

### ISSUE THREAD

**Issue by gustavomello9600** [termux/proot-distro#36]
Suddenly, all the commands run after I enter the Ubuntu distribution via `proot-distro login ubuntu` throw error messages with "required key not available" in It.

Sounds like it lost the capacity of writing to my internal storage. Here is some of the errors thrown:

Initializing pyenv
```
/root/.pyenv/libexec/pyenv-init: line 131: cannot create temp file for here-document: Required key not available
pyenv: cannot rehash: /root/.pyenv/shims/.pyenv-shim exists
/root/.pyenv/plugins/pyenv-virtualenv/bin/pyenv-virtualenv-init: line 94: cannot create temp file for here-document: Required key not available
```

Making a git pull
```
remote: Enumerating objects: 82, done.
remote: Counting objects: 100% (82/82), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 77 (delta 56), reused 62 (delta 41), pack-reused 0
error: unable to create temporary file: Required key not available
fatal: failed to write object
fatal: unpack-objects failed
```

Any ideas on how to solve this?

**Comment by michalbednarski** [comment]
Could you try if `proot-distro login --no-sysvipc ubuntu` works?

**Comment by gustavomello9600** [comment]
> Could you try if `proot-distro login --no-sysvipc ubuntu` works?

The errors persist.

**Comment by ElDavoo** [comment]
I'm having the same issue. "Suddenly" makes me think about the recent Magisk v21.1 update.

**Comment by xeffyr** [comment]
Closing as this is more general `proot` issue than one of `proot-distro` script.
