### ISSUE TITLE
Proot doe snot do proper host/port resolution.

### ISSUE THREAD

**Issue by trivigy** [termux/proot-distro#37]
When starting a server inside of ubuntu, seems like port forwarding is not working. If I start same server in termux then it does. Using some low-ish ports like `8000` and `localhost` as hostname. Would greatly appreciate some advice.

**Comment by WMCB-Tech** [comment]
use `--fix-low-ports` option in proot-distro

**Comment by trivigy** [comment]
Ahhhhh... Thank you for the comment. Figured out what the problem was though. Had nothing to do with ports. Was running `mdbook serve` from the inside and mdbook was listening to `localhost` by default which from the inside of the chroot didn't seem to bind to the right interfact. Changing `localhost` to `::` as a parameter for the hostname seem to do the trick.

Trial and error till it works!
