### ISSUE TITLE
[Attention]: Sylirre has/(Decided) to/Got Returned/Remains from Termux (with Termux X11)

### ISSUE THREAD

**Issue by BBCByComcast** [termux/proot-distro#371]
### Problem description

======== ATTENTION NOTES ========
in Now Year, Sylirre has Kill Twaik And Most 2019-2022 Termux GitHub/GitLab User And It's Modifying Termux (with Termux X11 And Termux Repo) Over Twaik Modifying Termux (with Termux X11 And Termux Repo) , Most 2015-2018 Termux GitHub/GitLab User Will Return with New User: TomJo2000, AngelJo2000, JerryJo2000, NibblesJo2000, HankJo2000 And BenJo2000, Over Twaik Modifed Termux, Thanks for Twaik....

### What steps will reproduce the bug?

_Nothing_

### What is the expected behavior?

_Nothing_

**Comment by TomJo2000** [comment]
Pardon my french.

What the fuck are you talking about?

**Comment by twaik** [comment]
Wtf...

**Comment by twaik** [comment]
@BBCByComcast Are you high or something?

**Comment by BBCByComcast** [comment]
> @BBCByComcast Are you high or something?

Come On Twaik, It's Saw That: https://github.com/termux/proot-distro/issues/370
Sylirre has Return And Decided to Close My Issues Then Sylirre Say "I always wondered: are people asking for distribution due to fancy screenshots or they really tried it themselves and think it is a good addition"
That Could Be....... Be...... in a Activity........ https://github.com/termux/proot-distro/activity
Thanks...... Must...... Be....... Twaik..........

**Comment by twaik** [comment]
I still don't see how I am involved with this...

**Comment by BBCByComcast** [comment]
> Pardon my french.
> 
> What the fuck are you talking about?

Pardon Not Your French, Do Not Say F**K Because It's Must Be Good, However I Talking About Sylirre Returns/Remains Attention, Also Sylirre Won't Return Termux GitHub/GitLab Activity Everyday So For Lore, Check My First Comment Instead

**Comment by BBCByComcast** [comment]
> I still don't see how I am involved with this...

Just Scroll Down And You See, a Sylirre has Here If You Say I Still Don't See

**Comment by twaik** [comment]
How the fuck am I related to this?

**Comment by BBCByComcast** [comment]
> How the fuck am I related to this?

@twaik Are You Deaf People/User, Just Check My First Comment And You See My Rules Instead Also Related to That Can True About Sylirre Returns/Remains

**Comment by BBCByComcast** [comment]
@TomJo2000 Did You Fork a Termux Packages, I Saw it: https://github.com/TomJo2000/termux-packages-prs
That Strange Nicely Bruh

**Comment by twaik** [comment]
There are 2 options.
1. You are high.
2. Your translate program is bad. Your messages contain words, but they do not contain any piece of sence.

**Comment by TomJo2000** [comment]
> Pardon Not Your French, Do Not Say F**K Because It's Must Be Good, However I Talking About Sylirre Returns/Remains Attention, Also Sylirre Won't Return Termux GitHub/GitLab Activity Everyday So For Lore, Check My First Comment Instead

Syrlirre, Twaik and I are entirely separate people.
You made a distro request without doing due diligence to verify that the ARM images are still maintained.
I am not blaming you for this.

**Comment by BBCByComcast** [comment]
Also @twaik Your Profile Picture That Look Like....
![9674930](https://github.com/termux/proot-distro/assets/137778363/062d84ad-1a28-4be2-8159-5635b0abeb11)
Is That Weird Cat or Weird User, However @TomJo2000 has Also Fork a Termux Packages Too, Exactly Am I Being Clowns for My Deleted Issues

**Comment by BBCByComcast** [comment]
> > Pardon Not Your French, Do Not Say F**K Because It's Must Be Good, However I Talking About Sylirre Returns/Remains Attention, Also Sylirre Won't Return Termux GitHub/GitLab Activity Everyday So For Lore, Check My First Comment Instead
> 
> Syrlirre, Twaik and I are entirely separate people. You made a distro request without doing due diligence to verify that the ARM images are still maintained. I am not blaming you for this.

Really, Am I Seperate People, Also Artix Linux has Maintained ARM64/ARM/i386 Images Too

**Comment by twaik** [comment]
Try to use Google translate. All your messages have no any piece of sence.

**Comment by TomJo2000** [comment]
> @TomJo2000 Did You Fork a Termux Packages, I Saw it: https://github.com/TomJo2000/termux-packages-prs
> That Strange Nicely Bruh

I have a personal development branch of Termux Packages which I keep up to date with the mainline package repository for the purpose of working on package requests.
This is standard practice for contributing.

It is not meant to act as a fork, all contributions made to it are made with the goal of being merged into the upstream termux/termux-packages repo.

**Comment by BBCByComcast** [comment]
> There are 2 options.
> 
> 1. You are high.
> 2. Your translate program is bad. Your messages contain words, but they do not contain any piece of sence.

My Answer Options

1. I am Not High, Why Are You Do That?
2. My Translation Program has Just a Good, Are You Typo or Autocorrect?

**Comment by twaik** [comment]
> My Translation Program has Just a Good, Are You Typo or Autocorrect?

It is not good.

**Comment by BBCByComcast** [comment]
> Try to use Google translate. All your messages have no any piece of sence.

However What About Duolingo, I Ask You Guys About Duolingo Here:
What About Duolingo: Duolingo is an American educational technology company that produces learning apps and provides language certification, with provides language and music certificate then music, Duolingo App has only phone and tablet then Duolingo App won't launch in PC And Laptop Because of that, at Least That a UWP/WinUI Apps Instead

Did William Caza Like Duolingo Channel: Exactly Duolingo Channel has Here so William Caza like Duolingo Channel Instead And Inducing More Language, Secret Channel has The Amazing Digital Circus And Skibidi Toliet Be Like Thought It's Think That a Bad Language And Decided to Use Duolingo Instead

**Comment by TomJo2000** [comment]
> Also @twaik Your Profile Picture That Look Like....
> Is That Weird Cat or Weird User, However @TomJo2000 has Also Fork a Termux Packages Too, Exactly Am I Being Clowns for My Deleted Issues

You are not being punished for any issues you have submitted.
However, continued incoherent rambling is liable to get you blocked from contributing to the various Termux projects.

**Comment by twaik** [comment]
Whatever you use, use something else because **all your messages have no sence.**

**Comment by Maxython** [comment]
Interesting circus 🍿

**Comment by BBCByComcast** [comment]
> > Also @twaik Your Profile Picture That Look Like....
> > Is That Weird Cat or Weird User, However @TomJo2000 has Also Fork a Termux Packages Too, Exactly Am I Being Clowns for My Deleted Issues
> 
> You are not being punished for any issues you have submitted. However, continued incoherent rambling is liable to get you blocked from contributing to the various Termux projects.

Don't Worry, If I Got Blocked for Contribution to Various Termux Project, We Have Create GitLab Account Before......
![Screenshot_2023-11-22-19-35-40-96_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/termux/proot-distro/assets/137778363/a171784e-3dbb-4a4b-91ee-6b5acaa6bb84)

**Comment by BBCByComcast** [comment]
> Interesting circus 🍿

![kmc_20231122_194433](https://github.com/termux/proot-distro/assets/137778363/8c8583c9-ae04-46e0-a12c-683bebc1cea8)

**Comment by BBCByComcast** [comment]
> Whatever you use, use something else because **all your messages have no sence.**

Nevermind, I Give Up is That Instead So **All Your Messages Have No Scene Too**

**Comment by twaik** [comment]
Scene?

**Comment by twaik** [comment]
I have no fucking idea. As far as I understand he uses some kind of translater program (possibly Duolingo) but it produces some nonsence instead of normal sentences.

**Comment by BBCByComcast** [comment]
> Scene?

Bruh, However I Send The Amazing Digital Circus Picture to Maxython Say "Interesting Circus"
And I Have One More Forgot About That Attention, Most 2015-2018 Termux GitHub/GitLab User Will Return with New User: TomJo2000, AngelJo2000, JerryJo2000, NibblesJo2000, HankJo2000, UrNightmare And BenJo2000 Then UrDaytime

**Comment by UrNightmaree** [comment]
> I have no fucking idea. As far as I understand he uses some kind of translater program (possibly Duolingo) but it produces some nonsence instead of normal sentences.

We need to contact maintainers in termux/dev room, this nonsense has driven us crazy.

**Comment by BBCByComcast** [comment]
> I have no fucking idea. As far as I understand he uses some kind of translater program (possibly Duolingo) but it produces some nonsence instead of normal sentences.

However These Duolingo Mascot Are Great with Duo Instead (So That a Duolingo Birds LOL)
![Duo_2019](https://github.com/termux/proot-distro/assets/137778363/37d67f8e-6569-4cae-aa99-8841a9cbe296)
