### ISSUE TITLE
Add Configurable Bind Mounts (proot's -b option)

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#39]
Hello, i have an suggestion if it's okay to add Configurable Bind Mounts to `proot-distro`

So i could easily access files or relocate files/folders and bind fake proc files which is useful for some programs (proot's `-b` or `--bind` option implementation im `proot-distro`)

*This issue is edited as to avoid useless/duplicate redundancies*

**Comment by WMCB-Tech** [comment]
I've just realized that bind mounts in proot-distro would be customizable and allows users to bind their own files/folders

**Comment by xeffyr** [comment]
> user can bind mount termux home directory to user's home directory if user account is created

Option `--termux-home`.

**Comment by WMCB-Tech** [comment]
I guess the issue that i made was implemented after all 😅 (fake proc loadavg/vmstat/uptime)

But i would say it would still be useful to bind mount such things like mounting webserver documentroot

**Comment by xeffyr** [comment]
`--bind` will be available in v1.3.
