### ISSUE TITLE
" You should not use command 'apt' as root."

### ISSUE THREAD

**Issue by sudomain** [termux/proot-distro#4]
This might be better suited for termux-packages, but running any apt command as a "root" user results in this warning:

` [root@localhost home]# apt
You should not use command 'apt' as root.
This is dangerous as may damage your Termux installation and data.`

I imagine that this warning is for people with rooted devices, but is this any actual danger of using it within a PRoot? If there is no danger, is there a way of bypassing the warning? My hacky solution is to have an alias of:
`su -c 'apt update' alarm`

to run it as an user not named "root"

**Comment by xeffyr** [comment]
> is there a way of bypassing the warning?

The purpose of this warning is to block all attempts and whatever existing scripts from running `apt` as root, with no way to bypass.

Apt checks the return value of `getuid()` syscall, if it is `0` then it assumes that running as root.
