### ISSUE TITLE
[Distribution]:freebsd

### ISSUE THREAD

**Issue by Lowertricker** [termux/proot-distro#414]
### Description

Freebsd is the best distro i wanted to run katana desktop environment and run things

### Home page URL

https://www.freebsd.org/

### Root file system archive URL

I don't have :(

### Does 64bit ARM builds available (arm64, aarch64)?

- [X] Yes, distribution provides 64 bit images.

**Comment by twaik** [comment]
Proot-distro can run only distros that are built on top of Linux kernel. Freebsd has its own kernel. It is not possible to run it in proot-distro.
