### ISSUE TITLE
does launch script contain sysvipc option by default?

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/proot-distro#42]
Dear specialists,
DO you plan sysvipc Proot option as A default choice for all launching scripts of yours package, which are capable to launch installed Linux distributions?
Or did you added this feature only for unstable Termux scripts repo for now?
If you are waiting and if you are performing some development tests. Can I help you while participating in such Proot tests? If those tests are based on executing scripts or by typing commands, I AM really prepared to debug and test with you.
I can confirm, that introduced sysvipc option really do not cause stability issues. No extra hundred of MBS memory allocations, no Termux auto termination or even mate-session crashes are not presented.
Because I Am running Orca, complex Python program which intensively communicates with many .so libraryes, I think, that intensive work with this screen reader can be very useful to confirm new sysvipc extension stability.
I want to do something very useful also for you, advanced programmers here. Because I know, that I AM sometimes overloading you by my complex pleas such as adding shared memory support.
But really, it work like A charm! GTK3 library do not report shmget function not implemented error, also other apps do not report errors related to added shared memory functions.
So thank you very very much for yours tips how to help you testing, if is it necessary.

**Comment by xeffyr** [comment]
Yes, sysvipc is enabled by default.
