### ISSUE TITLE
[Distribution]: Rhel and fedora 40

### ISSUE THREAD

**Issue by Lowertricker** [termux/proot-distro#425]
### Description

Fedora 39 is kinda not outdated but i hope it can upgrade to 40 in the other hand rhel is good

### Home page URL

Fedoraproject.org(fedora) www.redhat.com(rhel)

### Root file system archive URL

I don't have :(

### Does 64bit ARM builds available (arm64, aarch64)?

- [x] Yes, distribution provides 64 bit images.

**Comment by zavocc** [comment]
RHEL is a commercial enterprise product, not worth adding

**Comment by Lowertricker** [comment]
Im opening this
For fedora 40

**Comment by Lowertricker** [comment]
Im opening this for fedora 40

**Comment by Lowertricker** [comment]
Ok
