### ISSUE TITLE
[Bug]: Custom Working Directory

### ISSUE THREAD

**Issue by liuzhongyi2** [termux/proot-distro#432]
### Problem description

Custom Working Directory bug，Using adb in "/storage/emulated/" New folder

### What steps will reproduce the bug?

```bash
~ $ pd sh alpine --work-dir /storage/emulated/dmfyq
proot warning: can't chdir("/storage/emulated/dmfyq/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
localhost:/# exit
~ $ ls /storage/emulated/dmfyq/
代码树.py
~ $
```

**Comment by twaik** [comment]
proot-distro behaviour is correct. Custom working directory specifies directory inside a container, not outside of it.
