### ISSUE TITLE
[Feature]: Auto set arch when login

### ISSUE THREAD

**Issue by NoNameWasDefined** [termux/proot-distro#441]
### Feature description

When installing a distro we can specify the architecture to download with `DISTRO_ARCH` like this :

> DISTRO_ARCH=x86_64 proot-distro install debian

But if we do :

> proot-distro login debian

it won't work.

Is it possible to automatically choose architecture when login ?
Also can the `DISTRO_ARCH` variable be replaced with an option argument like `-arch` ç

**Comment by Biswa96** [comment]
> Is it possible to automatically choose architecture when login ?

How would the proot-distro script choose the arch if DISTRO_ARCH is not specified?

**Comment by NoNameWasDefined** [comment]
> > Is it possible to automatically choose architecture when login ?
> 
> How would the proot-distro script choose the arch if DISTRO_ARCH is not specified?

I said that won't work but the question was about setting it automatically.

**Comment by Biswa96** [comment]
Imagine there are two Debian distro installed with different architecture. How can proot-distro choose it automatically if the user does not specify any?

**Comment by NoNameWasDefined** [comment]
I wasn't talking about selecting distro automatically, sorry for the misunderstanding, the problem is that `proot-distro` doesn't choose the good architecture when login in a distro that isn't compatible with your actual architecture (QEMU).

**Comment by NoNameWasDefined** [comment]
When the release date ?
It isn't important.

**Comment by Biswa96** [comment]
It is already in the apt repository https://packages.termux.dev/apt/termux-main/pool/main/p/proot-distro/

**Comment by NoNameWasDefined** [comment]
It isn't documented yet.

**Comment by NoNameWasDefined** [comment]
But i'm happy to see the developpers staying active.

**Comment by NoNameWasDefined** [comment]
I see it in the code.
These checks shouldn't slow down the login ?
