### ISSUE TITLE
[Bug]: update-locale: Error: invalid locale settings:  LANG=en_US.UTF-8

### ISSUE THREAD

**Issue by pikriawan** [termux/proot-distro#448]
### Problem description

Generating locales (this might take a while)...
  en_US.UTF-8...E2024-09-14T11:32:01.377376:blink/memorymalloc.c:974:28327 mmap(virt=40143b1000, size=4096, flags=0x1, fd=4, offset=0xfd47000) crisis: ENOMEM
unrecoverable mmap() crisis: see log for further details
 done
Generation complete.
*** update-locale: Error: invalid locale settings:  LANG=en_US.UTF-8

### What steps will reproduce the bug?

Install a distribution with proot-distro with blink as emulator
```bash
export PROOT_DISTRO_X64_EMULATOR=BLINK
DISTRO_ARCH=x86_64 proot-distro install debian
```

**Comment by Biswa96** [comment]
ENOMEM error means that there is not enough space or memory to be allocated.
