### ISSUE TITLE
[Feature Request] Verify the tarball after downloading

### ISSUE THREAD

**Issue by sainnhe** [termux/proot-distro#45]
https://github.com/termux/proot-distro/blob/ff9f3198c982fbec21bf4799750669fe38bc76a3/proot-distro.sh#L276-L307

So the script extracts the tarball after downloading with no verification, I'd suggest verifying it after downloading.

This step is also recommended in the installation guide of most of the distros (e.g. [arch linux](https://wiki.archlinux.org/index.php/Installation_guide#Verify_signature)).

**Comment by xeffyr** [comment]
This feature is now available in git version and will be a part of v1.3 release.

**Comment by sainnhe** [comment]
Thanks!
