### ISSUE TITLE
[General]: Ubuntu Noble - 24.04 - Blender has faults

### ISSUE THREAD

**Issue by anonimo82** [termux/proot-distro#462]
### Description

Hello everyone.
I tried various ways to run Blender with Zink/Virpipe/Llvm, no luck.
Please note I'm using the official repository for installation.
If I run it with no hardware acceleration, it starts no problem, but is really slow.
Otherwise, I get a segmentation fault and a crash dump file, with the following content:

```
# Blender 4.0.2, Unknown revision

# backtrace
blender(+0xa21c20) [0x3000a21c20]
blender(+0x7084f4) [0x30007084f4]
[0x707f305678]
blender(+0xaa5634) [0x3000aa5634]
blender(+0xa76760) [0x3000a76760]
blender(+0xa783dc) [0x3000a783dc]
blender(+0xa8dd28) [0x3000a8dd28]
blender(+0x6ad998) [0x30006ad998]
/lib/aarch64-linux-gnu/libc.so.6(+0x284c4) [0x70797184c4]
/lib/aarch64-linux-gnu/libc.so.6(__libc_start_main+0x98) [0x7079718598]
blender(+0x6f86b0) [0x30006f86b0]

# Python backtrace

```

Please, can anyone help me with this?
Thanks in advance for any help.

Regards, have a nice day.

**Comment by twaik** [comment]
You ignored this sign.
![image](https://github.com/user-attachments/assets/eec95860-0a99-4a93-9482-bf3243d8ea68)

**Comment by anonimo82** [comment]
Whoops, excuse me. Truly.

**Comment by anonimo82** [comment]
Please, can you suggest me some place I can go to?

**Comment by twaik** [comment]
No.
