### ISSUE TITLE
Termux dir

### ISSUE THREAD

**Issue by op30mmd** [termux/proot-distro#463]
### Description

I ran into a problem, the pygame installs in termux dir itself but python can't find it.

`root@localhost:~# pip3 install pygame                                                   Collecting pygame
  Using cached pygame-2.6.1.tar.gz (14.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pygame
  Building wheel for pygame (pyproject.toml) ... done
  Created wheel for pygame: filename=pygame-2.6.1-cp312-cp312-linux_aarch64.whl size=9898266 sha256=557c084f42fc75d3a556b603465ca3b77a3ad55b246b82851c0edd0dfe503a30
  Stored in directory: /data/data/com.termux/cache/pip/wheels/83/7f/24/092550a10c1088c21479539f331d6838354a73475fa621ef72
Successfully built pygame
Installing collected packages: pygame
Successfully installed pygame-2.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
root@localhost:~# python3 webgame.py &
[1] 6399
root@localhost:~# Traceback (most recent call last):
  File "/root/webgame.py", line 2, in <module>
    import pygame
ModuleNotFoundError: No module named 'pygame'
^C
[1]+  Exit 1                  python3 webgame.py`

**Comment by twaik** [comment]
Use `pkg install python-pygame`.

**Comment by twaik** [comment]
Oh, that is proot-distro.
Run proot-distro in isolated mode and then try to install pygame.
