### ISSUE TITLE
[General]: Question about Arch Linux

### ISSUE THREAD

**Issue by sheesh3178** [termux/proot-distro#470]
### Description

It says "Arch Linux ARM" in the "supported distributions" section, so does that mean it supports both AArach64 (arm64-v8a) and armeabi (armeabi-v7a) or does it only support the latter? My phone supports AArch64 and I don't want the armeabi because it's gonna be slower.

**Comment by Biswa96** [comment]
There are both AArch64 and ARM versions of ArchLinux https://github.com/termux/proot-distro/blob/master/distro-plugins/archlinux.sh

By default, proot-distro installs distro similar as native system CPU architecture, here AArch64.

**Comment by sheesh3178** [comment]
> There are both AArch64 and ARM versions of ArchLinux https://github.com/termux/proot-distro/blob/master/distro-plugins/archlinux.sh
> 
> By default, proot-distro installs distro similar as native system CPU architecture, here AArch64.

Thank you! I get it now.
