### ISSUE TITLE
Add multi-architectural support

### ISSUE THREAD

**Issue by ZhymabekRoman** [termux/proot-distro#48]
Please add support for different architectures by using QEMU

**Comment by WMCB-Tech** [comment]
Cool, i like it. but I'm not sure on how usable is proot-distro + qemu because i lost motivation

**Comment by ZhymabekRoman** [comment]
> I like it. but I'm not sure on how usable is proot-distro + qemu because i lost motivation when using it, probably just to run wine

@WMCB-Tech, I agree that QEMU is very slow, it would be better to screw box86 together with proot.

**Comment by xeffyr** [comment]
That's not supported by design and qemu-user is not that stable anyway.

**Comment by kadrim** [comment]
i have a rare case wher a proprietary i386 binary would be run. So i tweaked the scripts a little bit, to allow passing the `-q` parameter.

Nothing special here, my main intent was simplicity and full compatibility with the existing plugins.

This most probably won't work with wine or stuff like that.

Simple i386 binaries can be executed this way, even graphical ones.

To get GUI working, the best way would be to run the xserver on termux and only run the different-arch binary on the new emulated proot.


Allow the xserver (i.e. vncserver) to be accessed locally, set your `DISPLAY` variable accordingly,
```bash
vncserver
export DISPLAY=":1"
pkg install xorg-xhost
xhost +local:
```

Start the proot with access to the shared /tmp directory:

```bash
proot-distro login --shared-tmp ubuntu-18.04-qemu
```

Within the proot, install xterm and set `DISPLAY` to run it:

```bash
apt update
apt install xterm
export DISPLAY=":1"
xterm &
```

It will look a little bit like this:

![termux-proot-distro-qemu](https://user-images.githubusercontent.com/8304331/103158726-45308500-47c1-11eb-945e-5db56e2a41c0.jpg)

**Comment by Jc-sims** [comment]
I have had the same issue. There are dependencies missing  from many of the cloned repositories.  My best  result was to install both the supplemental  x11 repo....look for it on the explore screen. Also arch linux distro givesba better result.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kadrim** [comment]
Yepp. Arch will in most cases work better.

I just added ubuntu as a reference in my pull request.

The whole idea is to enable anyone to write a custom plugin for qemu without too much hassle

**Comment by xeffyr** [comment]
Support for QEMU is added in version 1.4.0. You will just need to set variable `DISTRO_ARCH` to some custom value, for example `i686` and QEMU will be used automatically.
``` .bash
...
# Default value is set by proot-distro script and is equal
# to the CPU architecture of your device (uname -m).
#DISTRO_ARCH=$(uname -m)

#!!!
DISTRO_ARCH=i686

# Returns download URL and SHA-256 of file in this format:
# SHA-256|FILE-NAME
get_download_url() {
	local rootfs
	local sha256

	case "$DISTRO_ARCH" in
...
```

![Screenshot_20201228-175644_Termux](https://user-images.githubusercontent.com/25881154/103227317-bc3b5a00-4936-11eb-8bb7-883c72c7862f.png)

**Comment by WMCB-Tech** [comment]
Thanks, but the only issue that i encountered is sudo, that gives me errors about this
```
❯ proot-distro login ubuntu-18.04 --user marcusz
marcusz@localhost:~$ /usr/bin/sudo                         sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
marcusz@localhost:~$
```

My only workaround is to symlink fakeroot as sudo but when Installing some programs, it would give me some errors like group errors

**Comment by ZhymabekRoman** [comment]
> Thanks, but the only issue that i encountered is sudo, that gives me errors about this even with correct permissions

Hello, i have about the same problem, but I don't use QEMU
```
root@localhost:~/mesa-20.3.1/build# /usr/bin/sudo
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be only be writable by owner
sudo: fatal error, unable to load plugins
root@localhost:~/mesa-20.3.1/build#
```

As a temporary solution, you can set an empty alias for the sudo command

**Comment by kadrim** [comment]
this is most probably not connected to this change.

best would be to create a new issue i think. i will have a look at this tonight.

**Comment by xeffyr** [comment]
@WMCB-Tech @ZhymabekRoman `qemu` user-mode is **unstable** and that's unfixable. https://github.com/termux/proot-distro/issues/48#issuecomment-743738627

**Comment by xeffyr** [comment]
@WMCB-Tech Have you used a backup-restore feature? What's `ls -l /usr/bin/sudo` ?

**Comment by WMCB-Tech** [comment]
@xeffyr no, when using qemu feature in the first place

**Comment by xeffyr** [comment]
Ok, then perhaps in your case is `qemu` and in case of @ZhymabekRoman something else. Backup-restore feature of v1.3 really broke permissions of setuid executables, but that behavior was fixed (feature, not already made backups) in newer versions.

**Comment by kadrim** [comment]
so, the case of @WMCB-Tech is really qemu related, as the issue is reproducable but most probably not fixable.

with i686 emulation i get:

```bash
~ $ proot-distro login ubuntu-18.04-i686
root@localhost:~# ls -al /usr/bin/sudo
-rwsr-xr-x. 1 root root 172120 Sep 23 14:59 /usr/bin/sudo
root@localhost:~# exit
logout
~ $ proot-distro login ubuntu-18.04-i686 --user david
$ ls -al /usr/bin/sudo
-rwsr-xr-x. 1 david david 172120 Sep 23 14:59 /usr/bin/sudo
```

and with aarch64 (host) i get:

```bash
~ $ proot-distro login ubuntu-18.04
root@localhost:~# ls -al /usr/bin/sudo
-rwsr-xr-x. 1 root root 136616 Sep 23 14:59 /usr/bin/sudo
root@localhost:~# exit
logout
~ $ proot-distro login ubuntu-18.04 --user david
$ ls -al /usr/bin/sudo
-rwsr-xr-x. 1 david david 136616 Sep 23 14:59 /usr/bin/sudo
```

maybe this will be fixed someday in proot (upstream).

**Comment by xeffyr** [comment]
Under proot `sudo` should work when access mode is `-rwsr-xr-x` regardless of the ownership. Normally it should work same in cases with and without QEMU.

Here is what how it should work normally:
![Screenshot_20201229-194815_Termux](https://user-images.githubusercontent.com/25881154/103303599-06900a00-4a0f-11eb-90a7-ccca64ce3699.png)

Open a new issue in https://github.com/termux/proot, maybe issue is not with QEMU but rather with way how `proot` deals with it.

**Comment by ZhymabekRoman** [comment]
> Ok, then perhaps in your case is `qemu` and in case of @ZhymabekRoman something else. Backup-restore feature of v1.3 really broke permissions of setuid executables, but that behavior was fixed (feature, not already made backups) in newer versions.

I just tried to install Ubuntu 20.04 - and sudo team works great. I have my Ubuntu 20.04 long installed in proot-distro, and it seems that during my excrement I accidentally ruined the distribution. But I had a small problem - during the clean installation of the distribution, he did not have a sudo command, and because of which he began to immediately execute the sudo command from the tsu package, which is installed in Termux, but he did not want to execute, still it is adapted for Android. Is it possible to exclude the sudo command from the tsu package on the proot system?

**Comment by xeffyr** [comment]
> Is it possible to exclude the sudo command from the tsu package on the proot system?

To exclude it all files will have to be bind-mounted individually. This won't be done.

One of the solutions is to preinstall `sudo` when running `proot-distro install <xyz>`.

**Comment by maximumsomething** [comment]
Is there a way to run a 32-bit distro on a 64-bit phone without qemu? Adding `DISTRO_ARCH=arm` results in `Error: package 'qemu-user-arm' is not installed.`

**Comment by suhan-paradkar** [comment]
As it says, install `qemu-user-arm`

**Comment by maximumsomething** [comment]
I don't want to use qemu. The CPU can natively run 32-bit code.

**Comment by Pedro1234-code** [comment]
Comment the DISTRO_ARCH=arm line

**Comment by maximumsomething** [comment]
@Pedro1234-code I wanted to run a 32-bit distro, so I need DISTRO_ARCH=arm.

For anyone coming across this via google, it was fairly easy to comment out the qemu code from the proot_distro shell script. Just do ./proot-distro-noqemu login <your distro>

[proot-distro-noqemu.gz](https://github.com/termux/proot-distro/files/7156734/proot-distro-noqemu.gz)

This should be a builtin option in proot-distro, in my opinion.

**Comment by xeffyr** [comment]
v2.6.0 now runs 32bit distributions natively (i.e. no qemu), if your CPU and Termux installation are 64 bit.
