### ISSUE TITLE
[Bug]: "manjaro-xfce-settings" package missing. (Only in PRoot-Distro)

### ISSUE THREAD

**Issue by Anemosfy** [termux/proot-distro#480]
### Problem description

I tried to download the manjaro-xfce-settings package in proot-distro manjaro. But its showing theres no packages called it. I have manjaro installed in my pc, and manjaro-xfce-settings exist there. Btw i know how to download manjaro-xfce-settings manually. But manually downloading is surely not perfect. 

So my request is to add the package is PRoot-Distro manjaro or if it is bug plz just fix it will help me a lot. Thank you

**Comment by twaik** [comment]
Related to distro, not to proot-distro itself.

**Comment by Biswa96** [comment]
The manjaro-xfce-settings package is not provided in manjaro arm according to this search https://manjaristas.org/branch_compare?q=manjaro-xfce

**Comment by Anemosfy** [comment]
> The manjaro-xfce-settings package is not provided in manjaro arm according to this search https://manjaristas.org/branch_compare?q=manjaro-xfce

So how the manjaro-xfce-settings provided for manjaro arm?

**Comment by Anemosfy** [comment]
> > So how the manjaro-xfce-settings provided for manjaro arm?
> 
> I have asked the question in `#Manjaro:matrix.org` channel and here is the answer: https://matrix.to/#/!XCQjvjqXtjqpDWsato:matrix.org/$VJpMaDWO94rohIEMm5x9Xfd69aQRhl-2V61d7-h41nM
> 
> > https://gitlab.manjaro.org/packages/extra/manjaro-xfce-settings
> > They are basically all text files for configuration. So the ARCHITECTURE is also ANY. It is easy to add your own. I just don't know why it is not included in the official repositories.
> 
> It seems that the package has to be built and installed manually.

tysm for help.
