### ISSUE TITLE
 Raspberry Pi OS

### ISSUE THREAD

**Issue by dylan14567** [termux/proot-distro#49]
could you add this distribution please.

**Comment by xeffyr** [comment]
Do you have at least links to disk image files?

**Comment by dylan14567** [comment]
I do not have, but in this link are the rootfs of the distribution: http://downloads.raspberrypi.org/raspbian_lite/archive/2020-02-14-13:49/

**Comment by WMCB-Tech** [comment]
Raspbian OS is only for ARM (or even ARM(32) only) i think, and would not be compatible with Intel Processors like Chromebooks

**Comment by xeffyr** [comment]
Btw, what's the actual reason to add Raspberry Pi OS?

**Comment by dylan14567** [comment]
![67d8fcc5b2796665a45f61a2e8a5bb7f10cdd3f5_raspberry-pi-3-1-1619x1080](https://user-images.githubusercontent.com/55631040/102558679-fdf91480-409b-11eb-8108-8b77a6f4a99c.jpg)

the reason I want to add Raspberry Pi is to program these Raspberry Pi 3 Model B cards, and other people may want to use the Raspberry Pi operating system, to program those cards or microcontrollers or Raspberry Pi 3 Model B

**Comment by ZhymabekRoman** [comment]
What is the point of adding RaspbianOS when there is Debian in proot-distro?  After all, RaspbianOS, if I'm not mistaken, is based on Debian. And if you want a program from RaspbianOS, then I think it will be enough to put RaspbianOS repositories in the sources.list file, but I doubt that they will work

**Comment by xeffyr** [comment]
I'm more curious about
> I want to add Raspberry Pi is to program these Raspberry Pi 3 Model B cards

because `proot-distro` will not enable access to specific hardware.

If just need packages, then adding a repository to sources.list should be enough. Otherwise, i.e. adding Raspberry Pi OS to attempt gain write access over USB is useless, note that official variant of `proot-distro` won't run under su/tsu/sudo.

**Comment by dylan14567** [comment]
I think it would be better to add it to sources.list
