### ISSUE TITLE
Support for Backup Linux Distros?

### ISSUE THREAD

**Issue by WMCB-Tech** [termux/proot-distro#5]
is there a way to backup linux distros in proot-distro? so if things go wrong i could rollback to the previous state. just like VM Snapshots. for example. if have development files inside the proot environment then install other stuff and cause the linux environment to be problematic (eg. compiling linux programs with `make`). or accidentally entered a wrong command then reset a distribution and then start over from scratch. it would be nice to add backup/snapshot feature

**Comment by michalbednarski** [comment]
Installed distros stay in `/data/data/com.termux/files/usr/var/lib/proot-distro/installed-rootfs` and you can use `tar` to archive them

**Comment by WMCB-Tech** [comment]
Ok thanks for your suggestion. so that's why I couldn't find installed Linux Distros
