### ISSUE TITLE
lxc on android 👀

### ISSUE THREAD

**Issue by SaicharanKandukuri** [termux/proot-distro#55]
When I tried to decompile Samsung linux on dex app file I found lxc*.so files in it
So
can we somehow run lxc in termux like Samsung did in its Linux on dex app?

**Comment by Grimler91** [comment]
lxc is available from the root repository, but requires custom kernel. Discussed in https://github.com/termux/termux-root-packages/issues/60#issuecomment-636619123 and https://github.com/termux/termux-root-packages/issues/199
