### ISSUE TITLE
emulating /dev/fuse to mount a remote filesystem via SSHFS?

### ISSUE THREAD

**Issue by sudomain** [termux/proot-distro#56]
I'm trying to mount a remote filesystem using sshfs (from Arch) but I get the following error:

`[root@localhost ~]# sshfs 192.168.0.18:/ /mnt/mymount/`
`fuse: failed to open /dev/fuse: Permission denied`

That makes sense, since being root inside of PRoot is not actually root. Is there a workaround such as changing a bind point or running in isolated mode?

**Comment by WMCB-Tech** [comment]
I don't think proot can emulate such fuse, but I'm not sure if it's possible to implement that, but this issue has the same reference here about [proot virtual mount](https://github.com/termux/proot/issues/61)

My Alternative is to connect my server with `mc` or for gui, i connect my remote server with gvfs (Nautilus/PCManFM)

But it lacks of cli interaction like sshfs

**Comment by xeffyr** [comment]
/dev/fuse is not a mount point and in general has nothing to do with mounting. That's a driver (more specifically, interface to interact with kernel) allowing programs to implement a user-space file systems.

This is neither subject for implementing in proot nor in `proot-distro` (`proot-distro` is a shell script wrapper around `proot`). Same goes to ANY kernel functionality.
