### ISSUE TITLE
QUESTION: Fake proc: when and how?

### ISSUE THREAD

**Issue by nathaneltitane** [termux/proot-distro#60]
I've gone through trying out proot-distro default installation method using ubuntu-20.04
From what I gather, the fake proc entries are written on configuration, but are they always loaded?

What are the cases in which the fake proc entries should be explicitly mounted?

**Comment by xeffyr** [comment]
In case if `proot-distro` found that `/proc/stat` and similar files [can't be read](https://github.com/termux/proot-distro/blob/master/proot-distro.sh#L1142), it will do a bind-mount to fake ones which are static and were obtained from Android device with not restricted `/proc`.

On typical devices, i.e. if your Android OS is stock and up-to-date, this will happen always.
