### ISSUE TITLE
pkg proot-distro can't locate the package

### ISSUE THREAD

**Issue by jopilote** [termux/proot-distro#61]
admittedly  it's on a Nexus 5 , Android 6.0.1 which is marginaly not supported my termux. 
but  i  installed  octave 5.1 without a glitch,   and many other  packages,  so maybe it's something easy to fix? 

>pkg install proot-distro
![image_2021-02-03_231823](https://user-images.githubusercontent.com/78507704/106810792-1b973300-6676-11eb-9770-78050ab00b12.png)

**Comment by xeffyr** [comment]
> admittedly it's on a Nexus 5 , Android 6.0.1 which is marginaly not supported my termux.

So why you're opening issue here? No support means: no packages & no issue fixes for unsupported Android versions.

P.S. `proot-distro` requires proot version with features (like SysV IPC) available only for Android 7+.

**Comment by jopilote** [comment]
True, thanks 
I thought something might be broken in locating packages. But apparently even if that was true it wouldn't help.
