### ISSUE TITLE
Not working on 32-bit cpu

### ISSUE THREAD

**Issue by Crafto1337** [termux/proot-distro#62]
When I try to install proot-distro it says:
`Uable to locate package proot-distro`. On Andronix I had a similar issuse, I coulnt install anything. But I know that there are 32-bit Linux distros

**Comment by WMCB-Tech** [comment]
Have you tried `pkg update` and try again? if you tried it and still not found, then possibly you have a unsupported legacy environment (Android 5/6)

---

> On Andronix I had a similar issuse, I coulnt install anything. But I know that there are 32-bit Linux distros

I couldn't actually tell what 32-bit you're saying (either Intel x86 or ARM
(hf)), some distros dropped support for i386 architectures

Could you post your device info with `termux-info` command

**Comment by xeffyr** [comment]
> Uable to locate package proot-distro

This is possible only on legacy environment. Nothing to do with 32 bit CPUs. That's a shell script finally, platform/architecture independent.

***

**I do not provide support for `legacy environment`. It is 2 years as dead.**
