### ISSUE TITLE
Add Manjaro

### ISSUE THREAD

**Issue by theDarkAlpha** [termux/proot-distro#63]

**Comment by a8underscore** [comment]
just use arch its basically the same thing

**Comment by theblobscp** [comment]
I want manjaro as well

**Comment by Yisus7u7** [comment]
I want delicacy manjaro

**Comment by layaachmad** [comment]
i want the manjaro linux!

**Comment by SaicharanKandukuri** [comment]
Bad news folks manjaro only supports `arm64` [ 64 Bit Only ] officially
Here rootfs link ( probably most people know this ) https://osdn.net/projects/manjaro-arm/storage/.rootfs/Manjaro-ARM-aarch64-latest.tar.gz

<hr>

# Building Your own rootfs
refer this repo https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools

- `arm` mean `arm64` so don't go too far

**Comment by SaicharanKandukuri** [comment]
> Bad news folks if you are on arm platform manjaro only supports `arm64` [ 64 Bit Only ] officially
> Here rootfs link ( probably most people know this ) https://osdn.net/projects/manjaro-arm/storage/.rootfs/Manjaro-ARM-aarch64-latest.tar.gz
> 
> # Building Your own rootfs
> refer to this repo https://gitlab.manjaro.org/manjaro-arm/applications/manjaro-arm-tools
> 
> * `arm` means `arm64` so don't go too far 😉

⚠️ using that rootfs may require some touches in `proot-distro` script

**Comment by SDRausty** [comment]
> Add Manjaro
> I want manjaro as well

https://github.com/TermuxArch/scripts.TermuxArch/blob/master/frags/manjaro.sh was contributed years ago;  Hopefully, it will aid the impatient out.

**Comment by theblobscp** [comment]
Nice self promote. But thanks

**Comment by SDRausty** [comment]
> Nice self promote. But thanks

Glad to have helped with what you are seeking!

**Comment by Yisus7u7** [comment]
Works in 32 bits?

**Comment by SDRausty** [comment]
>Works in 32 bits?

`grep gz scripts.TermuxArch/frags/manjaro.sh`
  

`manjaro_rootfs="https://osdn.net/projects/manjaro-arm/storage/.rootfs/Manjaro-ARM-aarch64-latest.tar.gz"`

**Comment by layaachmad** [comment]
> Works in 32 bits? 

Only works in aarch64/arm64

**Comment by Pedro1234-code** [comment]
Manjaro is arch-based. PRoot Distro only provides minimal command line experience only, so your experience with manjaro will né pratically the same as arch.

**Comment by rizkihrp** [comment]
https://github.com/infinyte7/manjaro-fs-arm64

try this one

**Comment by xeffyr** [comment]
Going to be available in v2.9.0.
