### ISSUE TITLE
Arch Linux man Segmentation fault

### ISSUE THREAD

**Issue by StringManolo** [termux/proot-distro#64]
man, throws a Segmentation fault when running it from Arch using fresh Arch Linux installed using the __proot distro install archlinux__ command. 

Here is the device:
```
  Operative System:      GNU/Linux
  Kernel Version:        5.4.0-faked
  CPU:                   Cortex-A53
  Architecture:          aarch64
  Vendor:                ARM
  CPU MAX MHz:           2189.0000
  CPU MIN MHz:           480.0000
  CPU Operation:         32-bit, 64-bit
  CPU Cores:             8
  RAM Total:             3.593
  RAM Available:         1.333
  Model:                 HUAWEI P40 lite E
  Version:               10.1.0.164C432
  Network Type:          LTE
  RIL(radio):            android infineon balong-ril 1.0
  Wi-fi Device Name:     HUAWEI_P40_lite_E-8f0096e
  DPI:                   272
  Timezone:              Europe/Madrid
  Board:                 ARTHTHD_L29_VA
  Platform:              kirin710
  Build Date:            Tue Dec 22 17,52,35 CST 2020
  Security Patch:        2020-10-01
  SDK Ver:               29
  SDK Min-Ver:           23
```

I updated the system running pacman -Syu afterwards and still.

**Comment by WMCB-Tech** [comment]
You may need to use archlinux's man if possible

![Screenshot_2021-02-23-17-22-41-00.jpg](https://user-images.githubusercontent.com/65075766/108823793-d1400c80-75b8-11eb-9744-603809cd2ff3.jpg)

**Comment by StringManolo** [comment]
> You may need to use archlinux's man if possible
> 
> ![Screenshot_2021-02-23-17-22-41-00.jpg](https://user-images.githubusercontent.com/65075766/108823793-d1400c80-75b8-11eb-9744-603809cd2ff3.jpg)
> 
> As proot-distro does execute host commands like WSL does

You right. **pacman -S man** selected 1° option and done :D
