### ISSUE TITLE
Alpine 3.13 seems to have brojen git

### ISSUE THREAD

**Issue by isodecryptor** [termux/proot-distro#65]
Btw, what an amazing software. I was running alpine 3.12 with proot-distro, flawlessly. But since your alpine upgrade, git wont fetch anything and i have not noticed a termux upgrade since i noticed the bug. Please consider looking into the new, git issue. Git complains about not finding some ca-certificates when uninstalling. Im assuming this new bug has something to do with that. If you could, at least, give us alpine 3.12 as an option in proot-distro, i feel that would be an awesome fix for now. Not to metion that version was the most complete version of linux, yet. Almost flawless in my opinion.

**Comment by WMCB-Tech** [comment]
Could you post output of the error and how to reproduce it? alpine git (latest) works fine to me

**Comment by isodecryptor** [comment]
Yes. This is on a fresh install. No root. It totally refuses to allow git
to work and it complains about missing ca-certificates. Thank you for your
time! I admire your project and have used it for streaming servers for the
android. Amazing. Please send me a link for donations and i will surely
donate.

**Comment by WMCB-Tech** [comment]
Git works fine to me with no ca-certificates error on a fresh alpine Installation

![Screenshot_2021-02-27-11-45-41-70.jpg](https://user-images.githubusercontent.com/65075766/109374572-50318f80-78ae-11eb-8fff-de087e981071.jpg)

Try reinstalling alpine again

**Comment by isodecryptor** [comment]
This same exact script installed the rtmp server, recently. This is the
output it now recieves. Sorry about any incovienance and ty for
considering.

**Comment by isodecryptor** [comment]
Im 100 percent certain that this script was working before the update. Im
very u sure why it would discriminate per device.

**Comment by xeffyr** [comment]
If you have issue with missing `ca-certificates`, then just install related package.

Hint:
```
apk add ca-certificates
```

Downgrading is a wontfix.
