### ISSUE TITLE
Alpine Login issue (bad file descriptor, su)

### ISSUE THREAD

**Issue by atahabaki** [termux/proot-distro#66]
I just recently tried to installed the `proot-distro` package, and afterwards I installed `alpine` by `proot-distro install alpine`, I can't login to the alpine, prints error about su, and here that is:

> su: can't set groups: Bad file descriptor

I don't know why this happened... Where should I look, and resolve the issue?

**Comment by WMCB-Tech** [comment]
Whilst i didn't get that error, can you run `proot-distro` with `PROOT_NO_SECCOMP=1`?

**Comment by atahabaki** [comment]
Connected, thanks. But where's that documented?

**Comment by WMCB-Tech** [comment]
It's a proot workaround for some devices, and should not be used by default

**Comment by atahabaki** [comment]
OK, got it. What's kind of problems can occur if I may use that as a default env?

**Comment by WMCB-Tech** [comment]
Seems something like that, and some function not implemented errors when logging in, although it's irreproducable for me as proot works fine on my device,

**Comment by xeffyr** [comment]
Closing as rather `proot` issue.

`proot-distro` is a bash script that only manages rootfs and automates `proot` usage.
