### ISSUE TITLE
Pacman-key error on freshly installed Arch Linux

### ISSUE THREAD

**Issue by atahabaki** [termux/proot-distro#67]
Hi, this is a great project I would like to see more linux distros on this... Anyway, I can reproduce the problem again so easily just by this 3 simple steps:

* pkg i proot-distro
* proot-distro install archlinux
* proot-distro login arch-linux

I would like to PR, but anyway here is what I have faced with. Thanx.

**Comment by atahabaki** [comment]
Due to #66 solves the login error, but i didn't see any documentation about it, so?

**Comment by WMCB-Tech** [comment]
proot may not have some documentation but you may look at the https://github.com/termux/proot/issues and https://proot-me.github.io/ and https://wiki.termux.com/wiki/PRoot
