### ISSUE TITLE
Ubuntu20 Su: Authentication failed

### ISSUE THREAD

**Issue by Saurabh030-ubuntulover** [termux/proot-distro#68]
I have added a user using command 
> adduser &&&
I have created an password 
But when I'm trying to get su permission it says like this
saurabh@localhost:~$ su
Password:
su: Authentication failure

Some where I have read that su is disabled by default 
And users suggest to use sudo instead of su.
But the problem is sudo is also not installed by default and to install sudo I need root permission..

**Comment by WMCB-Tech** [comment]
Login as root then set a password with the command `passwd root`

**Comment by Saurabh030-ubuntulover** [comment]
Thanks I was searching this error from past 1 week. Thank you for your quick response...
:)
