### ISSUE TITLE
Distribution downloaded URL is not defined for CPU architecture 'i686'. See screenshot.

### ISSUE THREAD

**Issue by divitechstudios** [termux/proot-distro#69]
![Screenshot 2021-03-01 175542](https://user-images.githubusercontent.com/78260149/109537915-5fcff480-7ab7-11eb-81b1-740717017ee1.png)

**Comment by divitechstudios** [comment]
ubuntu 18.04 works, but I would like to get 20.04 working

**Comment by divitechstudios** [comment]
Ok actually 18.04 doesn't work, it downloaded but gave me another error.
If it matters, I am on bluestacks as I'm testing it before I get a new phone.

**Comment by divitechstudios** [comment]
I just realised it's probably because bluestacks is x86, and I found a setting to change it to arm and now it's not loading and giving another error. So I will probably just try again when I actually get an android phone.

**Comment by xeffyr** [comment]
20.04 has dropped support for 32bit x86 CPUs, except some 32bit multilib packages as stated in https://ubuntu.com/blog/statement-on-32-bit-i386-packages-for-ubuntu-19-10-and-20-04-lts.
