### ISSUE TITLE
Error libfprint-2-2:armhf

### ISSUE THREAD

**Issue by Saurabh030-ubuntulover** [termux/proot-distro#70]
`Errors were encountered while processing:
 libfprint-2-2:armhf
 fprintd
 libpam-fprintd:armhf
E: Sub-process /usr/bin/dpkg returned an error code (1)`

Fixing command you have given is not working 
Its says file doesn't exist

> root@localhost:~# rm /var/lib/dpkg/info/libfprint0:*.postinst
rm: cannot remove '/var/lib/dpkg/info/libfprint0:*.postinst': No such file or directory

my device is armv81
![Screenshot_20210302-103339_Termux](https://user-images.githubusercontent.com/75117608/109600534-47a5b700-7b43-11eb-99c6-6eac0daa8433.jpg)

**Comment by WMCB-Tech** [comment]
Try:
```
install -m 755 /dev/null /usr/local/bin/udevadm
dpkg --configure -a
```

**Comment by ZhymabekRoman** [comment]
Try delete fprintd postinstall file. I just tried to install libfprint-2-2:armhf fprintd libpam-fprintd:armhf separately,for me they installs without any errors
```
rm /var/lib/dpkg/info/fprintd.postinst
dpkg --configure -a
```

**Comment by xeffyr** [comment]
In readme solution... https://github.com/termux/proot-distro#fixing-dpkg-errors
