### ISSUE TITLE
ArchLinux x86

### ISSUE THREAD

**Issue by bb942323** [termux/proot-distro#72]
### Please help me out
I am looking a workaround for installing archlinux x86. 
**rootfs** is available here, as **split tar.gz files**; [https://github.com/CypherpunkArmory/UserLAnd-Assets-Arch/tree/master/assets/x86/](https://github.com/CypherpunkArmory/UserLAnd-Assets-Arch/tree/master/assets/x86/)

Yeah, I have one of those legacy android devices with architecture **i686** which can run **i386** code.

**Comment by ilobilo** [comment]
Try this:
`https://github.com/SDRausty/termux-archlinux`
