### ISSUE TITLE
Non-root user with root privileges 

### ISSUE THREAD

**Issue by Newton-AA** [termux/proot-distro#73]
I create a test user and right from the start, it can look in /root and do root stuff. Is this a default behaviour of ubuntu18.04 in proot-distro?

**Comment by WMCB-Tech** [comment]
Yes, by default, you are in root shell

If you have created a user account and want to use it as default

Specify:
```
--user <username>
```

At your proot-distro launch parameters

**Comment by Newton-AA** [comment]
I did that but I have a non root user but it does apt without sudo

**Comment by Newton-AA** [comment]
the new user can do everything that root can do

**Comment by WMCB-Tech** [comment]
Intended behavior, due to the fact of files are being owned by termux, proot doesn't handle file ownership so you will expect that root operations as user will work like apt but dpkg still detects if running as root or not

**Comment by Newton-AA** [comment]
Oh thanks alot. I thought that you had to type sudo for all root operations
