### ISSUE TITLE
How to export files to termux

### ISSUE THREAD

**Issue by bvcbvc** [termux/proot-distro#75]
How do you export to termux, or how do you access it, I want to know

**Comment by bvcbvc** [comment]
If it stores the os in a directory it would like to know this directory

**Comment by WMCB-Tech** [comment]
Distros are living in:

`$PREFIX/var/lib/proot-distro/installed-rootfs`

**Comment by xeffyr** [comment]
Files can be exported into proot environment but not vice versa.

If you are looking just for proot-distro files location, then refer to https://github.com/termux/proot-distro/issues/75#issuecomment-817051390.
