### ISSUE TITLE
Plzzz help i am getting this issue .While installing Ubuntu on termux 

### ISSUE THREAD

**Issue by dompsi** [termux/proot-distro#77]
1. gdm3  2. lightdm
Default display manager: 1

Creating config file /etc/gdm3/greeter.dconf-defaults with new version
invoke-rc.d: could not determine current runlevel
 * Scheduling reload of GNOME Display Manager configuration gdm3                         [ OK ]
Setting up libfprint-2-2:arm64 (1:1.90.1+tod1-0ubuntu4) ...
Failed to scan devices: No such file or directory
dpkg: error processing package libfprint-2-2:arm64 (--configure):
 installed libfprint-2-2:arm64 package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of fprintd:
 fprintd depends on libfprint-2-2 (>= 1:1.90.1); however:
  Package libfprint-2-2:arm64 is not configured yet.

dpkg: error processing package fprintd (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of libpam-fprintd:arm64:
 libpam-fprintd:arm64 depends on fprintd (= 1.90.1-1ubuntu1); however:
  Package fprintd is not configured yet.

dpkg: error processing package libpam-fprintd:arm64 (--configure):
 dependency problems - leaving unconfigured
Processing triggers for dictionaries-common (1.28.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
aspell-autobuildhash: processing: en [en-common].
aspell-autobuildhash: processing: en [en-variant_0].
aspell-autobuildhash: processing: en [en-variant_1].
aspell-autobuildhash: processing: en [en-variant_2].
aspell-autobuildhash: processing: en [en-w_accents-only].
aspell-autobuildhash: processing: en [en-wo_accents-only].
aspell-autobuildhash: processing: en [en_AU-variant_0].
aspell-autobuildhash: processing: en [en_AU-variant_1].
aspell-autobuildhash: processing: en [en_AU-w_accents-only].
aspell-autobuildhash: processing: en [en_AU-wo_accents-only].
aspell-autobuildhash: processing: en [en_CA-variant_0].
aspell-autobuildhash: processing: en [en_CA-variant_1].
aspell-autobuildhash: processing: en [en_CA-w_accents-only].
aspell-autobuildhash: processing: en [en_CA-wo_accents-only].
aspell-autobuildhash: processing: en [en_GB-ise-w_accents-only].
aspell-autobuildhash: processing: en [en_GB-ise-wo_accents-only].
aspell-autobuildhash: processing: en [en_GB-ize-w_accents-only].
aspell-autobuildhash: processing: en [en_GB-ize-wo_accents-only].
aspell-autobuildhash: processing: en [en_GB-variant_0].
aspell-autobuildhash: processing: en [en_GB-variant_1].
aspell-autobuildhash: processing: en [en_US-w_accents-only].
aspell-autobuildhash: processing: en [en_US-wo_accents-only].
Processing triggers for libc-bin (2.31-0ubuntu9) ...
Processing triggers for systemd (245.4-4ubuntu3) ...
Processing triggers for rygel (0.38.3-1ubuntu1) ...
Processing triggers for libgdk-pixbuf2.0-0:arm64 (2.40.0+dfsg-3) ...
Processing triggers for dbus (1.12.16-2ubuntu2) ...
Processing triggers for sgml-base (1.29.1) ...
Setting up sgml-data (2.0.11) ...
Processing triggers for sgml-base (1.29.1) ...
Setting up docbook-xml (4.5-9) ...
Processing triggers for sgml-base (1.29.1) ...
Errors were encountered while processing:
 libfprint-2-2:arm64
 fprintd
 libpam-fprintd:arm64

**Comment by WMCB-Tech** [comment]
You could do
```
rm -rf /var/lib/dpkg/info/libfprint*.postinst
dpkg --configure -a
```

See if it helps

**Comment by dompsi** [comment]
Thank you 😀 its working
