### ISSUE TITLE
How To Install Xfce4?

### ISSUE THREAD

**Issue by phamt8611** [termux/proot-distro#8]
Hello guys, I am using google translate to do this article, if it is difficult to read, please sympathize.

I am using proot-distro to install Xfce4 for it, I have followed some directions on Google, but for no reason, all failed.

Here if anyone knows how, guide me with ...

**Comment by Grimler91** [comment]
xfce4 is a desktop environment, so you install it though the package manager of the distro you are using.
In ubuntu this would be `sudo apt-get install xfce4`. 

See also https://wiki.termux.com/wiki/Graphical_Environment

**Comment by phamt8611** [comment]
Yes, I tried through the management package to install, download is complete, always install vncserver.

But the problem is its vnc connection at the moment, the display on the screen is nothing ....

* Note: My distribution is Arch Linux

> xfce4 là môi trường máy tính để bàn, vì vậy bạn cài đặt nó thông qua trình quản lý gói của bản phân phối bạn đang sử dụng.
> Trong ubuntu điều này sẽ là `sudo apt-get install xfce4`.
> 
> Xem thêm [https://wiki.termux.com/wiki/Graphical_Enosystem](https://wiki.termux.com/wiki/Graphical_Environment)

Yes, I tried through the management package to install, download is complete, always install vncserver.

But the problem is its vnc connection at the moment, the display on the screen is nothing ....

* Note: My distribution is Arch Linux

**Comment by XCalibre8** [comment]
I know I'm 7 months late here and it's closed, but if I found it this could be handy for someone.

The simplest way would probably be to install your proot distro with with XFCE ready to go using the Andronix app.

Still, that's not what I did, I installed with LXDE and found this when looking at switching over my Debian DE after trying XFCE on Manjaro but finding the packages I wanted weren't on arch.

If you've got it installed correctly then what's missing is that you don't get a session selection prompt with these proot distro's and x11 needs configuring to know what you want.

So edit or create your ~/.vnc/xstartup file to be like this...

`xrdb $HOME/.Xresources
startxfce4 &`

Hopefully that will do the trick, worked for me after installing the task-xfce-desktop meta package (I never tried just the plain one, figured what the heck, I'm exploring Linux, lets get the big one!).

**Comment by phamt8611** [comment]
> I know I'm 7 months late here and it's closed, but if I found it this could be handy for someone.
> 
> The simplest way would probably be to install your proot distro with with XFCE ready to go using the Andronix app.
> 
> Still, that's not what I did, I installed with LXDE and found this when looking at switching over my Debian DE after trying XFCE on Manjaro but finding the packages I wanted weren't on arch.
> 
> If you've got it installed correctly then what's missing is that you don't get a session selection prompt with these proot distro's and x11 needs configuring to know what you want.
> 
> So edit or create your ~/.vnc/xstartup file to be like this...
> 
> `
> xrdb $HOME/.Xresources
> 
> startxfce4 &
> `
> **edit: tried to get the code block working with a line break but apparently that's a nope
> 
> Hopefully that will do the trick, worked for me after installing the task-xfce-desktop meta package (I never tried just the plain one, figured what the heck, I'm exploring Linux, lets get the big one!).

A little late, but thank you!
