### ISSUE TITLE
install to SD Card?

### ISSUE THREAD

**Issue by alix78** [termux/proot-distro#80]
my phone is rooted with magisk, can i install OSs on the SD Card?
i dont have much storage on the internal storage..

**Comment by WMCB-Tech** [comment]
I don't think it would be possible though as it was primarily designed for non-rooted and `proot-distro` stores distros in `$PREFIX/var/lib/proot-distro/installed-rootfs`

***

btw, if you're rooted, use Linux Deploy/chroot instead as it can install distros on sdcard

**Comment by ZhymabekRoman** [comment]
Yes, you need to have root rights on the Android system. Using the App2SD program (http://www.apps2sd.info/) you need to create a second partition on the SD card in the ext4 file system. next, you need to create a mount script and mount it to the system. It is in this program that this is done in one click. Now there are two options : you can move it completely (data, APK, and so on) Termux itself on the SD card, or just install the Linux distribution on the path : /data/sdext2.

I personally have Termux installed on the SD card using Apps2SD and everything is fine. By the way, do not forget that the SD card does not have very large write and read cycles, and it is possible that after an year of use, the card will go into "read only" mode. I've already had this happen

**Comment by alix78** [comment]
thank so much for ur help

**Comment by Jc-sims** [comment]
Dont know how i helped . But thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
