### ISSUE TITLE
Linux Distro

### ISSUE THREAD

**Issue by sugizo** [termux/proot-distro#81]
discuss or suggest about : 
- Add Distro Void, perhaps can learn from [AnLinux Script Installer](https://github.com/EXALAB/Anlinux-Resources/tree/master/Scripts/Installer/Void)
- Parrot has officialy stopped its [ARM image developement since 2019](https://github.com/AndronixApp/AndronixOrigin/issues/89) and there's isn't any active developement on it.
- In AnLinux Kali and Nethunter is have their [own image](https://github.com/EXALAB/Anlinux-Resources/tree/master/Scripts/Installer) (separated not join like on prott-distro)
- Seen the proot-distro is followed by the version, why not just put the distro name without version, perhaps if want to make separate it with LTS version or not, like on opensuse (leap and tumbleweed), so when the distro upgrade just change the script content not the script file name

thanks

**Comment by WMCB-Tech** [comment]
If you're adding a new distro, you can configure distro scripts in `$PREFIX/etc/proot-distro`

That directory contains shell script snippets and configuration for parsing distro settings, like the distro name, rootfs download link, and distro initial setup during the Installation, more like lxc templates or dockerfiles

You can see https://github.com/termux/proot-distro/tree/master/distro-plugins for reference

**Comment by xeffyr** [comment]
> Add Distro Void

Added in https://github.com/termux/proot-distro/commit/bc4429aeaec2883f4662e276b9787a2623bd1ea4.

> Parrot has officialy stopped its ARM image developement since 2019
In AnLinux Kali and Nethunter is have their own image (separated not join like on prott-distro)

Parrot OS and Kali support by `proot-distro` is questionable and possibly they would be removed.

> Seen the proot-distro is followed by the version, why not just put the distro name without version, perhaps if want to make separate it with LTS version

Initially distributions didn't used version suffixes. Things changed after versioned distributions were requested. May be reconsidered in future for LTS-only or Rolling, whichever version exist.
