### ISSUE TITLE
Please solve this problem Command apt-get update

### ISSUE THREAD

**Issue by gowwe** [termux/proot-distro#82]
GPG error: https://deb.parrot.sh/parrot lts InRelease: The following signatures were invalid: EXPKEYSIG B56FFA946EB1660A Parrot project <team@parrotsec.org>
W: GPG error: https://deb.parrot.sh/parrot lts-security InRelease: The following signatures were invalid: EXPKEYSIG B56FFA946EB1660A Parrot project <team@parrotsec.org>

**Comment by WMCB-Tech** [comment]
Ignore that, as long the `/etc/apt/sources.list` entries appends:

```
deb [trusted=yes] 
```

Otherwise get a parrot keyring and place it in `/etc/apt/trusted.gpg.d`

**Comment by gowwe** [comment]
How do I get parrot keyring

في الأربعاء، ١٩ مايو ٢٠٢١ ٩:٤٤ ص marcusz ***@***.***> كتب:

**Comment by WMCB-Tech** [comment]
Can you still install programs?

Try:
```
apt install hello
```

And if it install successfully, then i supposed you ignore it

**Comment by gowwe** [comment]
E: Failed to fetch
https://deb.parrot.sh/parrot/pool/main/h/hello/hello_2.10-2_arm64.deb 404
Not Found [IP: 51.178.92.105 443]
E: Unable to fetch some archives, maybe run apt-get update or try with
--fix-missing?

في الأربعاء، ١٩ مايو ٢٠٢١ ١١:٢٣ ص marcusz ***@***.***> كتب:

**Comment by WMCB-Tech** [comment]
I tested on a fresh Parrot Installation and i was able to reproduce the same:
```
proot-distro login parrot-lts
apt update
apt install <package>
```

I have tried to install some packages like `htop` `git` or `hello` and they returned 404 error (non-existent link), there should be a alternative mirror for that but not sure where to find it

I guess Parrot Security Team should fix this problem

**Comment by GribanovIvan** [comment]
Not fixed yet.

**Comment by laudarch** [comment]
I faced same issues, you have to 
1. Change the repo from lts to rolling
`deb https://deb.parrot.sh/parrot/ rolling main contrib non-free
deb https://deb.parrot.sh/parrot/ rolling-security main contrib non-free`
2. Add the key
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys B56FFA946EB1660A`
3. sudo parrot-upgrade
