### ISSUE TITLE
Can't execute binary file 'aapt2' in Alpine distro.

### ISSUE THREAD

**Issue by masterjavaofficial** [termux/proot-distro#84]
I've installed Alpine using proot-distro. There I've installed openjdk11, gradle apks and cmdline-tools for Android development related perpose. But the binary files (such as aapt, aapt2, zipsigner) in build-tools downloaded by the sdkmanager are not running properly during APK build using gradle. I tried to run those by executing ./aapt and ./aapt2, but it says no such file or directory, although I can see them in the directory. Please tell me how to fix this.

**Comment by Yonle** [comment]
Like the error said, This because symlink issue. Also if you run a program that does not supported by your device arch, It won't work. So you should select a program that supported by your device arch.

**Comment by WMCB-Tech** [comment]
Probably missing dependencies, linked against GNU libc but alpine uses musl libc,

I suggest to:
* Make sure you install required dependencies

* Switch to Alternate Distro (Debian, Arch) as it uses GNU Libs

**Comment by xeffyr** [comment]
> Probably missing dependencies, linked against GNU libc but alpine uses musl libc,

Or incompatible arch or missing dependencies.
