### ISSUE TITLE
Audio in VNC

### ISSUE THREAD

**Issue by SaicharanKandukuri** [termux/proot-distro#85]
Can some help me in configuring sound in vnc

- my `~/.vnc/xstartup` file
```bash
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADRESS
export PULSE_SERVER=127.0.0.1
exec startxfce4
```
![Screenshot_20210604-093125_NetHunter KeX](https://user-images.githubusercontent.com/68287637/120744313-591ea680-c518-11eb-9ebf-cd0c8a4e48dc.jpg)

**Comment by LeapofAzzam-backup** [comment]
Type `start-pulseaudio` outside the proot-distro session

**Comment by WMCB-Tech** [comment]
`proot-distro` already specifies `PULSE_SERVER` in `/etc/profile.d/termux-proot.sh` accordingly, now open a new session and start PulseAudio daemon

```
pulseaudio --start --exit-idle-time=-1

pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1
```

Alternate suggestion is to use XSDL as audio backends

**Comment by ZhymabekRoman** [comment]
After several weeks of searching, I was able to fully launch pavucontrol - a graphical utility for adjusting the volume

1) Install Pulseaudio in Termux: pkg install pulseaudio -y
2) Enter this command in Termux: 
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

3) In proot system install pulseaudio and enter this command : 
export PULSE_SERVER=127.0.0.1 && pulseaudio --start --disable-shm=1 --exit-idle-time=-1

**Comment by SaicharanKandukuri** [comment]
Thanks @ZhymabekRoman  Looks like `pavucontrol` started right after second step 
> Enter this command in Termux:
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

3rd step is already done by `proot-distro`

![WhatsApp Image 2021-06-04 at 10 39 03 AM](https://user-images.githubusercontent.com/68287637/120749224-ce42a980-c521-11eb-85bd-c7c079cc6506.jpeg)

**Comment by ShivaShirsath** [comment]
> Thanks @ZhymabekRoman Looks like `pavucontrol` started right after second step
> 
> > Enter this command in Termux:
> > pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
> 
> 3rd step is already done by `proot-distro`
> 
> ![WhatsApp Image 2021-06-04 at 10 39 03 AM](https://user-images.githubusercontent.com/68287637/120749224-ce42a980-c521-11eb-85bd-c7c079cc6506.jpeg)

Reinstall the `pulseaudio` & naver touch it again

**Comment by pawn343** [comment]
> After several weeks of searching, I was able to fully launch pavucontrol - a graphical utility for adjusting the volume
> 
> 1) Install Pulseaudio in Termux: pkg install pulseaudio -y
> 2) Enter this command in Termux: 
> pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
> 
> 3) In proot system install pulseaudio and enter this command : 
> export PULSE_SERVER=127.0.0.1 && pulseaudio --start --disable-shm=1 --exit-idle-time=-1

only works for archlinux proot, i tried with alpine it showed error:
```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings                       ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory                                                                    ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name                          ALSA lib conf.c:5180:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory                                                                     ALSA lib conf.c:5703:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2666:(snd_pcm_open_noupdate) Unknown PCM default                          ERROR: Failed to load plugin /usr/lib/ao/plugins-4/libalsa.so => dlopen() failed
play FAIL ao: Could not open device: error 5                                             play FAIL sox: Sorry, there is no default audio device configured
```

**Comment by ZhymabekRoman** [comment]
> only works for archlinux proot

Debian-based distros also work perfectly
