### ISSUE TITLE
Variable environment

### ISSUE THREAD

**Issue by mySaYo** [termux/proot-distro#86]
Does adding the bin directory of termux to the variable environment have any effect?
My current pip is termux but Python is /usr/bin/python.

**Comment by ZhymabekRoman** [comment]
This is a special feature of proot-distro, which allows you to run Termux utilities in proot systems. As for pip, you need to install it in the proot system so that the modules are correctly installed in the Python environment

**Comment by mySaYo** [comment]
> This is a special feature of proot-distro, which allows you to run Termux utilities in proot systems. As for pip, you need to install it in the proot system so that the modules are correctly installed in the Python environment

I temporarily found that pip uses termux, and everything else is in the proot system. I went to the bin folder./pip to solve it. . Maybe I should use an alias.

**Comment by xeffyr** [comment]
If you want to use utility from proot'ed environment, then **install it in proot'ed environment**. In case of `pip` and Ubuntu/Debian distribution, you need to install the `python3-pip` package (one of differences between Termux and Ubuntu or Debian, even though all of them use `apt`).

Termux utilities work only within Termux environment, which is by default  mounted into proot'ed distribution rootfs.

**Comment by mySaYo** [comment]
> If you want to use utility from proot'ed environment, then **install it in proot'ed environment**. In case of `pip` and Ubuntu/Debian distribution, you need to install the `python3-pip` package (one of differences between Termux and Ubuntu or Debian, even though all of them use `apt`).
> 
> Termux utilities work only within Termux environment, which is by default mounted into proot'ed distribution rootfs.

It seems okay. If I didn't install it, I would use the one in twrmux, or if I installed it, I would use the one in proot.
