### ISSUE TITLE
Help needed xfce4-session not starting after updating xfce4 pkg and installing xfce4 goodies

### ISSUE THREAD

**Issue by human-V-oid** [termux/proot-distro#88]
I installed Ubuntu 20.04 in proot-distro on termux 
I updated xfce4 pkg 
Then installed xfce4-goodies and some more plugins
Afterwards when try to start desktop gui, this happens

`root@localhost:~# vncserver -localhost`

`New 'localhost:1 (root)' desktop is localhost:1`

`Starting applications specified in /root/.vnc/xstartup`
`Log file is /root/.vnc/localhost:1.log`

`root@localhost:~# export DISPLAY=":1"`
`root@localhost:~# xfce4-session`
`Unable to init server: Could not connect: Connection refused`
`xfce4-session: Cannot open display: .`
`Type 'xfce4-session --help' for usage.`

This happened for the second time 
The first time I reset the distro and again did the same as mentioned above

Pls help

**Comment by ZhymabekRoman** [comment]
Run xfce4 via the command:
`startxfce4`

**Comment by ZhymabekRoman** [comment]
> I tried that too but didn't help

Hmm, then shutdown VNC server (`vncserver -kill :1`) and add to end of `~/.vnc/xstartup` file this line:
```
startxfce4
```
And try again

**Comment by human-V-oid** [comment]
Sorry if I annoy you, but how do I edit this file?
I just started using termux 2 weeks ago so I'm a n00b :D

**Comment by ZhymabekRoman** [comment]
> how do I edit this file?

Use Nano: https://www.tecmint.com/learn-nano-text-editor-in-linux/

**Comment by human-V-oid** [comment]
> > how do I edit this file?
> 
> Use Nano: https://www.tecmint.com/learn-nano-text-editor-in-linux/

Did as you said but that did not solve the issue 
I've observed that maybe this happens only when I start the desktop gui second time, the first session on a fresh distro works fine.

**Comment by xeffyr** [comment]
Closing since this is not `proot-distro` script issue.
