### ISSUE TITLE
User other than root

### ISSUE THREAD

**Issue by mukhtharcm** [termux/proot-distro#9]
How to create a user other than root in proot ubuntu?
I really dont want to mess up with my installation.

**Comment by xeffyr** [comment]
> How to create a user other than root

`useradd`, then `su`/`sudo` for switching.

**Comment by mukhtharcm** [comment]
> > How to create a user other than root
> 
> `useradd`, then `su`/`sudo` for switching.

Is there any way to directly login to non root user?

**Comment by WMCB-Tech** [comment]
It's simple. you need to add the login command inside `.bashrc` file

eg:
`echo "su - username" >> .bashrc`

**Comment by xeffyr** [comment]
> Is there any way to directly login to non root user?

I hope you have read the help information of `proot-distro login` - this command allows to redefine login command and use something else instead of just root shell.

Try something like `proot-distro login ubuntu -- su - username`

**Comment by jj-sallo** [comment]
> Try something like `proot-distro login ubuntu -- su - username`

This will result in tty errors, making it impossible to use programs like emacs and breaking things all around.

For example, trying to start emacs results in: `emacs: Could not open file: /dev/tty`

> you need to add the login command inside .bashrc file

This works, but only when --termux-home is not specified.

Maybe adding a flag to login that switches --root-id to --change-id=*uid:gid* is a better option?

**Comment by xeffyr** [comment]
> This will result in tty errors

On your device maybe. Never seen such issue on any of mine.

> trying to start emacs results in: emacs: Could not open file: /dev/tty

I can't reproduce that. Emacs works perfectly as well as /dev/tty accessible. See below:
![screen](https://user-images.githubusercontent.com/25881154/99471053-832ec380-294e-11eb-8f71-d7882f6704e5.png)

> Maybe adding a flag to login that switches --root-id to --change-id=uid:gid is a better option?

`su` handles things better.

**Comment by jj-sallo** [comment]
Seems like it's specific to Ubuntu-18.04.

![Screenshot_20201117-204434](https://user-images.githubusercontent.com/60981826/99476321-f1a35f80-2915-11eb-9b7f-2f109aae231f.png)

Worked fine in Ubuntu 20.04. Haven't tried other distros.

I also tried to add a --user flag to login as described before and it worked fine in Ubuntu-18.04. Will upload a fork to Github soon.

Why is `su` preferred, if I may ask?

**Comment by xeffyr** [comment]
> Why is su preferred, if I may ask?

Because `su` is alternate implementation of `/bin/login`, transparently configures appropriate environment vars for user and handles PAM modules.

**Comment by vmobilez** [comment]
proot-distro login --user username dustro

example username eric, distro ubuntu-20.04

proot-distro login --user eric ubuntu-20.04
