### ISSUE TITLE
Alpine Linux 3.13.* require time64

### ISSUE THREAD

**Issue by amsitlab** [termux/proot-distro#91]
Alpine Linux 3.13.* for 32bit architecture require [time64](https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements)

**Comment by xeffyr** [comment]
And how this is related to `proot-distro` which is a shell script wrapper around proot?

**Comment by amsitlab** [comment]
Yes aarch64 will be fine, but no for armv7l 32bit ,  alpine linux repository 3.13 and edge use musl 1.2 https://gitlab.alpinelinux.org/alpine/aports/-/issues/11808
