### ISSUE TITLE
..apt fd 7 fstat(1: operation not permitted) [armhf]

### ISSUE THREAD

**Issue by SaicharanKandukuri** [termux/proot-distro#92]
![img](https://cdn.discordapp.com/attachments/851345999645507620/861948321772994610/IMG_20210706_143446.jpg)

`hippo` is my [custom plugin](https://raw.githubusercontent.com/RandomCoderOrg/ubuntu-on-android/armhf-patch/payload/hippo.sh) of ubuntu 21.04 fs from [cdimage](http://cdimage.ubuntu.com/ubuntu-base/releases/21.04/release/)

but I was [noticed](https://github.com/RandomCoderOrg/ubuntu-on-android/issues/34) this error in devices like this
```
Application version:
0.114
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.117+ #1 SMP PREEMPT Fri Mar 5 12:01:24 CST 2021 armv8l Android
Device manufacturer:
HUAWEI
Device model:
MRD-LX3
```
 So, any reasons why it actually happened and how to make it work(if possible)

**Comment by xeffyr** [comment]
proot-distro is only wrapper around proot. Proot issues should be submitted to https://github.com/termux/proot/issues.

This repository only about proot-distro script.
