### ISSUE TITLE
Proot-distro qemu mode isn't working

### ISSUE THREAD

**Issue by Pedro1234-code** [termux/proot-distro#95]
When I try to install Debian Buster i686 on my armhf phone modifying the distro plugin and enabling proot-distro qemu mode and installing the qemu-user-i386 package, it appears an error: vpid 1: terminated with signal 11.

How can I fix it?

**Comment by xeffyr** [comment]
This is not issue of proot-distro but rather of `proot` itself or `qemu-i386`. `proot-distro` is only a shell script for automating common use of these utilities.

Seems to be something device or architecture specific as I can't reproduce it (running i686 on aarch64):
![qemu-i686](https://user-images.githubusercontent.com/25881154/126878478-554c8a3b-c8e1-4f02-8990-41f12c1b2a72.png)

Proot is known to be unstable on some devices.
