### ISSUE TITLE
Ubuntu 20.04 Error When Upgrading To 21.04

### ISSUE THREAD

**Issue by dinaradenis** [termux/proot-distro#98]
I Want To Update My Ubuntu To 21.04 From 20.04, But I Found An Error : 

root@localhost:~# do-release-upgrade
Checking for a new Ubuntu release                    Get:1 Upgrade tool signature [819 B]                 Get:2 Upgrade tool [1268 kB]
Fetched 1269 kB in 6s (7351 B/s)                     authenticate 'hirsute.tar.gz' against 'hirsute.tar.gz.gpg'                                                extracting 'hirsute.tar.gz'                          
Reading cache                                        lspci: /sys/bus/pci/devices: No such file or directory                                                                                                         Checking package manager
                                                     
A fatal error occurred                                                                                    Please report this as a bug and include the files
/var/log/dist-upgrade/main.log and /var/log/dist-upgrade/apt.log in                                       your report. The upgrade has aborted.
Your original sources.list was saved in              /etc/apt/sources.list.distUpgrade.
                                                     Traceback (most recent call last):                   
File "/tmp/ubuntu-release-upgrader-tvflgqv0/hirsute", line 8, in
<module>                                             sys.exit(main())
                                                     File                                                 "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/DistUpgradeMain.py",                                   line 236, in main                                    if app.run():
                                                     File                                                 "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/DistUpgradeController.py",                             line 2024, in run                                    return self.fullUpgrade()
                                                     File                                                 "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/DistUpgradeController.py",
line 1794, in fullUpgrade                            if not self.prepare():                               
File                                                 "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/DistUpgradeController.py",
line 415, in prepare                                 self._sshMagic()

File                                                 "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/DistUpgradeController.py",
line 274, in _sshMagic
is_child_of_process_name("sshd")):                   
File "/tmp/ubuntu-release-upgrader-tvflgqv0/DistUpgrade/utils.py",                                        line 108, in is_child_of_process_name
with open(stat_file) as stat_f:
                                                     FileNotFoundError: [Errno 2] No such file or directory:                                                   '/proc/10689/stat'
                                                     
root@localhost:~#

What Should I Do To Upgrade My Ubuntu?

**Comment by WMCB-Tech** [comment]
don't use `update-manager` to upgrade your distro. instead, edit `/etc/apt/sources.list` file and change `focal` entries to `hirsute` then `apt dist-upgrade`

since `update-manager` is just apt itself, you probably don't need thar

**Comment by dinaradenis** [comment]
Thank You So Much!!! That Worked!!! 

![Screenshot_20210730-091531](https://user-images.githubusercontent.com/62831800/127589819-742ab7ed-e3a0-454f-80e5-e6b9e03b4663.png)

**Comment by dinaradenis** [comment]
Actually, I Install 21.10 ( Impish Indri ) Using The Same Way...


![Screenshot_20210730-130726](https://user-images.githubusercontent.com/62831800/127608647-539e5186-f4f4-4159-a086-eb375fb7d4e2.png)

**Comment by NoNameMan1231** [comment]
> don't use `update-manager` to upgrade your distro. instead, edit `/etc/apt/sources.list` file and change `focal` entries to `hirsute` then `apt dist-upgrade`
> 
> since `update-manager` is just apt itself, you probably don't need thar

But will it install Ubuntu 21.04's packages?

**Comment by ZhymabekRoman** [comment]
> > don't use `update-manager` to upgrade your distro. instead, edit `/etc/apt/sources.list` file and change `focal` entries to `hirsute` then `apt dist-upgrade`
> > since `update-manager` is just apt itself, you probably don't need thar
> 
> But will it install Ubuntu 21.04's packages?

yes

**Comment by NoNameMan1231** [comment]
> > 但是它会安装 Ubuntu 21.04 的软件包吗？
> 
> 是GREAT!

> > But will it install Ubuntu 21.04's packages?
> 
> yes

GREAT!
