### ISSUE TITLE
Can I Install Different Kernel?

### ISSUE THREAD

**Issue by dinaradenis** [termux/proot-distro#99]
I Want To Install Different Kernel In My Ubuntu 21.04 ( 20.04 ), But I Worry If I Broke Something, So I Install Or Don't / At Least Upgrade It?

**Comment by xeffyr** [comment]
No, your Ubuntu shares same kernel as Android OS coz works in user space.

Also `proot` is configured to specify fake kernel version anyway: https://github.com/termux/proot-distro/blob/master/proot-distro.sh#L1126
